export type PageMode = 'understand' | 'observe' | 'operate' | 'showcase';
export type PageDomain =
  | 'command' | 'finance' | 'manufacturing' | 'inventory' | 'procurement' | 'engineering'
  | 'epr' | 'knowledge' | 'sales' | 'market' | 'legal' | 'risk' | 'leadership' | 'admin';
export type PageOwner =
  | 'founder' | 'board' | 'finance' | 'operations' | 'engineering' | 'qa' | 'compliance'
  | 'sales' | 'market' | 'legal' | 'risk' | 'investors' | 'knowledge' | 'all';
export type PageMaturity = 'keep' | 'merge' | 'review';
export type NavigationGroup = 'Command' | 'Understand' | 'Observe' | 'Operate' | 'Showcase';
export interface PageMeta { mode: PageMode; domain: PageDomain; owner: PageOwner; maturity: PageMaturity; group: NavigationGroup; }
export interface RouteMeta extends PageMeta { route: string; label: string; }
const meta=(route:string,label:string,mode:PageMode,domain:PageDomain,owner:PageOwner,maturity:PageMaturity,group:NavigationGroup):RouteMeta=>({route,label,mode,domain,owner,maturity,group});
export const routeRegistry:Record<string,RouteMeta>={
'/command':meta('/command','Board','observe','command','board','keep','Command'),'/command/control-tower':meta('/command/control-tower','Command Tower','observe','command','founder','keep','Command'),'/command/management-intelligence':meta('/command/management-intelligence','Management Intelligence','observe','command','founder','keep','Command'),'/command/governance':meta('/command/governance','Governance & Approvals','observe','command','founder','keep','Command'),'/command/founder-command':meta('/command/founder-command','Founder Command','operate','command','founder','keep','Command'),'/command/founder-control':meta('/command/founder-control','Founder Control','operate','command','founder','keep','Command'),'/command/decision-engine':meta('/command/decision-engine','Decision Engine','operate','command','founder','keep','Command'),'/command/classification':meta('/command/classification','Classification','operate','command','founder','keep','Command'),'/command/master-data':meta('/command/master-data','Master Data Engine','operate','admin','founder','keep','Command'),'/command/users':meta('/command/users','User Access Control','operate','admin','founder','keep','Command'),'/command/investor-board':meta('/command/investor-board','Investor / Board','observe','command','investors','keep','Observe'),
'/command/knowledge':meta('/command/knowledge','Knowledge Base','understand','knowledge','all','keep','Understand'),'/command/technical':meta('/command/technical','Technical','understand','knowledge','engineering','keep','Understand'),'/command/design-philosophy':meta('/command/design-philosophy','Design Philosophy','understand','knowledge','founder','keep','Understand'),'/command/ai-knowledge':meta('/command/ai-knowledge','AI Knowledge','understand','knowledge','all','merge','Understand'),
'/command/balance-sheet':meta('/command/balance-sheet','Balance Sheet','observe','finance','finance','keep','Observe'),'/command/finance':meta('/command/finance','Finance Dashboard','observe','finance','finance','keep','Observe'),'/command/ca-audit':meta('/command/ca-audit','CA Verification / Audit','observe','finance','finance','keep','Observe'),'/command/scenarios':meta('/command/scenarios','Scenario Analysis','observe','finance','founder','review','Observe'),'/command/qa-verification':meta('/command/qa-verification','QA Verification','observe','manufacturing','qa','review','Observe'),'/command/epr-live':meta('/command/epr-live','Live EPR Transactions','observe','epr','compliance','keep','Observe'),
'/command/finance-assumptions':meta('/command/finance-assumptions','Financial Planning','operate','finance','finance','keep','Operate'),'/command/master-finance':meta('/command/master-finance','Master Finance','operate','finance','finance','review','Operate'),'/command/finance-control':meta('/command/finance-control','Finance Control','operate','finance','finance','keep','Operate'),'/command/funding':meta('/command/funding','Funding Intelligence','operate','finance','founder','keep','Operate'),'/command/cash':meta('/command/cash','Cash & Working Capital','operate','finance','finance','keep','Operate'),'/command/operations':meta('/command/operations','Operations & Procurement','operate','procurement','operations','keep','Operate'),'/command/inventory':meta('/command/inventory','Inventory Planning','operate','inventory','operations','keep','Operate'),'/command/inventory-truth':meta('/command/inventory-truth','Inventory Truth','operate','inventory','operations','keep','Operate'),'/inventory':meta('/inventory','Component Control','operate','inventory','operations','keep','Operate'),'/command/production':meta('/command/production','Production Planning','operate','manufacturing','operations','keep','Operate'),'/command/manufacturing':meta('/command/manufacturing','Manufacturing Controls','operate','manufacturing','operations','keep','Operate'),'/command/quality':meta('/command/quality','Quality Control','operate','manufacturing','qa','keep','Operate'),'/command/product':meta('/command/product','Product','operate','engineering','engineering','keep','Operate'),'/command/bom':meta('/command/bom','BOM & Cost Engine','operate','engineering','engineering','keep','Operate'),'/command/engineering':meta('/command/engineering','Engineering Control','operate','engineering','engineering','keep','Operate'),'/command/epr-workflow':meta('/command/epr-workflow','EPR Workflow','operate','epr','compliance','keep','Operate'),'/command/epr-execution':meta('/command/epr-execution','EPR Execution','operate','epr','compliance','keep','Operate'),
'/command/investor-pitch':meta('/command/investor-pitch','Investor Demo','showcase','command','investors','keep','Showcase'),'/command/stakeholder-portal':meta('/command/stakeholder-portal','Business Story','showcase','leadership','investors','keep','Showcase'),'/command/platform-walkthrough':meta('/command/platform-walkthrough','Platform Walkthrough','showcase','command','investors','keep','Showcase'),'/command/demo-company':meta('/command/demo-company','Demo Company','showcase','command','investors','keep','Showcase'),
'/command/financial-cockpit':meta('/command/financial-cockpit','Financial Cockpit','observe','finance','founder','keep','Observe'),'/command/phase-4':meta('/command/phase-4','Phase 4 · Sales & Revenue','operate','sales','sales','keep','Operate'),'/command/phase-5':meta('/command/phase-5','Phase 5 · Engineering + QC','operate','engineering','engineering','keep','Operate'),'/command/phase-6':meta('/command/phase-6','Phase 6 · Pilot Production','operate','manufacturing','operations','keep','Operate'),'/command/phase-6a':meta('/command/phase-6a','Phase 6A · EPR Execution','operate','epr','compliance','keep','Operate'),'/command/deployment-readiness':meta('/command/deployment-readiness','Deployment Readiness','observe','command','founder','keep','Command'),'/command/aluminium-finance':meta('/command/aluminium-finance','Aluminium Vertical','observe','finance','founder','review','Observe'),'/command/ops':meta('/command/ops','Ops','operate','procurement','operations','review','Operate'),'/command/sales':meta('/command/sales','Sales Planning','operate','sales','sales','keep','Operate'),'/command/market-survey':meta('/command/market-survey','Market Survey','understand','market','market','keep','Understand'),'/command/gtm':meta('/command/gtm','GTM','operate','sales','market','keep','Operate'),'/command/legal':meta('/command/legal','Legal','understand','legal','legal','keep','Understand'),'/command/legal-control':meta('/command/legal-control','Legal Control','operate','legal','legal','keep','Operate'),'/command/risk':meta('/command/risk','Risk','observe','risk','risk','keep','Observe'),'/command/actions':meta('/command/actions','Action Log','operate','command','founder','keep','Command')};
export const navigationGroups:Record<NavigationGroup,RouteMeta[]>={Command:[],Understand:[],Observe:[],Operate:[],Showcase:[]};
for(const page of Object.values(routeRegistry))navigationGroups[page.group].push(page);
export const pagesByMode:Record<PageMode,RouteMeta[]>={observe:Object.values(routeRegistry).filter(p=>p.mode==='observe'),operate:Object.values(routeRegistry).filter(p=>p.mode==='operate'),understand:Object.values(routeRegistry).filter(p=>p.mode==='understand'),showcase:Object.values(routeRegistry).filter(p=>p.mode==='showcase')};
export const getRouteMeta=(route:string):RouteMeta|undefined=>routeRegistry[route];
export const getNavigationGroup=(group:NavigationGroup):RouteMeta[]=>navigationGroups[group];
