import type { AccountingRow } from "@/lib/finance/accounting";
import type { VentureScope } from "@/lib/finance/venture-scope";
export type BoardStatus="ahead"|"on-track"|"watch"|"critical";
export type BoardKpi={label:string;value:number;plan:number;variancePct:number;status:BoardStatus};
export type BoardRisk={id:string;title:string;impact:string;owner:string;status:"open"|"mitigating"|"closed"};
export const DEFAULT_BOARD_RISKS:BoardRisk[]=[{id:"R1",title:"Cash runway / funding timing",impact:"Liquidity",owner:"Founder",status:"mitigating"},{id:"R2",title:"Production ramp vs demand",impact:"Revenue / inventory",owner:"Operations",status:"open"},{id:"R3",title:"Engineering revision cost drift",impact:"COGS / margin",owner:"Engineering",status:"open"},{id:"R4",title:"Compliance evidence readiness",impact:"Tax / governance",owner:"Finance",status:"mitigating"}];
export const BOARD_RISKS_BY_VENTURE:Record<VentureScope,BoardRisk[]>={consolidated:DEFAULT_BOARD_RISKS,carbon:DEFAULT_BOARD_RISKS.map(r=>({...r,owner:r.owner==="Founder"?"Vyndi":r.owner})),aluminium:DEFAULT_BOARD_RISKS.map(r=>({...r,owner:r.owner==="Founder"?"Aluminium Venture":r.owner}))};
const pct=(v:number,p:number)=>p===0?0:((v-p)/Math.abs(p))*100; const state=(v:number,f:"higher"|"lower"="higher"):BoardStatus=>{const x=f==="higher"?v:-v;if(x>=10)return"ahead";if(x>=-5)return"on-track";if(x>=-15)return"watch";return"critical"};
export function buildBoardKpis(accounting:AccountingRow[],planAccounting:AccountingRow[],headcount?:number|null,planHeadcount?:number|null):BoardKpi[]{const c=accounting.at(-1)!,p=planAccounting.at(-1)!;const rv=pct(c.revenue,p.revenue),gm=c.revenue?(c.grossProfit/c.revenue)*100:0,pg=p.revenue?(p.grossProfit/p.revenue)*100:0,cv=pct(c.closingCash,p.closingCash),burn=Math.max(0,c.opex-c.grossProfit),pb=Math.max(0,p.opex-p.grossProfit);const k=[{label:"M36 revenue",value:c.revenue,plan:p.revenue,variancePct:rv,status:state(rv)},{label:"Gross margin %",value:gm,plan:pg,variancePct:gm-pg,status:state(gm-pg)},{label:"Closing cash",value:c.closingCash,plan:p.closingCash,variancePct:cv,status:state(cv)},{label:"Net operating burn",value:burn,plan:pb,variancePct:pct(burn,pb),status:state(pct(burn,pb),"lower")}];if(headcount!=null&&planHeadcount!=null){const v=pct(headcount,planHeadcount);k.push({label:"Headcount",value:headcount,plan:planHeadcount,variancePct:v,status:state(v,"lower")});}return k;}
export function boardSummary(accounting:AccountingRow[],planAccounting:AccountingRow[]){const t=accounting.reduce((m,r)=>r.closingCash<m.closingCash?r:m,accounting[0]),pt=planAccounting.reduce((m,r)=>r.closingCash<m.closingCash?r:m,planAccounting[0]),be=accounting.find(r=>r.ebitda>=0)?.m??null,neg=accounting.findIndex(r=>r.closingCash<0);return{cashTrough:t.closingCash,cashTroughMonth:t.m,planCashTrough:pt.closingCash,breakEven:be,runway:neg<0?accounting.length:neg,funding:accounting.reduce((s,r)=>s+r.equityFunding+r.debtDraw+r.grantFunding,0)};}
