import { buildAccountingModel, accountingTotals, type AccountingAssumptions } from "@/lib/finance/accounting";
import { buildModelWithInputs, type FinanceAssumptions, type ScenarioId } from "@/lib/finance/model";
import { buildScopedRows, type VentureScope } from "@/lib/finance/venture-scope";
export type DecisionScenarioId="base"|"upside"|"downside"|"stress"|"custom";
export type DecisionOverrides={aspPct:number;cogsPct:number;unitPct:number;launchShift:number;opexPct:number;collectionDaysDelta:number;supplierDaysDelta:number;aluminiumVolumePct:number};
export type DecisionScenario={id:DecisionScenarioId;label:string;description:string;overrides:DecisionOverrides;venture?:VentureScope};
export type DecisionStatus="proceed"|"watch"|"funding"|"stop";
export type DecisionRecord={id:string;createdAt:string;scenarioId:DecisionScenarioId;scenarioLabel:string;overrides:DecisionOverrides;status:DecisionStatus;recommendation:string;cashTrough:number;cashTroughMonth:number;runway:number;fundingGap:number;breakEvenMonth:number|null;note:string;venture?:VentureScope};
export type DecisionResult={scenario:DecisionScenario;rows:ReturnType<typeof buildModelWithInputs>;accounting:ReturnType<typeof buildAccountingModel>;revenue:number;units:number;grossProfit:number;ebitda:number;closingCash:number;cashTrough:number;cashTroughMonth:number;runway:number;funding:number;fundingGap:number;breakEvenMonth:number|null};
export const DEFAULT_DECISION_OVERRIDES:Record<Exclude<DecisionScenarioId,"custom">,DecisionOverrides>={base:{aspPct:0,cogsPct:0,unitPct:0,launchShift:0,opexPct:0,collectionDaysDelta:0,supplierDaysDelta:0,aluminiumVolumePct:0},upside:{aspPct:8,cogsPct:-4,unitPct:25,launchShift:-1,opexPct:4,collectionDaysDelta:-10,supplierDaysDelta:5,aluminiumVolumePct:20},downside:{aspPct:-7,cogsPct:8,unitPct:-20,launchShift:2,opexPct:10,collectionDaysDelta:15,supplierDaysDelta:-10,aluminiumVolumePct:-15},stress:{aspPct:-12,cogsPct:20,unitPct:-35,launchShift:4,opexPct:18,collectionDaysDelta:30,supplierDaysDelta:-15,aluminiumVolumePct:-30}};
export const DECISION_SCENARIOS:DecisionScenario[]=[{id:"base",label:"Base",description:"Approved operating plan with no decision shock.",overrides:DEFAULT_DECISION_OVERRIDES.base},{id:"upside",label:"Upside",description:"Faster ramp, stronger ASP and modest cost improvement.",overrides:DEFAULT_DECISION_OVERRIDES.upside},{id:"downside",label:"Downside",description:"Slower demand, cost pressure and launch slippage.",overrides:DEFAULT_DECISION_OVERRIDES.downside},{id:"stress",label:"Stress",description:"Severe commercial, cost and working-capital pressure.",overrides:DEFAULT_DECISION_OVERRIDES.stress}];
const clamp=(v:number)=>Math.max(-90,Math.min(200,v));
export function applyDecisionOverrides(finance:FinanceAssumptions,o:DecisionOverrides):FinanceAssumptions{const productLines=finance.productLines.map(l=>({...l,aspLakh:Math.max(0,l.aspLakh*(1+clamp(o.aspPct)/100)),cogsLakh:Math.max(0,l.cogsLakh*(1+clamp(o.cogsPct)/100)),launchMonth:Math.max(1,Math.min(36,Math.round(l.launchMonth+o.launchShift)))}));return{...finance,productLines,unitMultiplier:Math.max(0,finance.unitMultiplier*(1+clamp(o.unitPct)/100)),opexMultiplier:Math.max(0,finance.opexMultiplier*(1+clamp(o.opexPct)/100)),aluminiumVertical:{...finance.aluminiumVertical,volumeMultiplier:Math.max(0,finance.aluminiumVertical.volumeMultiplier*(1+clamp(o.aluminiumVolumePct)/100))}};}
export function applyAccountingOverrides(a:AccountingAssumptions,o:DecisionOverrides):AccountingAssumptions{return{...a,collectionDays:Math.max(0,(a.collectionDays??a.collectionMonths*30)+o.collectionDaysDelta),supplierPaymentDays:Math.max(0,(a.supplierPaymentDays??a.supplierCreditMonths*30)+o.supplierDaysDelta)};}
export function buildDecisionResult(s:DecisionScenario,finance:FinanceAssumptions,accounting:AccountingAssumptions,drawStandby:boolean):DecisionResult{const f=applyDecisionOverrides(finance,s.overrides),a=applyAccountingOverrides(accounting,s.overrides),scenario:ScenarioId=s.id==="stress"?"stress":s.id==="downside"?"delayed":"base",rows=buildScopedRows(s.venture??"consolidated",scenario,drawStandby,f),acc=buildAccountingModel(rows,a),t=accountingTotals(acc),cash=acc.map(r=>r.closingCash),trough=Math.min(...cash),ti=cash.indexOf(trough),neg=acc.findIndex(r=>r.closingCash<0),be=acc.findIndex(r=>r.ebitda>0),floor=Math.max(0,finance.managementCashFloorLakh??15);return{scenario:s,rows,accounting:acc,revenue:t.revenue,units:rows.reduce((x,r)=>x+r.units,0),grossProfit:t.grossProfit,ebitda:t.ebitda,closingCash:acc.at(-1)?.closingCash??0,cashTrough:trough,cashTroughMonth:ti+1,runway:neg>=0?neg:36,funding:t.funding,fundingGap:Math.max(0,floor-trough),breakEvenMonth:be>=0?be+1:null};}
export function decisionStatus(r:DecisionResult,b:DecisionResult):DecisionStatus{if(r.cashTrough<0||r.runway<6)return"stop";if(r.fundingGap>0||r.cashTrough<b.cashTrough-10)return"funding";if(r.cashTrough<b.cashTrough-5||r.runway<12)return"watch";return"proceed";}
export function decisionRecommendation(r:DecisionResult,b:DecisionResult){const s=decisionStatus(r,b);if(s==="stop")return"Stop or correct the operating plan before proceeding: cash falls below zero or runway is under six months.";if(s==="funding")return`Proceed only with a cash gate and funding plan. The modeled management-floor gap is ${r.fundingGap.toFixed(1)}L.`;if(s==="watch")return"Proceed with a management watch list and monthly variance review.";return"Proceed within the controlled plan; keep the assumptions under review.";}
const label=(f:keyof DecisionOverrides,d:number)=>f==="launchShift"?`${d>0?"+":""}${d} mo`:f.includes("Days")?`${d>0?"+":""}${d} days`:`${d>0?"+":""}${d}%`;
export function sensitivity(finance:FinanceAssumptions,accounting:AccountingAssumptions,draw:boolean,field:keyof DecisionOverrides,deltas=[-10,-5,5,10],venture:VentureScope="consolidated"){return deltas.map(d=>buildDecisionResult({id:"custom",label:label(field,d),description:`Sensitivity: ${String(field)}`,overrides:{...DEFAULT_DECISION_OVERRIDES.base,[field]:d},venture},finance,accounting,draw));}
export function fullSensitivity(finance:FinanceAssumptions,accounting:AccountingAssumptions,draw:boolean,venture:VentureScope="consolidated"){return(Object.keys(DEFAULT_DECISION_OVERRIDES.base) as(keyof DecisionOverrides)[]).map(field=>({field,results:sensitivity(finance,accounting,draw,field,[-10,-5,5,10],venture)}));}
