import { buildAccountingModel, DEFAULT_ACCOUNTING_ASSUMPTIONS, type AccountingAssumptions, type AccountingRow } from "@/lib/finance/accounting";
import { buildModelWithInputs, type FinanceAssumptions, type MonthRow, type ScenarioId } from "@/lib/finance/model";
export type VentureId="carbon"|"aluminium"|"parent";
export type VentureMonthRow=MonthRow&{venture:VentureId;directRevenue:number;directCogs:number;directOpex:number;sharedOpex:number;directCapex:number;directInventoryBuy:number;directFunding:number;openingCash:number;closingCash:number};
export type VentureFinancialModel={carbon:VentureMonthRow[];aluminium:VentureMonthRow[];parent:VentureMonthRow[];consolidated:VentureMonthRow[]};
function costs(f:FinanceAssumptions){return{carbon:f.productLines.find(x=>x.id==="carbon")!,premiumCarbon:f.productLines.find(x=>x.id==="premiumCarbon")!,aluminium:f.productLines.find(x=>x.id==="aluminium")!};}
function aluminiumInventory(row:MonthRow,f:FinanceAssumptions){const a=costs(f).aluminium;return row.m>=a.launchMonth&&row.aluminiumUnits>0?row.aluminiumUnits*a.cogsLakh*Math.max(0,f.aluminiumVertical.inventoryCover-1)*f.inventoryMultiplier:0;}
function ventureRow(row:MonthRow,v:VentureId,f:FinanceAssumptions,openingCash:number,previousCash:number,enabled:boolean,stress:boolean):VentureMonthRow{const c=costs(f),factor=stress?1.2:1,alRevenue=row.aluminiumUnits*c.aluminium.aspLakh,carbonRevenue=row.carbonUnits*c.carbon.aspLakh+row.premiumCarbonUnits*c.premiumCarbon.aspLakh,alCogs=row.aluminiumUnits*c.aluminium.cogsLakh*factor,carbonCogs=(row.carbonUnits*c.carbon.cogsLakh+row.premiumCarbonUnits*c.premiumCarbon.cogsLakh)*factor,alInv=aluminiumInventory(row,f),alOpex=row.m>=c.aluminium.launchMonth?f.aluminiumVertical.opexLakh:f.aluminiumVertical.opexLakh*.35,shared=Math.max(0,row.opex-alOpex),alCapex=enabled&&row.m===c.aluminium.launchMonth?f.aluminiumVertical.capexLakh*f.capexMultiplier:0,alFunding=enabled&&row.m===c.aluminium.launchMonth?f.aluminiumVertical.fundingLakh*f.fundingMultiplier:0,isAl=v==="aluminium",isCarbon=v==="carbon",revenue=isAl?alRevenue:isCarbon?carbonRevenue:0,cogs=isAl?alCogs:isCarbon?carbonCogs:0,opex=isAl?alOpex:0,capex=isAl?alCapex:isCarbon?Math.max(0,row.capex-alCapex):0,inventoryBuy=isAl?alInv:isCarbon?Math.max(0,row.inventoryBuy-alInv):0,funding=isAl?alFunding:isCarbon?Math.max(0,row.funding-alFunding):0,units=isAl?row.aluminiumUnits:isCarbon?row.carbonUnits+row.premiumCarbonUnits:0,closing=previousCash+funding+revenue-opex-capex-inventoryBuy;return{...row,venture:v,units,directRevenue:revenue,directCogs:cogs,directOpex:opex,sharedOpex:v==="parent"?shared:0,directCapex:capex,directInventoryBuy:inventoryBuy,directFunding:funding,openingCash,closingCash:closing,revenue,cogs,gp:revenue-cogs,opex,ebitda:revenue-cogs-opex,capex,inventoryBuy,funding,opening:openingCash,closing};}
export function buildVentureFinancialModel(scenario:ScenarioId,drawStandby:boolean,f:FinanceAssumptions):VentureFinancialModel{const rows=buildModelWithInputs(scenario,drawStandby,f),carbon:VentureMonthRow[]=[],aluminium:VentureMonthRow[]=[],parent:VentureMonthRow[]=[];let cc=f.openingCashLakh,ac=f.aluminiumVertical.openingCashLakh,pc=0,ci=0,ai=0;for(const row of rows){const enabled=scenario!=="stress",c=ventureRow(row,"carbon",f,cc,cc,enabled,scenario==="stress"),a=ventureRow(row,"aluminium",f,ac,ac,enabled,scenario==="stress"),p=ventureRow(row,"parent",f,pc,pc,enabled,scenario==="stress");cc=c.closingCash;ac=a.closingCash;ci=Math.max(0,ci+c.directInventoryBuy-c.directCogs);ai=Math.max(0,ai+a.directInventoryBuy-a.directCogs);c.inventory=ci;a.inventory=ai;pc=p.closingCash-p.sharedOpex;p.closingCash=pc;p.closing=pc;p.opex=p.sharedOpex;p.ebitda=-p.sharedOpex;carbon.push(c);aluminium.push(a);parent.push(p);}const consolidated=rows.map((row,i)=>{const c=carbon[i],a=aluminium[i],p=parent[i],revenue=c.revenue+a.revenue,cogs=c.cogs+a.cogs,opex=c.opex+a.opex+p.opex,capex=c.capex+a.capex,inventoryBuy=c.inventoryBuy+a.inventoryBuy,funding=c.funding+a.funding,closing=c.closing+a.closing+p.closing;return{...row,venture:"carbon" as VentureId,directRevenue:revenue,directCogs:cogs,directOpex:opex,sharedOpex:p.opex,directCapex:capex,directInventoryBuy:inventoryBuy,directFunding:funding,openingCash:c.openingCash+a.openingCash+p.openingCash,closingCash:closing,revenue,cogs,gp:revenue-cogs,opex,ebitda:revenue-cogs-opex,capex,inventoryBuy,funding,inventory:c.inventory+a.inventory,opening:c.openingCash+a.openingCash+p.openingCash,closing};});return{carbon,aluminium,parent,consolidated};}
export function ventureAccounting(models:VentureFinancialModel,assumptions:Partial<AccountingAssumptions>={}){const base={...DEFAULT_ACCOUNTING_ASSUMPTIONS,...assumptions},rows=(r:VentureMonthRow[]):MonthRow[]=>r.map(x=>({...x}));return{carbon:buildAccountingModel(rows(models.carbon),base),aluminium:buildAccountingModel(rows(models.aluminium),base),parent:buildAccountingModel(rows(models.parent),base),consolidated:buildAccountingModel(rows(models.consolidated),base)} as Record<VentureId,AccountingRow[]>;}
