import { buildAccountingModel, DEFAULT_ACCOUNTING_ASSUMPTIONS, type AccountingAssumptions, type AccountingRow } from "@/lib/finance/accounting";
import { buildModelWithInputs, type FinanceAssumptions, type MonthRow, type ScenarioId } from "@/lib/finance/model";

export type VentureId = "carbon" | "aluminium" | "parent";
export type VentureMonthRow = MonthRow & { venture: VentureId; directRevenue: number; directCogs: number; directOpex: number; sharedOpex: number; directCapex: number; directInventoryBuy: number; directFunding: number; openingCash: number; closingCash: number };
export type VentureFinancialModel = { carbon: VentureMonthRow[]; aluminium: VentureMonthRow[]; parent: VentureMonthRow[]; consolidated: VentureMonthRow[] };

function costs(finance: FinanceAssumptions) { return { carbon: finance.productLines.find(x=>x.id==="carbon")!, premiumCarbon: finance.productLines.find(x=>x.id==="premiumCarbon")!, aluminium: finance.productLines.find(x=>x.id==="aluminium")! }; }
function aluminiumInventory(row: MonthRow, finance: FinanceAssumptions) { const a=costs(finance).aluminium; return row.m>=a.launchMonth&&row.aluminiumUnits>0 ? row.aluminiumUnits*a.cogsLakh*Math.max(0,finance.aluminiumVertical.inventoryCover-1)*finance.inventoryMultiplier : 0; }
function ventureRow(row: MonthRow, venture: VentureId, finance: FinanceAssumptions, openingCash: number, previousCash: number, aluminiumEnabled: boolean): VentureMonthRow {
  const c=costs(finance), alRevenue=row.aluminiumUnits*c.aluminium.aspLakh, carbonRevenue=row.carbonUnits*c.carbon.aspLakh+row.premiumCarbonUnits*c.premiumCarbon.aspLakh, alCogs=row.aluminiumUnits*c.aluminium.cogsLakh, carbonCogs=row.carbonUnits*c.carbon.cogsLakh+row.premiumCarbonUnits*c.premiumCarbon.cogsLakh;
  const alInv=aluminiumInventory(row,finance), alOpex=row.m>=c.aluminium.launchMonth?finance.aluminiumVertical.opexLakh:finance.aluminiumVertical.opexLakh*.35, shared=Math.max(0,row.opex-alOpex), alCapex=aluminiumEnabled&&row.m===c.aluminium.launchMonth?finance.aluminiumVertical.capexLakh*finance.capexMultiplier:0, alFunding=aluminiumEnabled&&row.m===c.aluminium.launchMonth?finance.aluminiumVertical.fundingLakh*finance.fundingMultiplier:0;
  const isAl=venture==="aluminium", isCarbon=venture==="carbon", revenue=isAl?alRevenue:isCarbon?carbonRevenue:0, cogs=isAl?alCogs:isCarbon?carbonCogs:0, opex=isAl?alOpex:0, capex=isAl?alCapex:isCarbon?Math.max(0,row.capex-alCapex):0, inventoryBuy=isAl?alInv:isCarbon?Math.max(0,row.inventoryBuy-alInv):0, funding=isAl?alFunding:isCarbon?Math.max(0,row.funding-alFunding):0, closing=previousCash+funding+revenue-opex-capex-inventoryBuy;
  return {...row,venture,directRevenue:revenue,directCogs:cogs,directOpex:opex,sharedOpex:venture==="parent"?shared:0,directCapex:capex,directInventoryBuy:inventoryBuy,directFunding:funding,openingCash,closingCash:closing,revenue,cogs,gp:revenue-cogs,opex,ebitda:revenue-cogs-opex,capex,inventoryBuy,funding,opening:openingCash,closing};
}
export function buildVentureFinancialModel(scenario: ScenarioId, drawStandby: boolean, finance: FinanceAssumptions): VentureFinancialModel {
  const rows=buildModelWithInputs(scenario,drawStandby,finance), carbon:VentureMonthRow[]=[], aluminium:VentureMonthRow[]=[], parent:VentureMonthRow[]=[]; let cc=finance.openingCashLakh,ac=finance.aluminiumVertical.openingCashLakh,pc=0,ci=0,ai=0;
  for(const row of rows){const enabled=scenario!=="stress", c=ventureRow(row,"carbon",finance,cc,cc,enabled), a=ventureRow(row,"aluminium",finance,ac,ac,enabled), p=ventureRow(row,"parent",finance,pc,pc,enabled); cc=c.closingCash;ac=a.closingCash;ci=Math.max(0,ci+c.directInventoryBuy-c.directCogs);ai=Math.max(0,ai+a.directInventoryBuy-a.directCogs);c.inventory=ci;a.inventory=ai;pc=p.closingCash-p.sharedOpex;p.closingCash=pc;p.closing=pc;p.opex=p.sharedOpex;p.ebitda=-p.sharedOpex;carbon.push(c);aluminium.push(a);parent.push(p);}
  const consolidated=rows.map((row,i)=>{const c=carbon[i],a=aluminium[i],p=parent[i],revenue=c.revenue+a.revenue,cogs=c.cogs+a.cogs,opex=c.opex+a.opex+p.opex,capex=c.capex+a.capex,inventoryBuy=c.inventoryBuy+a.inventoryBuy,funding=c.funding+a.funding,closing=c.closing+a.closing+p.closing;return {...row,venture:"carbon" as VentureId,directRevenue:revenue,directCogs:cogs,directOpex:opex,sharedOpex:p.opex,directCapex:capex,directInventoryBuy:inventoryBuy,directFunding:funding,openingCash:c.openingCash+a.openingCash+p.openingCash,closingCash:closing,revenue,cogs,gp:revenue-cogs,opex,ebitda:revenue-cogs-opex,capex,inventoryBuy,funding,inventory:c.inventory+a.inventory,opening:c.openingCash+a.openingCash+p.openingCash,closing};});
  return {carbon,aluminium,parent,consolidated};
}
export function ventureAccounting(models: VentureFinancialModel, assumptions: Partial<AccountingAssumptions> = {}) { const base={...DEFAULT_ACCOUNTING_ASSUMPTIONS,...assumptions}; const rows=(r:VentureMonthRow[]):MonthRow[]=>r.map(x=>({...x})); return {carbon:buildAccountingModel(rows(models.carbon),base),aluminium:buildAccountingModel(rows(models.aluminium),base),parent:buildAccountingModel(rows(models.parent),base),consolidated:buildAccountingModel(rows(models.consolidated),base)} as Record<VentureId,AccountingRow[]>; }
