import { createFileRoute, Link, redirect } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { SiteFooter, SiteHeader } from "@/components/site-header";
import { SEED_INVENTORY, useInventory, type InventoryCategory, type InventoryItem } from "@/lib/data/inventory";
import { getCommandAccess, getCommandRole } from "@/lib/command-access";
import { canAccessRoute } from "@/lib/page-access";
import { inr } from "@/lib/format";

export const Route = createFileRoute("/inventory")({
  beforeLoad: async () => {
    const access = await getCommandAccess();
    if (!access) throw redirect({ to: "/command-login" });
    const role = await getCommandRole();
    if (!canAccessRoute(role, "/inventory")) throw redirect({ to: "/command" });
  },
  component: InventoryPage,
});

type Draft = Omit<InventoryItem, "updatedAt">;
const BASE_CATEGORIES: InventoryCategory[] = ["groupset","wheelset","tyre","handlebar","stem","saddle","thruaxle","bottom-bracket","bottle-cage","tool-pouch","bracket","fastener","colour","gauge"];
const CATEGORY_KEY = "veloxis-inventory-categories-v1";
const blank: Draft = { id:"",category:"groupset",subcategory:"",brand:"",model:"",detail:"",sku:"",priceInr:0,stockQty:0,reorderLevel:2,coreEnabled:false,proEnabled:false,apexEnabled:false,source:"Internal estimate — verify with supplier",notes:"" };
const title = (x:string) => x.replaceAll("-"," ").replace(/\b\w/g,c=>c.toUpperCase());
const slug = (x:string) => x.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
function readCategories(){ if(typeof window==="undefined") return BASE_CATEGORIES; try{return Array.from(new Set([...BASE_CATEGORIES,...(JSON.parse(window.localStorage.getItem(CATEGORY_KEY)||"[]") as string[])]));}catch{return BASE_CATEGORIES;} }
function InventoryPage(){
 const [role,setRole]=useState<"admin"|"viewer"|null>(null); const [items,setItems]=useInventory(SEED_INVENTORY); const [categories,setCategories]=useState<string[]>(BASE_CATEGORIES); const [editing,setEditing]=useState<Draft|null>(null); const [filter,setFilter]=useState("all"); const [categoryOpen,setCategoryOpen]=useState(false); const [categoryDraft,setCategoryDraft]=useState("");
 useEffect(()=>{getCommandRole().then(setRole).catch(()=>setRole(null));setCategories(readCategories())},[]);
 useEffect(()=>{const next=Array.from(new Set([...BASE_CATEGORIES,...categories,...items.map(x=>x.category)]));if(next.length!==categories.length)setCategories(next)},[items]);
 const visible=useMemo(()=>filter==="all"?items:items.filter(x=>x.category===filter),[items,filter]); const low=items.filter(x=>x.stockQty<=x.reorderLevel).length;
 function save(){if(!editing?.brand.trim()||!editing.model.trim()||!editing.sku.trim())return;setItems(editing.id&&items.some(x=>x.id===editing.id)?items.map(x=>x.id===editing.id?{...editing,updatedAt:new Date().toISOString()}:x):[...items,{...editing,id:editing.id||crypto.randomUUID(),updatedAt:new Date().toISOString()}]);setEditing(null)}
 function remove(id:string){if(window.confirm("Remove this component from inventory and the configurator?"))setItems(items.filter(x=>x.id!==id))}
 function addCategory(){const value=slug(categoryDraft);if(!value||categories.includes(value))return;const next=[...categories,value];setCategories(next);window.localStorage.setItem(CATEGORY_KEY,JSON.stringify(next.filter(x=>!BASE_CATEGORIES.includes(x as InventoryCategory))));setCategoryDraft("");setCategoryOpen(false)}
 const viewer=role==="viewer";
 return <div className="min-h-dvh bg-bg"><SiteHeader/><fieldset disabled={viewer} className="min-w-0 border-0 p-0 m-0"><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6">
  <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><Link to="/range" className="text-sm text-muted hover:text-accent">Range</Link><p className="mt-5 text-[11px] uppercase tracking-[0.22em] text-green">Operations · component control</p><h1 className="mt-2 text-4xl font-bold text-accent">Component inventory</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">The single component catalogue. These are the original component families and item records used by the configurator.</p></div><div className="flex gap-2"><button type="button" onClick={()=>setCategoryOpen(true)} className="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold">+ New category</button><button type="button" onClick={()=>setEditing({...blank,id:crypto.randomUUID()})} className="rounded-lg bg-accent px-4 py-2.5 text-sm font-semibold text-bg">+ Add component</button></div></header>
  <div className="mt-8 grid gap-3 sm:grid-cols-3"><Stat label="Component models" value={String(items.length)}/><Stat label="Low / reorder" value={String(low)}/><Stat label="Selectable now" value={String(items.filter(x=>x.stockQty>0&&(x.coreEnabled||x.proEnabled||x.apexEnabled)).length)}/></div>
  <div className="mt-8 flex gap-2 overflow-x-auto pb-1">{["all",...categories].map(x=><button key={x} type="button" onClick={()=>setFilter(x)} className={`shrink-0 rounded-full border px-3 py-1.5 text-xs font-semibold uppercase tracking-wider ${filter===x?"border-accent bg-accent/10 text-accent":"border-border text-muted"}`}>{x==="all"?"All":title(x)}</button>)}</div>
  <div className="mt-5 overflow-x-auto rounded-xl border border-border bg-bg-elevated/70"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-green"><tr><th className="px-4 py-3">Component</th><th className="px-4 py-3">SKU</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Stock</th><th className="px-4 py-3">Allowed range</th><th className="px-4 py-3">Source</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{visible.map(x=><tr key={x.id} className="border-t border-border/70"><td className="px-4 py-3"><p className="font-semibold text-fg">{x.brand} {x.model}</p><p className="text-xs text-muted">{title(x.category)} · {x.subcategory} · {x.detail}</p></td><td className="px-4 py-3 font-mono text-xs">{x.sku}</td><td className="px-4 py-3 tabular-nums">{inr(x.priceInr)}</td><td className="px-4 py-3"><span className={x.stockQty<=x.reorderLevel?"text-warn":"text-green"}>{x.stockQty}</span><span className="text-xs text-subtle"> / reorder {x.reorderLevel}</span></td><td className="px-4 py-3"><div className="flex gap-1.5 text-[10px] font-bold uppercase">{x.coreEnabled&&<span>Core</span>}{x.proEnabled&&<span>Pro</span>}{x.apexEnabled&&<span>Apex</span>}</div></td><td className="max-w-[240px] px-4 py-3 text-xs text-muted">{x.source}</td><td className="px-4 py-3"><div className="flex gap-3"><button type="button" onClick={()=>setEditing({...x})} className="text-xs font-semibold text-accent">Edit</button><button type="button" onClick={()=>remove(x.id)} className="text-xs text-muted">Remove</button></div></td></tr>)}</tbody></table></div>
  <div className="mt-6 rounded-xl border border-border p-4 text-xs leading-5 text-muted"><strong className="text-fg">Control:</strong> this page is the single user-facing component catalogue. Authoritative stock for ERP ledger reporting remains separate; this catalogue is the component identity/configurator source.</div>
 </main></fieldset>{editing&&<Editor draft={editing} categories={categories} setDraft={setEditing} onCancel={()=>setEditing(null)} onSave={save} onNewCategory={()=>setCategoryOpen(true)}/>} {categoryOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-border bg-bg p-6"><h2 className="text-xl font-bold text-accent">New component category</h2><input autoFocus value={categoryDraft} onChange={e=>setCategoryDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addCategory()} placeholder="e.g. pedals, seatpost" className="control mt-4"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setCategoryOpen(false)} className="rounded-lg border border-border px-4 py-2 text-sm">Cancel</button><button onClick={addCategory} className="rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-bg">Add</button></div></div></div>}<SiteFooter/></div>
}
function Editor({draft,categories,setDraft,onCancel,onSave,onNewCategory}:{draft:Draft;categories:string[];setDraft:(v:Draft)=>void;onCancel:()=>void;onSave:()=>void;onNewCategory:()=>void}){const patch=(p:Partial<Draft>)=>setDraft({...draft,...p});return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/70 p-4"><div className="mx-auto my-8 max-w-3xl rounded-2xl border border-border bg-bg p-6"><div className="flex justify-between"><h2 className="text-2xl font-bold text-accent">Component editor</h2><button onClick={onCancel}>Close</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{([["Category","category"],["Sub-category","subcategory"],["Brand","brand"],["Model","model"],["Detail / size","detail"],["SKU","sku"],["Price ₹","priceInr"],["Stock","stockQty"],["Reorder level","reorderLevel"],["Source","source"],["Notes","notes"]] as const).map(([label,key])=><label key={key} className="text-xs"><span className="mb-1 block text-subtle">{label}</span>{key==="category"?<div className="flex gap-2"><select value={draft.category} onChange={e=>patch({category:e.target.value as InventoryCategory})} className="control">{categories.map(c=><option key={c}>{c}</option>)}</select><button type="button" onClick={onNewCategory}>New</button></div>:<input className="control" type={key==="priceInr"||key==="stockQty"||key==="reorderLevel"?"number":"text"} value={String(draft[key])} onChange={e=>patch({[key]:key==="priceInr"||key==="stockQty"||key==="reorderLevel"?Number(e.target.value):e.target.value} as Partial<Draft>)}/>}</label>)}<div className="flex items-center gap-4 text-xs">{(["coreEnabled","proEnabled","apexEnabled"] as const).map(k=><label key={k}><input type="checkbox" checked={draft[k]} onChange={e=>patch({[k]:e.target.checked} as Partial<Draft>)}/> {k.replace("Enabled","")}</label>)}</div></div><div className="mt-6 flex justify-end gap-2"><button onClick={onCancel} className="rounded-lg border border-border px-4 py-2">Cancel</button><button onClick={onSave} className="rounded-lg bg-accent px-4 py-2 font-semibold text-bg">Save</button></div></div></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-border bg-bg-elevated/40 p-4"><p className="text-[10px] uppercase tracking-wider text-subtle">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums text-accent">{value}</p></div>}
