-- One governed production release per confirmed bike/order batch.
-- The release freezes the job-card revision, auto-registers one traveller per unit,
-- passes EPR-04 using the production approval as accepted evidence, and converts
-- committed material shortages into auditable draft PO shells.
-- Draft POs are NOT supplier commitments: supplier/commercial completion and an
-- independent approval are still required before issue.

alter table epr_production_job_cards
  add column if not exists batch_code text,
  add column if not exists approved_by text,
  add column if not exists approved_at timestamptz;

create unique index if not exists epr_production_job_cards_batch_code_uq
  on epr_production_job_cards(batch_code)
  where batch_code is not null;

alter table vyndi_purchase_orders alter column supplier_id drop not null;
alter table vyndi_purchase_orders
  add column if not exists job_card_id text references epr_production_job_cards(id) on delete restrict,
  add column if not exists auto_generated boolean not null default false;

alter table vyndi_purchase_orders drop constraint if exists vyndi_purchase_orders_supplier_required_check;
alter table vyndi_purchase_orders add constraint vyndi_purchase_orders_supplier_required_check
  check (status in ('draft','cancelled') or supplier_id is not null);

create index if not exists vyndi_purchase_orders_job_card_idx
  on vyndi_purchase_orders(job_card_id,status,sku)
  where job_card_id is not null;

create or replace view vyndi_purchase_order_status as
select p.*,
       coalesce(s.name,'Supplier not assigned') as supplier_name,
       coalesce(s.currency,'INR') as currency,
       coalesce(r.quantity_received,0) as quantity_received,
       coalesce(r.quantity_accepted,0) as quantity_accepted,
       greatest(p.quantity-coalesce(r.quantity_accepted,0),0) as quantity_open,
       p.quantity*p.unit_price_inr as order_value_inr
  from vyndi_purchase_orders p
  left join vyndi_suppliers s on s.id=p.supplier_id
  left join (
    select purchase_order_id,sum(quantity_received) quantity_received,sum(quantity_accepted) quantity_accepted
      from vyndi_goods_receipts group by purchase_order_id
  ) r on r.purchase_order_id=p.id;

create or replace function submit_vyndi_draft_purchase_order(
  p_id text,
  p_supplier_id text,
  p_unit_price_inr numeric,
  p_expected_receipt_on date,
  p_payment_terms_days integer,
  p_source_reference text,
  p_notes text,
  p_actor_user_id text,
  p_actor_role text
) returns text
language plpgsql
as $$
declare p record;
begin
  select * into p from vyndi_purchase_orders where id=p_id for update;
  if p.id is null then raise exception 'Purchase order not found.'; end if;
  if p.status<>'draft' then raise exception 'Only a draft purchase order can be submitted; current status is %.',p.status; end if;
  if trim(coalesce(p_source_reference,''))='' then raise exception 'Supplier quotation / evidence reference is required.'; end if;
  if p_unit_price_inr<=0 then raise exception 'A positive controlled supplier price is required before PO submission.'; end if;
  if p_expected_receipt_on<p.order_date then raise exception 'Expected receipt cannot precede the order date.'; end if;
  if p_payment_terms_days<0 or p_payment_terms_days>365 then raise exception 'Payment terms must be between 0 and 365 days.'; end if;
  if not exists(select 1 from vyndi_suppliers where id=upper(trim(p_supplier_id)) and active=true and approval_status='approved') then
    raise exception 'PO submission requires an active approved supplier.';
  end if;

  update vyndi_purchase_orders
     set supplier_id=upper(trim(p_supplier_id)),
         unit_price_inr=p_unit_price_inr,
         expected_receipt_on=p_expected_receipt_on,
         payment_terms_days=p_payment_terms_days,
         source_reference=p_source_reference,
         notes=coalesce(p_notes,''),
         status='pending_approval',
         updated_by=p_actor_user_id,
         updated_at=now()
   where id=p_id;

  insert into vyndi_audit_events
    (id,entity_type,entity_id,action,actor_user_id,actor_role,source_reference,payload_json)
  values
    ('AUD-'||p_id||'-SUBMIT-'||substr(md5(clock_timestamp()::text),1,8),'purchase_order',p_id,
     'submitted_for_approval',p_actor_user_id,p_actor_role,p_source_reference,
     jsonb_build_object('supplierId',upper(trim(p_supplier_id)),'unitPriceInr',p_unit_price_inr,
       'autoGenerated',p.auto_generated,'jobCardId',p.job_card_id));
  return p_id;
end;
$$;

create or replace function transition_vyndi_purchase_order(
  p_id text,p_next_status text,p_source_reference text,p_actor_user_id text,p_actor_role text
) returns text language plpgsql as $$
declare v_current text;
begin
  select status into v_current from vyndi_purchase_orders where id=p_id for update;
  if v_current is null then raise exception 'Purchase order not found.'; end if;
  if not ((v_current='draft' and p_next_status='cancelled') or
          (v_current='pending_approval' and p_next_status in ('approved','cancelled')) or
          (v_current='approved' and p_next_status in ('issued','cancelled')) or
          (v_current in ('issued','part_received') and p_next_status='cancelled')) then
    raise exception 'Purchase order transition % -> % is not allowed.',v_current,p_next_status;
  end if;
  if p_next_status='approved' and exists(select 1 from vyndi_purchase_orders where id=p_id and created_by=p_actor_user_id) then
    raise exception 'Purchase-order approval requires a different authorised user.';
  end if;
  if p_next_status in ('approved','issued') and exists(select 1 from vyndi_purchase_orders where id=p_id and supplier_id is null) then
    raise exception 'Supplier must be assigned before purchase-order approval or issue.';
  end if;
  update vyndi_purchase_orders set status=p_next_status,
    approved_by=case when p_next_status='approved' then p_actor_user_id else approved_by end,
    approved_at=case when p_next_status='approved' then now() else approved_at end,
    issued_by=case when p_next_status='issued' then p_actor_user_id else issued_by end,
    issued_at=case when p_next_status='issued' then now() else issued_at end,
    updated_by=p_actor_user_id,updated_at=now() where id=p_id;
  insert into vyndi_audit_events
    (id,entity_type,entity_id,action,actor_user_id,actor_role,source_reference,payload_json)
  values
    ('AUD-'||p_id||'-'||p_next_status||'-'||substr(md5(clock_timestamp()::text),1,8),'purchase_order',p_id,p_next_status,p_actor_user_id,p_actor_role,p_source_reference,
     jsonb_build_object('from',v_current,'to',p_next_status));
  return p_id;
end;
$$;

create or replace function approve_vyndi_production_batch(
  p_job_card_id text,
  p_actor_user_id text,
  p_actor_role text
) returns table (
  job_card_id text,
  batch_code text,
  travellers_created integer,
  po_drafts_created integer,
  shortage_sku_count integer
)
language plpgsql
as $$
declare
  c record;
  r record;
  t record;
  v_batch text;
  v_existing integer:=0;
  v_target integer:=0;
  v_travellers integer:=0;
  v_po_drafts integer:=0;
  v_shortage_skus integer:=0;
  v_seq integer;
  v_traveller_id text;
  v_serial text;
  v_action_id text;
  v_po_id text;
  v_price numeric:=0;
begin
  select jc.*,o.status as sales_status
    into c
    from epr_production_job_cards jc
    join vyndi_sales_orders o on o.id=jc.sales_order_id
   where jc.id=p_job_card_id
   for update of jc;
  if not found then raise exception 'Production job card not found.'; end if;
  if c.sales_status<>'confirmed' then raise exception 'Production release requires a confirmed Commercial order.'; end if;
  if c.status not in ('released','in_progress') then
    raise exception 'Production release requires a synchronized released job card; current status is %.',c.status;
  end if;
  if c.variant_id is null or trim(c.variant_id)='' then raise exception 'Job card has no exact VINDY variant.'; end if;
  if c.bom_revision is null or trim(c.bom_revision)='' then raise exception 'Job card has no released BOM revision.'; end if;
  if jsonb_array_length(coalesce(c.released_mapping_set,'[]'::jsonb))=0 then raise exception 'Job card has no released BOM mapping snapshot.'; end if;

  v_batch:=coalesce(c.batch_code,'BATCH-'||upper(substr(md5(c.id),1,12)));
  update epr_production_job_cards
     set batch_code=v_batch,
         approved_by=coalesce(approved_by,p_actor_user_id),
         approved_at=coalesce(approved_at,now()),
         updated_by=p_actor_user_id,
         updated_at=now()
   where id=c.id;

  v_target:=ceil(c.units)::integer;
  select count(*)::integer into v_existing
    from epr_travellers where job_card_id=c.id and status<>'rejected';

  if v_existing<v_target then
    for v_seq in (v_existing+1)..v_target loop
      v_traveller_id:='TRV-'||gen_random_uuid()::text;
      v_serial:='VYNDI-'||upper(c.model_tier)||'-'||upper(substr(md5(c.id),1,10))||'-'||lpad(v_seq::text,3,'0');
      perform raise_epr_traveller_for_job_card(
        v_traveller_id,c.id,v_serial,c.bom_revision,'',p_actor_user_id,p_actor_role
      );
      v_travellers:=v_travellers+1;
    end loop;
  end if;

  -- The single production approval is the accepted EPR-04 release evidence for
  -- every physical unit in the approved batch. Later EPR gates remain independent.
  for t in
    select id,venture,status from epr_travellers
     where job_card_id=c.id and status='draft'
     order by created_at,id
  loop
    if not exists(select 1 from epr_evidence where traveller_id=t.id and gate_id='EPR-04' and disposition='accepted') then
      insert into epr_evidence
        (id,traveller_id,gate_id,evidence_type,title,reference,disposition,notes,recorded_by)
      values
        ('EVD-'||gen_random_uuid()::text,t.id,'EPR-04','production_release','Single bike / batch production approval',
         v_batch,'accepted','Model, released BOM, job-card quantity and genealogy approved as one controlled build release.',p_actor_user_id);
    end if;
    if not exists(select 1 from epr_gate_events where traveller_id=t.id and gate_id='EPR-04' and status='passed') then
      insert into epr_gate_events(id,traveller_id,gate_id,status,reason,actor)
      values('GATE-'||gen_random_uuid()::text,t.id,'EPR-04','passed','Approved production batch '||v_batch,p_actor_user_id);
    end if;
    update epr_travellers set status='released',updated_at=now() where id=t.id;
    insert into epr_audit_events(id,venture,entity_type,entity_id,action,actor,payload_json)
    values('AUD-'||gen_random_uuid()::text,t.venture,'traveller',t.id,'auto_released_from_batch_approval',p_actor_user_id,
      json_build_object('jobCardId',c.id,'batchCode',v_batch,'bomRevision',c.bom_revision)::text);
  end loop;

  select count(*)::integer into v_shortage_skus
    from (
      select sku,vyndi_canonical_unit(unit)
        from vyndi_live_job_card_requirements
       where job_card_id=c.id and sku is not null and shortage_quantity>0
       group by sku,vyndi_canonical_unit(unit)
    ) s;

  for r in
    select sku,vyndi_canonical_unit(unit) as unit,sum(shortage_quantity) as shortage_quantity,min(job_card_line_id) as source_line
      from vyndi_live_job_card_requirements
     where job_card_id=c.id and sku is not null and shortage_quantity>0
     group by sku,vyndi_canonical_unit(unit)
     order by sku
  loop
    v_action_id:='JBREQ-'||upper(substr(md5(c.id||'|'||r.sku||'|'||r.unit),1,24));
    insert into epr_procurement_sku_actions
      (id,scenario,requirement_month,sku,unit,action_type,quantity,status,demand_basis,note,updated_by)
    values
      (v_action_id,'base',c.due_month,upper(r.sku),r.unit,'po',r.shortage_quantity,'planned','committed',
       'Auto-generated from approved Production job card '||c.id||' / batch '||v_batch,p_actor_user_id)
    on conflict (id) do update set
      quantity=excluded.quantity,
      status=case when epr_procurement_sku_actions.status in ('complete','cancelled') then epr_procurement_sku_actions.status else 'planned' end,
      note=excluded.note,updated_by=excluded.updated_by,updated_at=now();

    select coalesce(max(
      case when m.attributes->>'legacyPriceInr' ~ '^[0-9]+([.][0-9]+)?$'
           then (m.attributes->>'legacyPriceInr')::numeric else 0 end
    ),0)
      into v_price
      from master_data_records m
     where m.domain='inventory' and m.status='approved' and upper(m.code)=upper(r.sku);

    v_po_id:='AUTOPO-'||upper(substr(md5(c.id||'|'||r.sku||'|'||r.unit),1,20));
    if not exists(
      select 1 from vyndi_purchase_orders
       where id=v_po_id and status<>'cancelled'
    ) then
      insert into vyndi_purchase_orders
        (id,supplier_id,source_action_id,job_card_id,auto_generated,requirement_month,sku,unit,quantity,
         unit_price_inr,order_date,expected_receipt_on,payment_terms_days,status,source_reference,notes,created_by,updated_by)
      values
        (v_po_id,null,v_action_id,c.id,true,c.due_month,upper(r.sku),r.unit,r.shortage_quantity,
         v_price,current_date,current_date,0,'draft','AUTO:'||c.id,
         'Automatically generated from committed job-card shortage. Assign an approved supplier, confirm commercial price/lead time, then submit for independent approval.',
         p_actor_user_id,p_actor_user_id);
      v_po_drafts:=v_po_drafts+1;
      insert into vyndi_audit_events
        (id,entity_type,entity_id,entity_revision,action,actor_user_id,actor_role,source_reference,payload_json)
      values
        ('AUD-'||v_po_id,'purchase_order',v_po_id,c.sales_order_revision,'auto_draft_created_from_job_shortage',
         p_actor_user_id,p_actor_role,c.id,
         jsonb_build_object('jobCardId',c.id,'batchCode',v_batch,'sku',upper(r.sku),'quantity',r.shortage_quantity,
           'planningPriceInr',v_price,'supplierAssigned',false));
    end if;
  end loop;

  insert into vyndi_audit_events
    (id,entity_type,entity_id,entity_revision,action,actor_user_id,actor_role,source_reference,payload_json)
  values
    ('AUD-'||c.id||'-APPROVE-'||substr(md5(clock_timestamp()::text),1,8),'production_job_card',c.id,c.sales_order_revision,
     'bike_batch_approved',p_actor_user_id,p_actor_role,c.sales_order_id,
     jsonb_build_object('batchCode',v_batch,'units',c.units,'variantId',c.variant_id,'bomRevision',c.bom_revision,
       'travellersCreated',v_travellers,'shortageSkus',v_shortage_skus,'poDraftsCreated',v_po_drafts));

  return query select c.id,v_batch,v_travellers,v_po_drafts,v_shortage_skus;
end;
$$;
