import { useMemo } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Kpi, Panel } from "@/components/kpi";
import { buildModelWithInputs } from "@/lib/finance/model";
import { accountingTotals, buildAccountingModel, maxBalanceSheetError } from "@/lib/finance/accounting";
import { checkFinanceIntegrity } from "@/lib/finance/integrity";
import { useVeloxis } from "@/lib/store";
export const Route=createFileRoute("/command/balance-sheet")({component:BalanceSheet});
const f=(n:number)=>`₹${n.toFixed(1)}L`; const MONTHS=[1,6,12,18,24,30,36];
function BalanceSheet(){const {scenario,finance,accounting}=useVeloxis(); const planning=useMemo(()=>buildModelWithInputs(scenario,scenario!=="base",finance),[scenario,finance]); const rows=useMemo(()=>buildAccountingModel(planning,accounting),[planning,accounting]); const totals=useMemo(()=>accountingTotals(rows),[rows]); const last=rows.at(-1); const snapshots=MONTHS.map(m=>rows[m-1]).filter(Boolean); const bsError=maxBalanceSheetError(rows); const integrity=useMemo(()=>checkFinanceIntegrity(rows),[rows]); return <div className="space-y-6">
<header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Finance · Accounting layer</p><h1 className="font-display text-4xl">Financial Statements</h1><p className="mt-2 max-w-3xl text-sm text-muted">One accounting view tied directly to the live operating plan: accrual P&L, working capital, Balance Sheet and cash flow.</p><Link to="/command/finance-assumptions" className="mt-3 inline-block text-sm text-accent">Edit accounting controls →</Link></header>
<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="Revenue" value={f(totals.revenue)} hint="36-month accrual sales"/><Kpi label="Gross profit" value={f(totals.grossProfit)} hint="Revenue less COGS"/><Kpi label="EBITDA" value={f(totals.ebitda)} hint="Before depreciation"/><Kpi label="Net profit" value={f(totals.netProfit)} hint="After depreciation + tax"/><Kpi label="Closing cash" value={f(last?.closingCash??0)} hint="After AR/AP/GST timing" tone={(last?.closingCash??0)<0?"danger":"ok"}/></div>
<Panel title="Profit & Loss" kicker="₹ lakh · accrual basis"><div className="grid gap-2 md:grid-cols-3 lg:grid-cols-6">{[["Revenue","revenue"],["COGS","cogs"],["Gross profit","grossProfit"],["Opex","opex"],["Depreciation","depreciation"],["Net profit","netProfit"]].map(([label,key])=><div key={key} className="rounded-lg border border-border bg-surface p-3"><p className="text-[10px] uppercase tracking-wider text-subtle">{label}</p><p className="mt-1 text-xl tabular-nums">{f(Number(totals[key as keyof typeof totals]||0))}</p></div>)}</div></Panel>
<Panel title="Working Capital & Tax" kicker="Operating balances feeding cash"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="rounded-lg border border-border bg-surface p-4"><p className="text-xs text-subtle">M36 receivables</p><p className="mt-2 text-2xl">{f(last?.receivables??0)}</p><p className="mt-1 text-xs text-muted">Collection {accounting.collectionMonths}M</p></div><div className="rounded-lg border border-border bg-surface p-4"><p className="text-xs text-subtle">M36 inventory</p><p className="mt-2 text-2xl">{f(last?.inventory??0)}</p></div><div className="rounded-lg border border-border bg-surface p-4"><p className="text-xs text-subtle">M36 payables</p><p className="mt-2 text-2xl">{f(last?.payables??0)}</p><p className="mt-1 text-xs text-muted">Supplier credit {accounting.supplierCreditMonths}M</p></div><div className="rounded-lg border border-border bg-surface p-4"><p className="text-xs text-subtle">GST net payable</p><p className="mt-2 text-2xl">{f(last?.gstNetPayable??0)}</p><p className="mt-1 text-xs text-muted">Settlement {accounting.gstSettlementMonths}M</p></div><div className="rounded-lg border border-border bg-surface p-4"><p className="text-xs text-subtle">Purchases</p><p className="mt-2 text-2xl">{f(totals.purchases)}</p></div></div></Panel>
<Panel title="Balance Sheet" kicker="Selected month-end snapshots · ₹ lakh"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr><th className="px-3 py-3">Line item</th>{snapshots.map(r=><th key={r.m} className="px-3 py-3 text-right">M{r.m}</th>)}</tr></thead><tbody>{[["Cash & bank","closingCash"],["Trade receivables","receivables"],["Inventory","inventory"],["Net fixed assets","fixedAssetsNet"],["GST input-credit asset","gstNetPayable"],["Total assets","totalAssets"],["Trade payables","payables"],["Debt","debt"],["GST payable","gstNetPayable"],["Equity incl. funding","equity"],["Retained earnings","retainedEarnings"],["Total liabilities + equity","totalLiabilitiesEquity"],["Balance check","balanceCheck"]].map(([label,key])=><tr key={label} className="border-t border-border"><td className="px-3 py-3 font-medium">{label}</td>{snapshots.map(r=>{const raw=Number(r[key as keyof typeof r]||0); const value=label==="GST input-credit asset"?Math.max(0,-raw):label==="GST payable"?Math.max(0,raw):raw; return <td key={r.m} className="px-3 py-3 text-right tabular-nums">{f(value)}</td>})}</tr>)}</tbody></table></div></Panel>
<Panel title="Cash Flow" kicker="Operating · investing · financing"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-lg border border-border bg-surface p-4"><p className="text-xs text-subtle">Operating</p><p className="mt-2 text-2xl">{f(totals.operatingCashFlow)}</p></div><div className="rounded-lg border border-border bg-surface p-4"><p className="text-xs text-subtle">Investing</p><p className="mt-2 text-2xl">{f(totals.investingCashFlow)}</p></div><div className="rounded-lg border border-border bg-surface p-4"><p className="text-xs text-subtle">Financing</p><p className="mt-2 text-2xl">{f(totals.financingCashFlow)}</p></div></div></Panel>
<Panel title="Model integrity" kicker="Automated management checks"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Balance Sheet",integrity.balanced,`max error ${f(integrity.maxBalanceError)}`],["Cash Flow",integrity.cashReconciled,`max error ${f(integrity.maxCashError)}`],["Statements",integrity.statementsPresent,"P&L · BS · CF values present"],["Numeric model",integrity.finite,"No NaN / Infinity"]].map(([label,ok,hint])=><div key={label as string} className="rounded-lg border border-border bg-surface p-4"><div className="flex items-center justify-between"><p className="text-xs text-subtle">{label}</p><span className={ok?"text-ok":"text-danger"}>{ok?"PASS":"CHECK"}</span></div><p className="mt-2 text-xs text-muted">{hint}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-muted">These are management-model controls. A PASS means the model is internally consistent within the configured tolerance; it is not a substitute for CA ledger reconciliation.</p></Panel>
<Panel title="Accounting controls" kicker="Management reconciliation layer"><div className="grid gap-3 md:grid-cols-4"><div><p className="text-xs text-subtle">M36 receivables</p><p className="mt-1 text-lg">{f(last?.receivables??0)}</p></div><div><p className="text-xs text-subtle">M36 payables</p><p className="mt-1 text-lg">{f(last?.payables??0)}</p></div><div><p className="text-xs text-subtle">M36 fixed assets</p><p className="mt-1 text-lg">{f(last?.fixedAssetsNet??0)}</p></div><div><p className="text-xs text-subtle">Max BS error</p><p className="mt-1 text-lg">{f(bsError)}</p></div></div><p className="mt-4 rounded-md border border-border bg-surface p-3 text-xs leading-5 text-muted">Funding supports equity / debt / grant classification through the accounting assumptions. GST and tax remain management-planning controls and must be reconciled to actual invoices, eligible ITC, returns and the CA ledger before statutory use.</p></Panel></div>}
