import { createFileRoute, Link } from "@tanstack/react-router";
import { Kpi, Panel } from "@/components/kpi";
import { listCanonicalBalanceSheetAuthority } from "@/lib/finance-governance-authority";

type Row = Record<string, unknown>;
const num = (row: Row, ...keys: string[]) => { for (const key of keys) if (row[key] != null) return Number(row[key]) || 0; return 0; };
const text = (row: Row, ...keys: string[]) => { for (const key of keys) if (row[key] != null) return String(row[key]); return ""; };
const money = (value: number) => `₹${value.toFixed(2)}L`;

export const Route = createFileRoute("/command/balance-sheet")({
  loader: () => listCanonicalBalanceSheetAuthority(),
  component: BalanceSheet,
});

function BalanceSheet() {
  const snapshots = Route.useLoaderData() as Row[];
  const latest = snapshots.at(-1) ?? null;
  const latestError = latest ? num(latest,"balance_error_lakh","balanceErrorLakh") : 0;
  return <div className="space-y-6">
    <header className="border-b border-border pb-6"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-green">Finance · canonical financial statement authority</p><h1 className="mt-1 font-display text-4xl text-accent">Balance Sheet</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-muted">Only posted, source-referenced and balance-checked financial statement snapshots are shown here. Planning-model projections are deliberately kept outside this canonical register.</p><div className="mt-3 flex gap-3 text-sm font-semibold"><Link to="/command/cash" className="text-accent">Canonical Cash →</Link><Link to="/command/ca-audit" className="text-accent">CA Audit →</Link></div></header>
    <div className="grid gap-3 sm:grid-cols-4"><Kpi label="Posted snapshots" value={String(snapshots.length)} hint="Governed statement evidence" tone={snapshots.length ? "ok" : "warn"}/><Kpi label="Latest month" value={latest ? `M${num(latest,"plan_month","planMonth")}` : "None"} hint={latest ? text(latest,"as_of_date","asOfDate") : "No statement posted"}/><Kpi label="Latest assets" value={latest ? money(num(latest,"total_assets_lakh","totalAssetsLakh")) : "—"} hint="Posted authority"/><Kpi label="Balance error" value={latest ? money(latestError) : "—"} hint="Tolerance ≤ ₹0.01L" tone={Math.abs(latestError) <= 0.01 ? "ok" : "danger"}/></div>
    <Panel title="Posted Balance Sheet Register" kicker="Assets = liabilities + equity">{snapshots.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr><th className="px-3 py-3 text-left">Month / evidence</th><th className="px-3 py-3 text-right">Cash</th><th className="px-3 py-3 text-right">Receivables</th><th className="px-3 py-3 text-right">Inventory</th><th className="px-3 py-3 text-right">Fixed assets</th><th className="px-3 py-3 text-right">Total assets</th><th className="px-3 py-3 text-right">Payables</th><th className="px-3 py-3 text-right">Debt</th><th className="px-3 py-3 text-right">Equity + RE</th><th className="px-3 py-3 text-right">L+E</th><th className="px-3 py-3 text-right">Check</th></tr></thead><tbody>{snapshots.map((row) => <tr key={text(row,"id")} className="border-t border-border/70"><td className="px-3 py-3"><p className="font-semibold">M{num(row,"plan_month","planMonth")} · R{num(row,"revision")}</p><p className="max-w-xs text-[10px] text-muted">{text(row,"source_reference","sourceReference")}</p></td><td className="px-3 py-3 text-right">{money(num(row,"cash_lakh","cashLakh"))}</td><td className="px-3 py-3 text-right">{money(num(row,"receivables_lakh","receivablesLakh"))}</td><td className="px-3 py-3 text-right">{money(num(row,"inventory_lakh","inventoryLakh"))}</td><td className="px-3 py-3 text-right">{money(num(row,"fixed_assets_lakh","fixedAssetsLakh"))}</td><td className="px-3 py-3 text-right font-semibold">{money(num(row,"total_assets_lakh","totalAssetsLakh"))}</td><td className="px-3 py-3 text-right">{money(num(row,"payables_lakh","payablesLakh"))}</td><td className="px-3 py-3 text-right">{money(num(row,"debt_lakh","debtLakh"))}</td><td className="px-3 py-3 text-right">{money(num(row,"equity_lakh","equityLakh") + num(row,"retained_earnings_lakh","retainedEarningsLakh"))}</td><td className="px-3 py-3 text-right font-semibold">{money(num(row,"total_liabilities_equity_lakh","totalLiabilitiesEquityLakh"))}</td><td className={Math.abs(num(row,"balance_error_lakh","balanceErrorLakh")) <= 0.01 ? "px-3 py-3 text-right font-semibold text-ok" : "px-3 py-3 text-right font-semibold text-danger"}>{money(num(row,"balance_error_lakh","balanceErrorLakh"))}</td></tr>)}</tbody></table></div> : <div className="rounded-xl border border-dashed border-border p-6"><p className="font-semibold text-fg">No canonical Balance Sheet has been posted yet.</p><p className="mt-2 text-sm leading-6 text-muted">This is a controlled empty register, not a fabricated projection. A statement becomes visible only after an authorised balanced snapshot is posted with source evidence.</p></div>}</Panel>
    <p className="text-xs text-muted">Canonical source: <code>vyndi_financial_statement_snapshots</code> through <code>vyndi_balance_sheet_authority</code>. The writer rejects unbalanced statements.</p>
  </div>;
}
