import { createFileRoute, redirect } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Panel } from "@/components/kpi";
import { InventoryWorkspaceNav } from "@/components/inventory-workspace-nav";
import { approveControlledBomMapping, createControlledBomMapping, listControlledBomMappings, retireControlledBomMapping } from "@/lib/bom-mapping-authority";
import { getCommandAccess, getCommandRole } from "@/lib/command-access";
import { SEED_INVENTORY, type InventoryCategory } from "@/lib/data/inventory";
import { MODELS } from "@/lib/data/models";
import { canAccessRoute } from "@/lib/page-access";
import { isEligible } from "@/lib/product-configuration";

export const Route=createFileRoute("/command/bom-inventory-mapping")({beforeLoad:async()=>{if(!await getCommandAccess())throw redirect({to:"/command-login"});const role=await getCommandRole();if(!canAccessRoute(role,"/command/bom-inventory-mapping"))throw redirect({to:"/command"});},component:BomInventoryMappingPage});
type Mapping={id:string;venture:"carbon"|"aluminium";model_id:string;bom_revision:string;bom_line_key:string;sku:string;quantity:number|string;unit:string;status:string;configuration_category:InventoryCategory|null;configuration_option_id:string|null;approved_by?:string|null;approved_at?:string|null;notes?:string};
const planningScopes=[{id:"core",label:"Planning standard · Longitude",venture:"aluminium" as const},{id:"pro",label:"Planning standard · Latitude",venture:"carbon" as const},{id:"apex",label:"Planning standard · Altitude",venture:"carbon" as const}];
const configurableCategories=["groupset","wheelset","tyre","handlebar","stem","saddle","thruaxle","bottom-bracket","bottle-cage","tool-pouch","bracket","colour"] as const;
type ConfigurableCategory=(typeof configurableCategories)[number];

function BomInventoryMappingPage(){
  const [rows,setRows]=useState<Mapping[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const [form,setForm]=useState({modelId:MODELS.find((m)=>m.id==="core-105")?.id??MODELS[0].id,bomRevision:"BOM-001",bomLineKey:"",sku:"",quantity:"1",unit:"ea",configurationCategory:"" as ""|ConfigurableCategory,configurationOptionId:"",notes:""});
  const variant=MODELS.find((m)=>m.id===form.modelId);const planning=planningScopes.find((s)=>s.id===form.modelId);const venture=variant?(variant.tier==="core"?"aluminium":"carbon"):planning?.venture??"carbon";
  const eligible=useMemo(()=>!variant||!form.configurationCategory?[]:SEED_INVENTORY.filter((i)=>i.category===form.configurationCategory&&isEligible(i,variant.tier)),[form.configurationCategory,variant]);
  async function refresh(){const next=await listControlledBomMappings();if(!Array.isArray(next))throw new Error("BOM mapping register returned an invalid response. Refresh and retry.");setRows(next as Mapping[]);} useEffect(()=>{void refresh().catch((e)=>setError(e instanceof Error?e.message:"Unable to load mappings."));},[]);
  function chooseOption(id:string){const option=SEED_INVENTORY.find((i)=>i.id===id);setForm({...form,configurationOptionId:id,sku:option?.sku??form.sku,bomLineKey:form.bomLineKey||(option?`option:${option.category}`:"")});}
  async function create(){setBusy(true);setError("");try{await createControlledBomMapping({data:{venture,modelId:form.modelId,bomRevision:form.bomRevision,bomLineKey:form.bomLineKey,sku:form.sku,quantity:Number(form.quantity),unit:form.unit,configurationCategory:form.configurationCategory||null,configurationOptionId:form.configurationOptionId||null,notes:form.notes}});setForm({...form,bomLineKey:"",sku:"",quantity:"1",configurationCategory:"",configurationOptionId:"",notes:""});await refresh();}catch(e){setError(e instanceof Error?e.message:"Mapping creation failed.");}finally{setBusy(false);}}
  async function approve(id:string){setBusy(true);setError("");try{await approveControlledBomMapping({data:{mappingId:id}});await refresh();}catch(e){setError(e instanceof Error?e.message:"Approval failed.");}finally{setBusy(false);}}
  async function retire(id:string){const reason=window.prompt("Retirement reason");if(!reason)return;setBusy(true);setError("");try{await retireControlledBomMapping({data:{mappingId:id,reason}});await refresh();}catch(e){setError(e instanceof Error?e.message:"Retirement failed.");}finally{setBusy(false);}}
  const active=rows.filter((x)=>x.status==="active").length;const drafts=rows.filter((x)=>x.status==="draft").length;const scopes=[...new Set(rows.filter((x)=>x.status==="active").map((x)=>`${x.venture}|${x.model_id}`))];const ambiguous=scopes.filter((scope)=>new Set(rows.filter((x)=>x.status==="active"&&`${x.venture}|${x.model_id}`===scope).map((x)=>x.bom_revision)).size>1);
  return <div className="space-y-6">
    <header><p className="text-[11px] uppercase tracking-[0.2em] text-green">Controlled engineering → inventory authority</p><h1 className="mt-2 font-display text-4xl">BOM → Inventory SKU Mapping</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-muted">Release exact variants or planning-standard families against approved Inventory Master SKUs. Approval controls remain visible on every card; no horizontal register scrolling.</p></header><InventoryWorkspaceNav active="mapping"/>
    <div className="grid gap-3 sm:grid-cols-4"><Stat label="Mappings" value={String(rows.length)}/><Stat label="Active" value={String(active)}/><Stat label="Draft awaiting approval" value={String(drafts)} tone={drafts?"warn":"ok"}/><Stat label="Ambiguous scopes" value={String(ambiguous.length)} tone={ambiguous.length?"warn":"ok"}/></div>
    <Panel title="Create controlled mapping" kicker="Exact sellable variant or planning-standard family BOM"><div className="grid gap-4 md:grid-cols-4"><Field label="Mapping scope"><select className="control" value={form.modelId} onChange={(e)=>setForm({...form,modelId:e.target.value,configurationCategory:"",configurationOptionId:"",sku:""})}><optgroup label="Exact sellable variants">{MODELS.map((m)=><option key={m.id} value={m.id}>{m.name}</option>)}</optgroup><optgroup label="36-month planning standards">{planningScopes.map((s)=><option key={s.id} value={s.id}>{s.label}</option>)}</optgroup></select></Field><Field label="Venture"><input className="control uppercase" value={venture} disabled/></Field><Field label="BOM revision"><input className="control" value={form.bomRevision} onChange={(e)=>setForm({...form,bomRevision:e.target.value})}/></Field><Field label="BOM line key"><input className="control" value={form.bomLineKey} onChange={(e)=>setForm({...form,bomLineKey:e.target.value})} placeholder="stable controlled key"/></Field><Field label="Configuration category"><select className="control" value={form.configurationCategory} disabled={!variant} onChange={(e)=>setForm({...form,configurationCategory:e.target.value as ""|ConfigurableCategory,configurationOptionId:"",sku:""})}><option value="">Base BOM line</option>{configurableCategories.map((c)=><option key={c}>{c}</option>)}</select></Field><Field label="Controlled option"><select className="control" value={form.configurationOptionId} disabled={!form.configurationCategory} onChange={(e)=>chooseOption(e.target.value)}><option value="">Select option</option>{eligible.map((i)=><option key={i.id} value={i.id}>{i.brand} {i.model} · {i.sku}</option>)}</select></Field><Field label="Inventory SKU"><input className="control uppercase" value={form.sku} disabled={Boolean(form.configurationOptionId)} onChange={(e)=>setForm({...form,sku:e.target.value})} placeholder="approved SKU"/></Field><Field label="Qty / unit"><div className="grid grid-cols-2 gap-2"><input className="control" type="number" min="0.0001" step="0.01" value={form.quantity} onChange={(e)=>setForm({...form,quantity:e.target.value})}/><select className="control" value={form.unit} onChange={(e)=>setForm({...form,unit:e.target.value})}><option>ea</option><option>pair</option><option>set</option><option>m</option><option>kg</option><option>litre</option></select></div></Field></div><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs leading-5 text-muted">The server rejects unapproved SKUs, mismatched variants, ineligible options and ambiguous active revisions.</p><button disabled={busy||!form.bomLineKey||!form.sku||(Boolean(form.configurationCategory)!==Boolean(form.configurationOptionId))} onClick={()=>void create()} className="rounded-lg bg-accent px-4 py-2.5 text-sm font-semibold text-bg disabled:opacity-40">Create draft</button></div></Panel>
    {error?<div className="rounded-lg border border-warn/40 bg-warn/5 p-3 text-sm text-warn">{error}</div>:null}
    <Panel title="Mapping register" kicker="Responsive Draft → Active → Superseded">
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map((x)=><article key={x.id} className={`rounded-xl border p-4 ${x.status==="draft"?"border-warn/40 bg-warn/5":"border-border bg-bg-elevated/25"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs font-semibold text-fg">{x.sku}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-subtle">{x.model_id} · {x.venture}</p></div><span className={`text-[10px] font-bold uppercase ${x.status==="draft"?"text-warn":x.status==="active"?"text-green":"text-subtle"}`}>{x.status}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><Mini label="BOM revision" value={x.bom_revision}/><Mini label="Line" value={x.bom_line_key}/><Mini label="Option" value={x.configuration_option_id??"Base"}/><Mini label="Quantity" value={`${Number(x.quantity)} ${x.unit}`}/></div><div className="mt-4 border-t border-border/70 pt-3">{x.status==="draft"?<button disabled={busy} onClick={()=>void approve(x.id)} className="w-full rounded-md bg-accent px-3 py-2 text-xs font-semibold text-bg disabled:opacity-40">Approve mapping</button>:x.status==="active"?<button disabled={busy} onClick={()=>void retire(x.id)} className="w-full rounded-md border border-border px-3 py-2 text-xs font-semibold text-muted hover:border-warn hover:text-warn disabled:opacity-40">Retire / supersede</button>:<p className="text-xs text-subtle">Historical mapping retained for audit.</p>}</div></article>)}</div>
    </Panel>
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.14em] text-subtle">{label}</span>{children}</label>;}
function Stat({label,value,tone="normal"}:{label:string;value:string;tone?:"normal"|"warn"|"ok"}){return <div className="rounded-xl border border-border bg-bg-elevated/40 p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-subtle">{label}</p><p className={`mt-1 text-2xl font-bold ${tone==="warn"?"text-warn":tone==="ok"?"text-green":"text-accent"}`}>{value}</p></div>;}
function Mini({label,value}:{label:string;value:string}){return <div><p className="text-[9px] uppercase tracking-wider text-subtle">{label}</p><p className="mt-1 break-words font-semibold text-fg">{value}</p></div>;}
