import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { buildAccountingModel, accountingTotals } from "@/lib/finance/accounting";
import { buildModelWithInputs } from "@/lib/finance/model";
import { buildPeopleOpexMonths } from "@/lib/finance/people-opex-engine";
import { buildControlTowerSnapshot } from "@/lib/finance/control-tower-engine";
import { useVeloxis } from "@/lib/store";

export const Route = createFileRoute("/command/control-tower")({ component: ControlTower });
const money=(n:number)=>`₹${n.toFixed(1)}L`;
const tone=(status:"clear"|"watch"|"critical")=>status==="clear"?"text-ok":status==="watch"?"text-warn":"text-danger";
function ControlTower(){
 const scenario=useVeloxis(s=>s.scenario),drawStandby=useVeloxis(s=>s.drawStandby),finance=useVeloxis(s=>s.finance),accounting=useVeloxis(s=>s.accounting);
 const rows=useMemo(()=>buildModelWithInputs(scenario,drawStandby,finance),[scenario,drawStandby,finance]);
 const books=useMemo(()=>buildAccountingModel(rows,accounting),[rows,accounting]);
 const people=useMemo(()=>buildPeopleOpexMonths(finance.peopleOpex!),[finance.peopleOpex]);
 const snapshot=useMemo(()=>buildControlTowerSnapshot(rows,books,people,finance.managementCashFloorLakh??15),[rows,books,people,finance.managementCashFloorLakh]);
 const at=accountingTotals(books); const last=books.at(-1); const floor=finance.managementCashFloorLakh??15;
 return <div className="space-y-6"><header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Phase 10 · ERP / Control Tower</p><h1 className="font-display text-4xl">Control Tower</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">One operating view across finance, sales, production, inventory, engineering, quality, people and compliance. This is the control layer above the existing single financial engine.</p></header>
 <div className="rounded-xl border border-border bg-surface p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] uppercase tracking-[0.16em] text-subtle">System status</p><p className={`mt-1 font-display text-3xl ${tone(snapshot.status)}`}>{snapshot.status.toUpperCase()}</p></div><div className="text-left text-xs text-muted sm:text-right"><p>Scenario: <span className="text-fg">{scenario}</span></p><p>Management floor: <span className="text-fg">{money(floor)}</span></p></div></div></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Revenue" value={money(snapshot.metrics.revenue)} hint="36M accounting"/><Kpi label="Closing cash" value={money(snapshot.metrics.cash)} hint="M36"/><Kpi label="Inventory" value={money(snapshot.metrics.inventory)} hint="M36"/><Kpi label="Headcount" value={`${snapshot.metrics.headcount}`} hint="M36 plan"/></div>
 <Panel title="Exceptions & actions" kicker="Management controls generated from live model state"><div className="space-y-2">{snapshot.alerts.map(alert=><div key={alert.id} className="flex flex-col gap-3 rounded-lg border border-border bg-surface p-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><span className={`text-[10px] font-semibold uppercase tracking-wider ${tone(alert.status)}`}>{alert.status}</span><span className="text-sm font-medium text-fg">{alert.title}</span>{alert.month?<span className="text-[10px] text-subtle">M{alert.month}</span>:null}</div><p className="mt-1 text-xs leading-5 text-muted">{alert.detail}</p></div><span className="shrink-0 text-xs text-accent">{alert.action}</span></div>)}</div></Panel>
 <div className="grid gap-4 lg:grid-cols-2"><Panel title="Integrated operating state" kicker="The same numbers drive execution and finance"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><div><p className="text-[10px] uppercase text-subtle">Units</p><p className="mt-1 text-xl tabular-nums">{snapshot.metrics.units}</p></div><div><p className="text-[10px] uppercase text-subtle">AR</p><p className="mt-1 text-xl tabular-nums">{money(snapshot.metrics.receivables)}</p></div><div><p className="text-[10px] uppercase text-subtle">AP</p><p className="mt-1 text-xl tabular-nums">{money(snapshot.metrics.payables)}</p></div><div><p className="text-[10px] uppercase text-subtle">Purchases</p><p className="mt-1 text-xl tabular-nums">{money(at.purchases)}</p></div></div><p className="mt-4 text-xs leading-5 text-muted">Cash, working capital and operating totals come from the existing accounting layer; no second financial model is created here.</p></Panel><Panel title="Control domains" kicker="Drill into the system of record"><div className="grid gap-2 sm:grid-cols-2"><Link to="/command/decision-engine" className="rounded-lg border border-border p-3 text-sm hover:border-accent">Decision Engine →</Link><Link to="/command/operations" className="rounded-lg border border-border p-3 text-sm hover:border-accent">Operations & Procurement →</Link><Link to="/command/inventory" className="rounded-lg border border-border p-3 text-sm hover:border-accent">Inventory →</Link><Link to="/command/sales" className="rounded-lg border border-border p-3 text-sm hover:border-accent">Sales →</Link><Link to="/command/engineering" className="rounded-lg border border-border p-3 text-sm hover:border-accent">Engineering →</Link><Link to="/command/quality" className="rounded-lg border border-border p-3 text-sm hover:border-accent">Quality →</Link><Link to="/command/people-opex" className="rounded-lg border border-border p-3 text-sm hover:border-accent">People & Opex →</Link><Link to="/command/tax-compliance" className="rounded-lg border border-border p-3 text-sm hover:border-accent">Compliance →</Link></div></Panel></div>
 <Panel title="ERP control principle" kicker="Phase 10 foundation"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-lg border border-border p-4"><p className="text-sm font-semibold">One source of truth</p><p className="mt-1 text-xs leading-5 text-muted">Existing Zustand planning state remains the shared management state; the Control Tower only reads and consolidates it.</p></div><div className="rounded-lg border border-border p-4"><p className="text-sm font-semibold">Exception first</p><p className="mt-1 text-xs leading-5 text-muted">Managers see cash, inventory, sales and operating exceptions before drilling into detailed workspaces.</p></div><div className="rounded-lg border border-border p-4"><p className="text-sm font-semibold">Audit trail</p><p className="mt-1 text-xs leading-5 text-muted">Decisions remain recorded in the Phase 9 register; execution controls stay linked to the underlying modules.</p></div></div></Panel></div>;
}
