import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { buildDecisionResult, DECISION_SCENARIOS, DEFAULT_DECISION_OVERRIDES, decisionRecommendation, decisionStatus, fullSensitivity, type DecisionOverrides, type DecisionScenarioId } from "@/lib/finance/decision-engine";
import { useVeloxis } from "@/lib/store";

export const Route = createFileRoute("/command/decision-engine")({ component: DecisionEngine });
const money=(n:number)=>`₹${n.toFixed(1)}L`; const pct=(n:number)=>`${n>0?"+":""}${n.toFixed(1)}%`;
const fields:{key:keyof DecisionOverrides;label:string;min:number;max:number;step:number}[]=[
 {key:"aspPct",label:"ASP",min:-30,max:30,step:1},{key:"cogsPct",label:"COGS",min:-30,max:40,step:1},{key:"unitPct",label:"Units",min:-50,max:50,step:1},{key:"launchShift",label:"Launch shift",min:-6,max:12,step:1},{key:"opexPct",label:"Opex",min:-20,max:40,step:1},{key:"collectionDaysDelta",label:"Collection days",min:-30,max:60,step:1},{key:"supplierDaysDelta",label:"Supplier payment days",min:-30,max:60,step:1},{key:"aluminiumVolumePct",label:"Aluminium volume",min:-50,max:100,step:1}
];
const labels:Record<keyof DecisionOverrides,string>={aspPct:"ASP",cogsPct:"COGS",unitPct:"Units",launchShift:"Launch",opexPct:"Opex",collectionDaysDelta:"Collections",supplierDaysDelta:"Supplier credit",aluminiumVolumePct:"Aluminium"};
const STORAGE="veloxis-decision-overrides-v1";
function DecisionEngine(){
 const finance=useVeloxis(s=>s.finance); const accounting=useVeloxis(s=>s.accounting); const drawStandby=useVeloxis(s=>s.drawStandby);
 const [selected,setSelected]=useState<DecisionScenarioId>("base"); const [custom,setCustom]=useState<DecisionOverrides>(DEFAULT_DECISION_OVERRIDES.base); const [saved,setSaved]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw)setCustom({...DEFAULT_DECISION_OVERRIDES.base,...JSON.parse(raw)});}catch{}},[]);
 const scenarios=useMemo(()=>DECISION_SCENARIOS.map(s=>buildDecisionResult(s,finance,accounting,drawStandby)),[finance,accounting,drawStandby]); const base=scenarios[0];
 const customScenario=useMemo(()=>buildDecisionResult({id:"custom",label:"Custom",description:"Your controlled decision assumptions.",overrides:custom},finance,accounting,drawStandby),[custom,finance,accounting,drawStandby]);
 const active=selected==="custom"?customScenario:scenarios.find(s=>s.scenario.id===selected)??base; const status=decisionStatus(active,base);
 const sens=useMemo(()=>fullSensitivity(finance,accounting,drawStandby),[finance,accounting,drawStandby]);
 const update=(key:keyof DecisionOverrides,value:number)=>{setSaved(false);setCustom(v=>({...v,[key]:value}));};
 const save=()=>{try{localStorage.setItem(STORAGE,JSON.stringify(custom));setSaved(true);}catch{}};
 const reset=()=>{setCustom(DEFAULT_DECISION_OVERRIDES.base);try{localStorage.removeItem(STORAGE);}catch{}setSaved(false);};
 return <div className="space-y-6"><header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Phase 9 · Scenario / Decision Engine</p><h1 className="font-display text-4xl">Decision Cockpit</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">One controlled what-if layer. Every change propagates through units, revenue, COGS, Opex, working capital, accounting cash, runway and funding gap.</p></header>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="Decision" value={status.toUpperCase()} hint={decisionRecommendation(active,base)} tone={status==="proceed"?"ok":status==="watch"?"warn":"danger"}/><Kpi label="Cash trough" value={money(active.cashTrough)} hint={`M${active.cashTroughMonth}`}/><Kpi label="Runway" value={`${active.runway.toFixed(1)} mo`} hint="Accounting cash" tone={active.runway>=12?"ok":active.runway>=6?"warn":"danger"}/><Kpi label="Funding modeled" value={money(active.funding)}/><Kpi label="Funding gap" value={money(active.fundingGap)} hint="To maintain ₹15L floor" tone={active.fundingGap>0?"warn":"ok"}/></div>
 <Panel title="Scenario selector" kicker="Base · Upside · Downside · Stress · Custom"><div className="flex flex-wrap gap-2">{[...DECISION_SCENARIOS.map(s=>s.id),"custom" as DecisionScenarioId].map(id=>{const label=id==="custom"?"Custom":DECISION_SCENARIOS.find(s=>s.id===id)?.label??id;return <button key={id} type="button" onClick={()=>setSelected(id)} className={`rounded-md border px-4 py-2 text-sm ${selected===id?"border-accent bg-surface text-fg":"border-border text-muted hover:text-fg"}`}>{label}</button>})}</div><p className="mt-3 text-sm text-muted">{active.scenario.description}</p></Panel>
 <Panel title="What-if controls" kicker="Relative to the approved plan"><div className="grid gap-4 md:grid-cols-2">{fields.map(f=><label key={f.key} className="rounded-lg border border-border p-3"><div className="flex justify-between gap-3 text-sm"><span>{f.label}</span><span className="tabular-nums text-accent">{f.key==="launchShift"?`${custom[f.key]>0?"+":""}${custom[f.key]} mo`:pct(custom[f.key])}</span></div><input aria-label={f.label} type="range" min={f.min} max={f.max} step={f.step} value={custom[f.key]} onChange={e=>update(f.key,Number(e.target.value))} className="mt-3 w-full"/><div className="mt-1 flex justify-between text-[10px] text-subtle"><span>{f.min}{f.key==="launchShift"?" mo":"%"}</span><span>{f.max}{f.key==="launchShift"?" mo":"%"}</span></div></label>)}</div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={save} className="rounded-md border border-accent px-4 py-2 text-sm text-fg">{saved?"Saved":"Save custom scenario"}</button><button type="button" onClick={reset} className="rounded-md border border-border px-4 py-2 text-sm text-muted">Reset</button></div></Panel>
 <Panel title="36-month scenario comparison" kicker="Financial outcome from the same engine"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead><tr className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><th className="px-2 py-3">Scenario</th><th>Units</th><th>Revenue</th><th>Gross profit</th><th>EBITDA</th><th>Cash trough</th><th>Runway</th><th>Funding</th><th>Funding gap</th><th>Break-even</th></tr></thead><tbody>{[...scenarios,customScenario].map(r=><tr key={r.scenario.id} className={`border-b border-border last:border-0 ${r.scenario.id===active.scenario.id?"bg-surface":""}`}><td className="px-2 py-3 font-medium">{r.scenario.label}</td><td>{r.units.toFixed(0)}</td><td>{money(r.revenue)}</td><td>{money(r.grossProfit)}</td><td>{money(r.ebitda)}</td><td>{money(r.cashTrough)} <span className="text-xs text-muted">M{r.cashTroughMonth}</span></td><td>{r.runway.toFixed(1)} mo</td><td>{money(r.funding)}</td><td>{money(r.fundingGap)}</td><td>{r.breakEvenMonth?`M${r.breakEvenMonth}`:"—"}</td></tr>)}</tbody></table></div></Panel>
 <div className="grid gap-4 lg:grid-cols-2"><Panel title="Decision answer" kicker="Management action"><p className="text-sm leading-6">{decisionRecommendation(active,base)}</p><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted">Revenue vs base</span><span>{money(active.revenue-base.revenue)}</span></div><div className="flex justify-between"><span className="text-muted">Cash trough vs base</span><span>{money(active.cashTrough-base.cashTrough)}</span></div><div className="flex justify-between"><span className="text-muted">Funding gap</span><span>{money(active.fundingGap)}</span></div><div className="flex justify-between"><span className="text-muted">Runway change</span><span>{(active.runway-base.runway).toFixed(1)} mo</span></div></div></Panel>
 <Panel title="Sensitivity" kicker="One variable at a time"><div className="space-y-3 max-h-[420px] overflow-auto">{sens.map(group=><div key={group.field}><p className="mb-1 text-xs font-semibold text-fg">{labels[group.field]}</p><div className="grid gap-1 sm:grid-cols-4">{group.results.map(r=><div key={`${group.field}-${r.scenario.label}`} className="rounded border border-border px-2 py-2 text-xs"><div className="text-accent">{r.scenario.label}</div><div>{money(r.cashTrough)} trough</div><div>{r.runway.toFixed(1)} mo</div></div>)}</div></div>)}</div></Panel></div>
 <Panel title="Decision chain" kicker="Single source of truth"><div className="grid gap-2 md:grid-cols-4 lg:grid-cols-8">{["Assumption","Units","Revenue","COGS / GP","Opex / EBITDA","AR / AP","Cash / Runway","Funding / Decision"].map((x,i)=><div key={x} className="rounded-lg border border-border p-3 text-center text-xs"><span className="text-accent">0{i+1}</span><p className="mt-1 text-fg">{x}</p></div>)}</div></Panel>
 <div className="rounded-xl border border-border bg-surface p-4 text-xs leading-5 text-muted"><span className="text-fg">Control note:</span> management planning and sensitivity layer only; statutory accounting, tax and CA review remain separate controls.</div></div>;
}
