import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, ClipboardPlus, FilePlus2, ShieldCheck, PackageCheck, Factory, Ruler, AlertTriangle, Boxes } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Kpi, Panel } from "@/components/kpi";
import { getEprSnapshot, createEprTraveller, recordEprEvidence, updateEprGate } from "@/lib/epr/execution";
import { getEprExecutionChain, recordMaterialLot, recordProcessOperation, recordEprInspection, recordNcrCapa, recordInventoryMovement } from "@/lib/epr/traceability";

export const Route = createFileRoute("/command/epr-live")({ component: LiveEpr });
type Snapshot = Awaited<ReturnType<typeof getEprSnapshot>>;
type Chain = Awaited<ReturnType<typeof getEprExecutionChain>>;
const models = { core: "Longitude", pro: "Latitude", apex: "Altitude" } as const;

function LiveEpr() {
  const [data, setData] = useState<Snapshot | null>(null);
  const [chain, setChain] = useState<Chain | null>(null);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ venture: "carbon", modelId: "core", modelName: "Longitude", sku: "VINDY-LONGITUDE-PILOT", bomRevision: "BOM-001", engineeringRevision: "VEDM-301-5.3.8", serialNumber: "", supplier: "" });
  const [evidence, setEvidence] = useState({ travellerId: "", gateId: "EPR-05", evidenceType: "process-record", title: "", reference: "", notes: "" });
  const [lot, setLot] = useState({ travellerId: "", materialCode: "T700", materialDescription: "Carbon fibre / prepreg", lotNumber: "", supplier: "", certificateReference: "", quantity: 1, unit: "lot", disposition: "quarantine" });
  const [operation, setOperation] = useState({ travellerId: "", operationCode: "OP-001", operationName: "Frame layup", workstation: "", operatorName: "", status: "planned", recordReference: "", notes: "" });
  const [inspection, setInspection] = useState({ travellerId: "", inspectionType: "dimensional", characteristic: "", nominalValue: "", measuredValue: "", acceptanceCriteria: "", result: "pending", evidenceReference: "", notes: "" });
  const [ncr, setNcr] = useState({ travellerId: "", recordType: "ncr", severity: "minor", title: "", description: "", containment: "", rootCause: "", correctiveAction: "", owner: "", status: "open", closureReference: "" });
  const [movement, setMovement] = useState({ travellerId: "", sku: "", movementType: "issue", quantity: 1, unit: "unit", reference: "", notes: "" });

  async function refresh() {
    try { const [s, c] = await Promise.all([getEprSnapshot(), getEprExecutionChain()]); setData(s); setChain(c); } catch (error) { setMessage(error instanceof Error ? error.message : "Command access required."); }
  }
  useEffect(() => { void refresh(); }, []);
  const travellerVenture = (id: string) => (data?.travellers.find((t) => t.id === id)?.venture ?? "carbon") as "carbon" | "aluminium";
  async function transact(fn: () => Promise<unknown>, success: string) { setBusy(true); setMessage(""); try { await fn(); setMessage(success); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Transaction failed."); } finally { setBusy(false); } }
  async function create() { await transact(async () => { if (!form.serialNumber.trim()) throw new Error("Serial number is required."); const result = await createEprTraveller({ data: { ...form, venture: form.venture as "carbon" | "aluminium", modelId: form.modelId as "core" | "pro" | "apex", modelName: form.modelName as "Longitude" | "Latitude" | "Altitude" } }); setEvidence(v => ({...v,travellerId:result.travellerId})); setLot(v=>({...v,travellerId:result.travellerId})); setOperation(v=>({...v,travellerId:result.travellerId})); setInspection(v=>({...v,travellerId:result.travellerId})); setNcr(v=>({...v,travellerId:result.travellerId})); setMovement(v=>({...v,travellerId:result.travellerId})); setForm(v=>({...v,serialNumber:""})); }, "Traveller created and execution workspace linked."); }
  async function gate(travellerId: string, status: "in_progress" | "passed" | "blocked" | "hold" | "rework") { await transact(() => updateEprGate({ data: { travellerId, venture: travellerVenture(travellerId), gateId: evidence.gateId as any, status, reason: status === "passed" ? "Evidence reviewed by operator." : "Operator disposition." } }), `${evidence.gateId} recorded as ${status}.`); }
  async function addEvidence() { await transact(async () => { if (!evidence.travellerId || !evidence.title) throw new Error("Traveller and evidence title are required."); await recordEprEvidence({ data: { ...evidence, venture: travellerVenture(evidence.travellerId), gateId: evidence.gateId as any } }); }, "Evidence committed to the EPR ledger."); setEvidence(v=>({...v,title:"",reference:"",notes:""})); }
  const travellers = data?.travellers ?? [];
  const selectTraveller = (value: string, setter: (v: any) => void) => setter((v: any) => ({...v,travellerId:value}));
  const tSelect = (value: string, current: string, setter: (v:any)=>void) => <select value={current} onChange={e=>selectTraveller(e.target.value,setter)} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option value="">Select traveller</option>{travellers.map((t:any)=><option key={t.id} value={t.id}>{t.serial_number} · {t.model_name}</option>)}</select>;
  const execute = async (kind: string) => {
    if (kind === "lot") return transact(async()=>{if(!lot.lotNumber.trim())throw new Error("Lot number is required.");await recordMaterialLot({...lot,venture:travellerVenture(lot.travellerId),quantity:Number(lot.quantity),disposition:lot.disposition as any} as any);},"Material lot recorded.");
    if (kind === "operation") return transact(()=>recordProcessOperation({...operation,venture:travellerVenture(operation.travellerId),status:operation.status as any} as any),"Process operation recorded.");
    if (kind === "inspection") return transact(()=>recordEprInspection({...inspection,venture:travellerVenture(inspection.travellerId),inspectionType:inspection.inspectionType as any,result:inspection.result as any} as any),"Inspection record committed.");
    if (kind === "ncr") return transact(()=>recordNcrCapa({...ncr,venture:travellerVenture(ncr.travellerId),recordType:ncr.recordType as any,severity:ncr.severity as any,status:ncr.status as any} as any),"NCR/CAPA record committed.");
    return transact(()=>recordInventoryMovement({...movement,venture:travellerVenture(movement.travellerId),movementType:movement.movementType as any,quantity:Number(movement.quantity)} as any),"Inventory movement committed.");
  };
  return <div className="space-y-6">
    <header className="rounded-2xl border border-border bg-bg-elevated/70 p-5"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Vāyú Shastr · VINDY · Production control</p><h1 className="mt-1 font-display text-4xl text-accent">Live EPR Transaction Core</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-muted">Traveller → material → process → inspection → NCR/CAPA → inventory → evidence → gate → audit.</p></div><ShieldCheck className="size-12 text-accent" /></div></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Travellers" value={String(travellers.length)} hint="durable records"/><Kpi label="Lots" value={String(chain?.lots.length??0)} hint="material traceability"/><Kpi label="Operations" value={String(chain?.operations.length??0)} hint="process records"/><Kpi label="Inspections" value={String(chain?.inspections.length??0)} hint="quality records"/><Kpi label="NCR/CAPA" value={String(chain?.ncrCapa.length??0)} hint="quality containment"/></div>
    <Panel title="Create controlled pilot traveller" kicker="EPR-04 · serial genealogy root"><div className="grid gap-3 md:grid-cols-4"><select value={form.venture} onChange={e=>setForm({...form,venture:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option value="carbon">VINDY · Carbon</option><option value="aluminium">Aluminium Bicycle</option></select><select value={form.modelId} onChange={e=>{const id=e.target.value as keyof typeof models;setForm({...form,modelId:id,modelName:models[id]})}} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option value="core">Longitude</option><option value="pro">Latitude</option><option value="apex">Altitude</option></select><input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} placeholder="SKU" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={form.serialNumber} onChange={e=>setForm({...form,serialNumber:e.target.value})} placeholder="Serial number *" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={form.bomRevision} onChange={e=>setForm({...form,bomRevision:e.target.value})} placeholder="BOM revision" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={form.engineeringRevision} onChange={e=>setForm({...form,engineeringRevision:e.target.value})} placeholder="Engineering revision" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})} placeholder="Supplier / OEM" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><Button disabled={busy} onClick={create}><ClipboardPlus/> Create traveller</Button></div></Panel>
    <Panel title="Material & lot traceability" kicker="EPR-05 · material / certificate control"><div className="grid gap-3 md:grid-cols-4">{tSelect(lot.travellerId,lot.travellerId,setLot)}<input value={lot.materialCode} onChange={e=>setLot({...lot,materialCode:e.target.value})} placeholder="Material code" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={lot.materialDescription} onChange={e=>setLot({...lot,materialDescription:e.target.value})} placeholder="Material description" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={lot.lotNumber} onChange={e=>setLot({...lot,lotNumber:e.target.value})} placeholder="Lot number *" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={lot.supplier} onChange={e=>setLot({...lot,supplier:e.target.value})} placeholder="Supplier" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={lot.certificateReference} onChange={e=>setLot({...lot,certificateReference:e.target.value})} placeholder="Certificate reference" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input type="number" value={lot.quantity} onChange={e=>setLot({...lot,quantity:Number(e.target.value)})} placeholder="Quantity" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><select value={lot.disposition} onChange={e=>setLot({...lot,disposition:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option>quarantine</option><option>accepted</option><option>rejected</option><option>consumed</option></select></div><Button className="mt-3" disabled={busy} onClick={()=>execute("lot")}><PackageCheck/> Record lot</Button></Panel>
    <Panel title="Process execution" kicker="EPR-06 · traveller-linked operation record"><div className="grid gap-3 md:grid-cols-4">{tSelect(operation.travellerId,operation.travellerId,setOperation)}<input value={operation.operationCode} onChange={e=>setOperation({...operation,operationCode:e.target.value})} placeholder="Operation code" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={operation.operationName} onChange={e=>setOperation({...operation,operationName:e.target.value})} placeholder="Operation name" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={operation.workstation} onChange={e=>setOperation({...operation,workstation:e.target.value})} placeholder="Workstation" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={operation.operatorName} onChange={e=>setOperation({...operation,operatorName:e.target.value})} placeholder="Operator" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><select value={operation.status} onChange={e=>setOperation({...operation,status:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option>planned</option><option>in_progress</option><option>completed</option><option>hold</option><option>rework</option><option>rejected</option></select><input value={operation.recordReference} onChange={e=>setOperation({...operation,recordReference:e.target.value})} placeholder="Record reference" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><Button disabled={busy} onClick={()=>execute("operation")}><Factory/> Record operation</Button></div></Panel>
    <Panel title="Inspection & test record" kicker="EPR-07 → EPR-10 · objective result"><div className="grid gap-3 md:grid-cols-4">{tSelect(inspection.travellerId,inspection.travellerId,setInspection)}<select value={inspection.inspectionType} onChange={e=>setInspection({...inspection,inspectionType:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm">{["dimensional","interface","ndt","cosmetic","structural","iso4210"].map(x=><option key={x}>{x}</option>)}</select><input value={inspection.characteristic} onChange={e=>setInspection({...inspection,characteristic:e.target.value})} placeholder="Characteristic *" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={inspection.nominalValue} onChange={e=>setInspection({...inspection,nominalValue:e.target.value})} placeholder="Nominal" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={inspection.measuredValue} onChange={e=>setInspection({...inspection,measuredValue:e.target.value})} placeholder="Measured" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={inspection.acceptanceCriteria} onChange={e=>setInspection({...inspection,acceptanceCriteria:e.target.value})} placeholder="Acceptance criteria" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><select value={inspection.result} onChange={e=>setInspection({...inspection,result:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option>pending</option><option>pass</option><option>fail</option><option>conditional</option></select><input value={inspection.evidenceReference} onChange={e=>setInspection({...inspection,evidenceReference:e.target.value})} placeholder="Evidence reference" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/></div><Button className="mt-3" disabled={busy} onClick={()=>execute("inspection")}><Ruler/> Commit inspection</Button></Panel>
    <div className="grid gap-6 lg:grid-cols-2"><Panel title="NCR / CAPA" kicker="EPR-11 · deviation control"><div className="space-y-3">{tSelect(ncr.travellerId,ncr.travellerId,setNcr)}<div className="grid grid-cols-2 gap-3"><select value={ncr.recordType} onChange={e=>setNcr({...ncr,recordType:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option>ncr</option><option>capa</option></select><select value={ncr.severity} onChange={e=>setNcr({...ncr,severity:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option>minor</option><option>major</option><option>critical</option></select></div><input value={ncr.title} onChange={e=>setNcr({...ncr,title:e.target.value})} placeholder="Title *" className="w-full rounded-md border border-border bg-bg px-3 py-2 text-sm"/><textarea value={ncr.description} onChange={e=>setNcr({...ncr,description:e.target.value})} placeholder="Description *" className="min-h-20 w-full rounded-md border border-border bg-bg px-3 py-2 text-sm"/><textarea value={ncr.containment} onChange={e=>setNcr({...ncr,containment:e.target.value})} placeholder="Containment" className="min-h-16 w-full rounded-md border border-border bg-bg px-3 py-2 text-sm"/><textarea value={ncr.correctiveAction} onChange={e=>setNcr({...ncr,correctiveAction:e.target.value})} placeholder="Corrective action" className="min-h-16 w-full rounded-md border border-border bg-bg px-3 py-2 text-sm"/><Button disabled={busy} onClick={()=>execute("ncr")}><AlertTriangle/> Commit NCR/CAPA</Button></div></Panel>
    <Panel title="Inventory movement" kicker="EPR-05 / EPR-12 · serial-linked consumption"><div className="space-y-3">{tSelect(movement.travellerId,movement.travellerId,setMovement)}<input value={movement.sku} onChange={e=>setMovement({...movement,sku:e.target.value})} placeholder="SKU *" className="w-full rounded-md border border-border bg-bg px-3 py-2 text-sm"/><div className="grid grid-cols-2 gap-3"><select value={movement.movementType} onChange={e=>setMovement({...movement,movementType:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option>reserve</option><option>issue</option><option>return</option><option>consume</option><option>adjust</option></select><input type="number" min="0.01" value={movement.quantity} onChange={e=>setMovement({...movement,quantity:Number(e.target.value)})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/></div><input value={movement.reference} onChange={e=>setMovement({...movement,reference:e.target.value})} placeholder="Reference" className="w-full rounded-md border border-border bg-bg px-3 py-2 text-sm"/><Button disabled={busy} onClick={()=>execute("movement")}><Boxes/> Commit movement</Button></div></Panel></div>
    <Panel title="Evidence, gate & audit" kicker="EPR-12 · release control"><div className="grid gap-3 md:grid-cols-4"><select value={evidence.travellerId} onChange={e=>setEvidence({...evidence,travellerId:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm"><option value="">Select traveller</option>{travellers.map((t:any)=><option key={t.id} value={t.id}>{t.serial_number} · {t.model_name}</option>)}</select><select value={evidence.gateId} onChange={e=>setEvidence({...evidence,gateId:e.target.value})} className="rounded-md border border-border bg-bg px-3 py-2 text-sm">{["EPR-05","EPR-06","EPR-07","EPR-08","EPR-09","EPR-10","EPR-11","EPR-12"].map(g=><option key={g}>{g}</option>)}</select><input value={evidence.evidenceType} onChange={e=>setEvidence({...evidence,evidenceType:e.target.value})} placeholder="Evidence type" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={evidence.title} onChange={e=>setEvidence({...evidence,title:e.target.value})} placeholder="Evidence title *" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/></div><div className="mt-3 flex flex-wrap gap-2"><Button disabled={busy} onClick={addEvidence}><FilePlus2/> Commit evidence</Button><Button disabled={busy||!evidence.travellerId} variant="outline" onClick={()=>gate(evidence.travellerId,"in_progress")}><ArrowRight/> Start selected gate</Button><Button disabled={busy||!evidence.travellerId} onClick={()=>gate(evidence.travellerId,"passed")}><CheckCircle2/> Pass selected gate</Button></div></Panel>
    {message&&<div className="rounded-xl border border-accent/40 bg-accent/5 p-4 text-sm text-fg">{message}</div>}
  </div>;
}
