import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { inr } from "@/lib/format";
import { useVeloxis } from "@/lib/store";
import { PHASE3_PRODUCTION, PHASE3_PURCHASES, PHASE3_SALES, activeProduction, activeSales, openPurchases, type ProductionOrder, type ProductionStatus, type PurchaseOrder, type PurchaseStatus, type SalesOrder, type SalesStatus, type VentureId, SALES_STATUSES, PURCHASE_STATUSES, PRODUCTION_STATUSES } from "@/lib/operations/phase3";

export const Route = createFileRoute("/command/erp-execution")({ component: ErpExecution });
const KEY="veloxis-phase3-erp-v1";
const ventureLabels:Record<VentureId,string>={carbon:"Vyndi · Carbon Venture",aluminium:"Aluminium Bicycle Venture"};
function ErpExecution(){
 const finance=useVeloxis(s=>s.finance);
 const [sales,setSales]=useState<SalesOrder[]>(PHASE3_SALES),[purchases,setPurchases]=useState<PurchaseOrder[]>(PHASE3_PURCHASES),[production,setProduction]=useState<ProductionOrder[]>(PHASE3_PRODUCTION);
 const [venture,setVenture]=useState<VentureId>("carbon");
 const [draft,setDraft]=useState({customer:"",product:"",units:1,valueInr:0,month:1,supplier:"",sku:"",item:"",qty:1,unitCostInr:0,expectedMonth:1});
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);setSales(x.sales??[]);setPurchases(x.purchases??[]);setProduction(x.production??[])}}catch{}},[]);
 function persist(nextSales:SalesOrder[],nextPurchases:PurchaseOrder[],nextProduction:ProductionOrder[]){setSales(nextSales);setPurchases(nextPurchases);setProduction(nextProduction);try{localStorage.setItem(KEY,JSON.stringify({sales:nextSales,purchases:nextPurchases,production:nextProduction}))}catch{}}
 function addSales(){if(!draft.customer.trim()||!draft.product.trim()||draft.units<1||draft.valueInr<=0)return;const id=`SO-${Date.now()}`;persist([...sales,{id,venture,customer:draft.customer.trim(),product:draft.product.trim(),units:draft.units,valueInr:draft.valueInr,status:"confirmed",month:draft.month,createdAt:new Date().toISOString()}],purchases,production)}
 function addPurchase(){if(!draft.supplier.trim()||!draft.sku.trim()||!draft.item.trim()||draft.qty<1||draft.unitCostInr<=0)return;persist(sales,[...purchases,{id:`PO-${Date.now()}`,venture,supplier:draft.supplier.trim(),sku:draft.sku.trim(),item:draft.item.trim(),qty:draft.qty,unitCostInr:draft.unitCostInr,status:"ordered",expectedMonth:draft.expectedMonth}],production)}
 function startProduction(order:SalesOrder){if(production.some(p=>p.salesOrderId===order.id))return;persist(sales.map(x=>x.id===order.id?{...x,status:"in-production"}:x),purchases,[...production,{id:`MO-${Date.now()}`,venture:order.venture,salesOrderId:order.id,product:order.product,units:order.units,status:"planned",qcPassed:false}])}
 function setSalesStatus(id:string,status:SalesStatus){persist(sales.map(x=>x.id===id?{...x,status}:x),purchases,production)}
 function setPurchaseStatus(id:string,status:PurchaseStatus){persist(sales,purchases.map(x=>x.id===id?{...x,status}:x),production)}
 function setProductionStatus(id:string,status:ProductionStatus){persist(sales, purchases, production.map(x=>x.id===id?{...x,status,qcPassed:status==="finished"||status==="released"?true:x.qcPassed}:x))}
 const scopedSales=useMemo(()=>activeSales(sales).filter(x=>x.venture===venture),[sales,venture]);const scopedPurchases=useMemo(()=>openPurchases(purchases).filter(x=>x.venture===venture),[purchases,venture]);const scopedProduction=useMemo(()=>activeProduction(production).filter(x=>x.venture===venture),[production,venture]);const value=scopedSales.reduce((n,x)=>n+x.valueInr,0);const units=scopedSales.reduce((n,x)=>n+x.units,0);const committedPurchases=scopedPurchases.reduce((n,x)=>n+x.qty*x.unitCostInr,0);
 return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Phase 3 · operational ERP</p><h1 className="mt-1 font-display text-4xl">ERP Execution Control</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">The transaction layer connecting customer demand, procurement, production and release. Operational records stay venture-owned and feed the Phase 2 control architecture.</p></div><Link to="/command/control-tower" className="rounded-lg border border-accent px-4 py-2.5 text-sm font-semibold text-accent">Control Tower →</Link></header>
 <Panel title="Venture operating boundary" kicker="Never mix Carbon and Aluminium transactions"><div className="flex flex-wrap gap-2">{(["carbon","aluminium"] as VentureId[]).map(v=><button key={v} type="button" onClick={()=>setVenture(v)} className={`rounded-lg border px-4 py-2 text-sm font-semibold ${venture===v?"border-accent bg-accent/10 text-accent":"border-border text-muted"}`}>{ventureLabels[v]}</button>)}</div></Panel>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Open sales units" value={String(units)} hint={ventureLabels[venture]}/><Kpi label="Order value" value={inr(value)} hint="Confirmed / active orders"/><Kpi label="Open POs" value={String(scopedPurchases.length)} hint="Not received / cancelled"/><Kpi label="PO commitment" value={inr(committedPurchases)} hint="Qty × unit cost"/><Kpi label="Production WIP" value={String(scopedProduction.reduce((n,x)=>n+x.units,0))} hint="Open manufacturing orders"/></div>
 <Panel title="Order → production → delivery" kicker="Commercial execution"><div className="grid gap-3 rounded-xl border border-border bg-surface p-4 md:grid-cols-7"><label className="text-xs text-muted">Customer<input value={draft.customer} onChange={e=>setDraft({...draft,customer:e.target.value})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm" placeholder="Customer / dealer"/></label><label className="text-xs text-muted">Product<select value={draft.product} onChange={e=>setDraft({...draft,product:e.target.value})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"><option value="">Select product</option>{finance.productLines.filter(p=>p.venture===venture).map(p=><option key={p.id} value={p.label}>{p.label}</option>)}</select></label><label className="text-xs text-muted">Units<input type="number" min="1" value={draft.units} onChange={e=>setDraft({...draft,units:Number(e.target.value)})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"/></label><label className="text-xs text-muted">Order value<input type="number" min="1" value={draft.valueInr} onChange={e=>setDraft({...draft,valueInr:Number(e.target.value)})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"/></label><label className="text-xs text-muted">Month<input type="number" min="1" max="36" value={draft.month} onChange={e=>setDraft({...draft,month:Number(e.target.value)})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"/></label><button type="button" onClick={addSales} className="self-end rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg">Create SO</button></div>
 {scopedSales.length===0?<p className="mt-4 text-sm text-muted">No active sales orders for this venture.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr><th className="px-3 py-3 text-left">SO</th><th className="px-3 py-3 text-left">Customer</th><th className="px-3 py-3 text-left">Product</th><th className="px-3 py-3 text-right">Units</th><th className="px-3 py-3 text-right">Value</th><th>Status</th><th>Action</th></tr></thead><tbody>{scopedSales.map(o=><tr key={o.id} className="border-t border-border"><td className="px-3 py-3 text-xs text-muted">{o.id}</td><td className="px-3 py-3">{o.customer}</td><td className="px-3 py-3">{o.product}</td><td className="px-3 py-3 text-right">{o.units}</td><td className="px-3 py-3 text-right">{inr(o.valueInr)}</td><td className="px-3 py-3"><select value={o.status} onChange={e=>setSalesStatus(o.id,e.target.value as SalesStatus)} className="rounded border border-border bg-bg px-2 py-1 text-xs">{SALES_STATUSES.map(s=><option key={s}>{s}</option>)}</select></td><td className="px-3 py-3">{o.status==="confirmed"?<button type="button" onClick={()=>startProduction(o)} className="text-xs font-semibold text-accent">Release to production →</button>:"—"}</td></tr>)}</tbody></table></div>}</Panel>
 <div className="grid gap-4 lg:grid-cols-2"><Panel title="Procure → receive → inventory" kicker="Purchase order control"><div className="grid gap-3 rounded-xl border border-border bg-surface p-4 md:grid-cols-3"><label className="text-xs text-muted">Supplier<input value={draft.supplier} onChange={e=>setDraft({...draft,supplier:e.target.value})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"/></label><label className="text-xs text-muted">SKU<input value={draft.sku} onChange={e=>setDraft({...draft,sku:e.target.value})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"/></label><label className="text-xs text-muted">Item<input value={draft.item} onChange={e=>setDraft({...draft,item:e.target.value})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"/></label><label className="text-xs text-muted">Qty<input type="number" min="1" value={draft.qty} onChange={e=>setDraft({...draft,qty:Number(e.target.value)})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"/></label><label className="text-xs text-muted">Unit cost<input type="number" min="1" value={draft.unitCostInr} onChange={e=>setDraft({...draft,unitCostInr:Number(e.target.value)})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"/></label><label className="text-xs text-muted">Expected month<input type="number" min="1" max="36" value={draft.expectedMonth} onChange={e=>setDraft({...draft,expectedMonth:Number(e.target.value)})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm"/></label><button type="button" onClick={addPurchase} className="rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg">Create PO</button></div>{scopedPurchases.length===0?<p className="mt-4 text-sm text-muted">No open purchase orders for this venture.</p>:<div className="mt-4 space-y-2">{scopedPurchases.map(p=><div key={p.id} className="grid gap-2 rounded-lg border border-border p-3 md:grid-cols-[auto_1fr_auto_auto]"><span className="text-xs text-muted">{p.id}</span><span><span className="block text-sm font-semibold">{p.item}</span><span className="text-xs text-muted">{p.sku} · {p.supplier} · {p.qty} units</span></span><span className="text-sm tabular-nums">{inr(p.qty*p.unitCostInr)}</span><select value={p.status} onChange={e=>setPurchaseStatus(p.id,e.target.value as PurchaseStatus)} className="rounded border border-border bg-bg px-2 py-1 text-xs">{PURCHASE_STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>)}</div>}</Panel>
 <Panel title="Production → QC → finished bike" kicker="Manufacturing release gate">{scopedProduction.length===0?<p className="text-sm text-muted">No active manufacturing orders. Release a confirmed sales order to create one.</p>:<div className="space-y-2">{scopedProduction.map(p=><div key={p.id} className="grid gap-2 rounded-lg border border-border p-3 md:grid-cols-[auto_1fr_auto]"><span className="text-xs text-muted">{p.id}</span><span><span className="block text-sm font-semibold">{p.product} · {p.units} units</span><span className="text-xs text-muted">SO {p.salesOrderId} · QC {p.qcPassed?"passed":"pending"}</span></span><select value={p.status} onChange={e=>setProductionStatus(p.id,e.target.value as ProductionStatus)} className="rounded border border-border bg-bg px-2 py-1 text-xs">{PRODUCTION_STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>)}</div>}</Panel></div>
 <Panel title="Phase 3 transaction chain" kicker="System of record boundary"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["01","Customer","Sales Order"],["02","Supplier","Purchase Order"],["03","Production","BOM consumption"],["04","Quality","QC release"],["05","Finance","COGS · cash · margin"]].map(([n,t,d])=><div key={n} className="rounded-xl border border-border bg-bg-elevated/40 p-4"><span className="text-[10px] font-bold tracking-[0.16em] text-accent">{n}</span><p className="mt-2 text-sm font-semibold">{t}</p><p className="mt-1 text-xs leading-5 text-muted">{d}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-muted">This Phase 3 execution layer is deliberately operational: records persist in the browser for the current command session. Statutory invoices, GST, payment settlement and audited inventory valuation remain downstream accounting controls until the transactional backend is introduced.</p></Panel></div>;
}
