import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { FinanceVisual } from "@/components/finance-visual";
import { buildAccountingModel, accountingTotals } from "@/lib/finance/accounting";
import { buildModelWithInputs, minCash, totals, type ScenarioId } from "@/lib/finance/model";
import { useVeloxis } from "@/lib/store";

export const Route=createFileRoute("/command/finance-control")({component:FinanceControl});
const money=(n:number)=>`₹${n.toFixed(1)}L`;
const scenarios:{id:ScenarioId;label:string}[]=[{id:"base",label:"Base"},{id:"delayed",label:"Delayed"},{id:"stress",label:"Stress"}];
function FinanceControl(){
 const scenario=useVeloxis(s=>s.scenario); const drawStandby=useVeloxis(s=>s.drawStandby); const finance=useVeloxis(s=>s.finance); const accounting=useVeloxis(s=>s.accounting); const setScenario=useVeloxis(s=>s.setScenario);
 const rows=useMemo(()=>buildModelWithInputs(scenario,drawStandby,finance),[scenario,drawStandby,finance]); const books=useMemo(()=>buildAccountingModel(rows,accounting),[rows,accounting]); const t=totals(rows); const at=accountingTotals(books); const low=minCash(rows); const last=books.at(-1); const floor=15; const fundingGap=Math.max(0,floor-low.cash); const maxCash=Math.max(...rows.map(r=>r.closing),0);
 const budget=useMemo(()=>buildAccountingModel(buildModelWithInputs("base",drawStandby,finance),accounting),[drawStandby,finance,accounting]);
 const scenarioRows=useMemo(()=>scenarios.map(s=>{const r=buildModelWithInputs(s.id,drawStandby,finance); const b=buildAccountingModel(r,accounting); const low=minCash(r); return {id:s.id,label:s.label,revenue:b.reduce((x,v)=>x+v.revenue,0),net:b.reduce((x,v)=>x+v.netProfit,0),cash: b.at(-1)?.closingCash??0,trough:low.cash,gap:Math.max(0,floor-low.cash)};}),[drawStandby,finance,accounting]);
 const checkpoints=[6,12,18,24,30,36].map(m=>({m,budget:budget[m-1],forecast:books[m-1]})).filter(x=>x.forecast);
 return <div className="space-y-6">
  <div><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Stage 5 · Integrated finance control</p><h1 className="font-display text-4xl">Finance Control</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Budget, forecast, working capital, funding and the 36-month cash waterfall now read from the same accounting engine.</p><div className="mt-3 flex flex-wrap gap-2"><Link to="/command/financial-cockpit" className="rounded-md border border-accent/50 px-3 py-2 text-xs text-accent">Financial Cockpit</Link><Link to="/command/finance-assumptions" className="rounded-md border border-border px-3 py-2 text-xs text-muted hover:text-fg">Edit assumptions</Link><Link to="/command/balance-sheet" className="rounded-md border border-border px-3 py-2 text-xs text-muted hover:text-fg">Financial statements</Link></div></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="Revenue" value={money(at.revenue)} hint="36M forecast"/><Kpi label="Net profit" value={money(at.netProfit)} hint="Accounting view"/><Kpi label="Cash trough" value={money(low.cash)} hint={`M${low.m}`} tone={low.cash<0?"danger":low.cash<floor?"warn":"ok"}/><Kpi label="Funding gap" value={money(fundingGap)} hint={`₹${floor}L floor`} tone={fundingGap?"danger":"ok"}/><Kpi label="M36 cash" value={money(last?.closingCash??0)} hint="Forecast closing"/></div>
  <Panel title="Budget vs Forecast vs Actual" kicker="Actuals are intentionally blank until real books are entered"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr><th className="px-3 py-3">Checkpoint</th><th className="px-3 py-3 text-right">Budget revenue</th><th className="px-3 py-3 text-right">Forecast revenue</th><th className="px-3 py-3 text-right">Variance</th><th className="px-3 py-3 text-right">Actual</th></tr></thead><tbody>{checkpoints.map(({m,budget:b,forecast:f})=><tr key={m} className="border-t border-border"><td className="px-3 py-3 font-medium">M{m}</td><td className="px-3 py-3 text-right tabular-nums">{money(b?.revenue??0)}</td><td className="px-3 py-3 text-right tabular-nums">{money(f?.revenue??0)}</td><td className={`px-3 py-3 text-right tabular-nums ${(f?.revenue??0)-(b?.revenue??0)<0?"text-danger":"text-ok"}`}>{money((f?.revenue??0)-(b?.revenue??0))}</td><td className="px-3 py-3 text-right text-subtle">—</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-muted">Budget = Base case. Forecast = currently selected scenario. Actuals are not fabricated; an actual-entry ledger will be added once source accounting data is available.</p></Panel>
  <Panel title="36-month cash waterfall" kicker="Closing cash · minimum operating floor"><div className="grid gap-2 md:grid-cols-6">{checkpoints.map(({m,forecast:r})=><div key={m} className="rounded-lg border border-border bg-surface p-3"><p className="text-[10px] uppercase tracking-wider text-subtle">M{m}</p><p className="mt-2 text-lg tabular-nums">{money(r?.closingCash??0)}</p><p className="mt-1 text-[10px] text-muted">Operating {money(r?.operatingCashFlow??0)}</p><p className="text-[10px] text-muted">Funding {money(r?.financingCashFlow??0)}</p></div>)}</div><div className="mt-4 h-3 overflow-hidden rounded-full bg-bg"><div className="h-full bg-accent" style={{width:`${Math.min(100,Math.max(4,last?.closingCash??0)/Math.max(maxCash,1)*100)}%`}}/></div><div className="mt-2 flex justify-between text-[10px] text-subtle"><span>Operating floor ₹{floor}L</span><span>Peak modeled cash {money(maxCash)}</span></div></Panel>
  <div className="grid gap-4 lg:grid-cols-2"><Panel title="Working capital" kicker="Cash tied up in the operating cycle"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><div><p className="text-xs text-subtle">M36 AR</p><p className="mt-1 text-xl">{money(last?.receivables??0)}</p></div><div><p className="text-xs text-subtle">M36 Inventory</p><p className="mt-1 text-xl">{money(last?.inventory??0)}</p></div><div><p className="text-xs text-subtle">M36 AP</p><p className="mt-1 text-xl">{money(last?.payables??0)}</p></div><div><p className="text-xs text-subtle">Purchases</p><p className="mt-1 text-xl">{money(at.purchases)}</p></div></div><p className="mt-4 text-xs leading-5 text-muted">Collection lag {accounting.collectionMonths}M · supplier credit {accounting.supplierCreditMonths}M · GST settlement {accounting.gstSettlementMonths}M.</p></Panel><Panel title="Funding & runway" kicker="Capital required to protect liquidity"><div className="space-y-3"><div className="flex justify-between text-sm"><span className="text-muted">Minimum cash</span><span className="tabular-nums">{money(low.cash)} · M{low.m}</span></div><div className="flex justify-between text-sm"><span className="text-muted">Management floor</span><span>{money(floor)}</span></div><div className="flex justify-between text-sm"><span className="text-muted">Additional gap</span><span className={fundingGap?"text-danger":"text-ok"}>{money(fundingGap)}</span></div><div className="flex justify-between text-sm"><span className="text-muted">Planned funding</span><span>{money(t.funding)}</span></div></div></Panel></div>
  <Panel title="Scenario decision matrix" kicker="Same assumptions · different risk cases"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr><th className="px-3 py-3">Scenario</th><th className="px-3 py-3 text-right">Revenue</th><th className="px-3 py-3 text-right">Net profit</th><th className="px-3 py-3 text-right">Cash trough</th><th className="px-3 py-3 text-right">Funding gap</th><th className="px-3 py-3">Decision</th></tr></thead><tbody>{scenarioRows.map(s=><tr key={s.id} className={`border-t border-border ${scenario===s.id?"bg-accent/5":""}`}><td className="px-3 py-3 font-medium">{s.label}</td><td className="px-3 py-3 text-right">{money(s.revenue)}</td><td className="px-3 py-3 text-right">{money(s.net)}</td><td className="px-3 py-3 text-right">{money(s.trough)}</td><td className="px-3 py-3 text-right">{money(s.gap)}</td><td className="px-3 py-3"><button type="button" onClick={()=>setScenario(s.id)} className="text-accent hover:text-fg">Set active →</button></td></tr>)}</tbody></table></div></Panel>
  <FinanceVisual rows={rows} title="Integrated portfolio trajectory"/>
  <Panel title="Control rule" kicker="Keep the model disciplined"><p className="text-sm leading-6 text-muted">Change assumptions once, then read the consequences here. Do not type over calculated outputs. Actuals remain separate from Budget and Forecast so real accounting data can later be reconciled without corrupting the planning model.</p></Panel>
 </div>;
}
