import { useMemo } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Kpi, Panel } from "@/components/kpi";
import { FinanceVisual } from "@/components/finance-visual";
import { buildModelWithInputs, minCash, totals } from "@/lib/finance/model";
import { useVeloxis } from "@/lib/store";

export const Route = createFileRoute("/command/finance-control")({ component: FinanceControl });
const money=(n:number)=>`₹${n.toFixed(1)}L`;
const pct=(n:number)=>`${n.toFixed(1)}%`;

function FinanceControl(){
  const scenario=useVeloxis(s=>s.scenario); const drawStandby=useVeloxis(s=>s.drawStandby); const finance=useVeloxis(s=>s.finance);
  const rows=useMemo(()=>buildModelWithInputs(scenario,drawStandby,finance),[scenario,drawStandby,finance]); const t=totals(rows); const low=minCash(rows); const gp=rows.reduce((s,r)=>s+r.gp,0); const margin=t.revenue?gp/t.revenue*100:0;
  const annual=[1,2,3].map(year=>{const slice=rows.slice((year-1)*12,year*12);return {year,units:slice.reduce((s,r)=>s+r.units,0),aluminium:slice.reduce((s,r)=>s+r.aluminiumUnits,0),carbon:slice.reduce((s,r)=>s+r.carbonUnits,0),premium:slice.reduce((s,r)=>s+r.premiumCarbonUnits,0),revenue:slice.reduce((s,r)=>s+r.revenue,0),ebitda:slice.reduce((s,r)=>s+r.ebitda,0),closing:slice.at(-1)?.closing??0};});
  const maxRevenue=Math.max(...annual.map(a=>a.revenue),1);
  return <div className="space-y-6"><div><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Stage 4 · Financial planning control</p><h1 className="font-display text-4xl">Finance Control</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">This is the working 36-month model. It reads the same live state used by the Financial Cockpit, Master Finance and Aluminium Vertical.</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><Link to="/command/financial-cockpit" className="rounded-md border border-accent/50 px-3 py-2 text-accent hover:bg-surface">Financial Cockpit</Link><Link to="/command/finance-assumptions" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">Edit assumptions</Link><Link to="/command/scenarios" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">Compare scenarios</Link></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="36M units" value={String(t.units)} hint={`Al ${rows.reduce((s,r)=>s+r.aluminiumUnits,0)} · C ${rows.reduce((s,r)=>s+r.carbonUnits,0)} · P ${rows.reduce((s,r)=>s+r.premiumCarbonUnits,0)}`}/><Kpi label="Revenue" value={money(t.revenue)} hint="36-month total"/><Kpi label="Gross margin" value={pct(margin)} hint="Weighted portfolio"/><Kpi label="Cash trough" value={money(low.cash)} hint={`M${low.m}`} tone={low.cash<8?"danger":low.cash<15?"warn":"ok"}/><Kpi label="Funding" value={money(t.funding)} hint="36-month ladder"/></div>
    <FinanceVisual rows={rows} title="Live portfolio trajectory"/>
    <Panel title="Annual scale" kicker="Units → revenue → EBITDA → cash"><div className="grid gap-3 lg:grid-cols-3">{annual.map(a=><div key={a.year} className="rounded-xl border border-border bg-surface p-4"><div className="flex justify-between"><p className="text-sm font-semibold">Year {a.year}</p><p className="text-xs text-subtle">{a.units} bikes</p></div><p className="mt-2 text-xs text-muted">Aluminium {a.aluminium} · Carbon {a.carbon} · Premium {a.premium}</p><div className="mt-4 space-y-3"><div className="flex justify-between text-xs"><span className="text-subtle">Revenue</span><span>{money(a.revenue)}</span></div><div className="h-2 rounded-full bg-border"><div className="h-2 rounded-full bg-accent" style={{width:`${Math.max(3,a.revenue/maxRevenue*100)}%`}}/></div><div className="grid grid-cols-2 gap-3 text-xs"><div><span className="text-subtle">EBITDA</span><p className="mt-1 text-fg">{money(a.ebitda)}</p></div><div><span className="text-subtle">Closing cash</span><p className="mt-1 text-fg">{money(a.closing)}</p></div></div></div></div>)}</div></Panel>
    <Panel title="Decision logic" kicker="What this page is for"><div className="grid gap-3 md:grid-cols-4">{[["Revenue","ASP × units"],["Gross profit","Revenue − COGS"],["Cash","Opening + funding + operating flows − capex / inventory"],["Funding need","Capital required to keep cash above the operating floor"]].map(([a,b])=><div key={a} className="rounded-lg border border-border bg-surface p-4"><p className="text-sm font-semibold text-fg">{a}</p><p className="mt-2 text-xs leading-5 text-muted">{b}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-muted">Use <span className="text-fg">Plan & Assumptions</span> to change inputs. Do not manually edit outputs here; keeping the dependency chain intact is what makes the model useful.</p></Panel>
  </div>;
}
