import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { inr } from "@/lib/format";
import { generateAlerts, proposeActions, PHASE4_DEMAND, PHASE4_INVENTORY, type ActionType, type ManagementAction, type VentureId } from "@/lib/operations/phase4";

export const Route = createFileRoute("/command/intelligence")({ component: Intelligence });
const labels: Record<VentureId,string> = { carbon: "Vyndi · Carbon Venture", aluminium: "Aluminium Bicycle Venture" };
const severityRank = { critical: 0, warning: 1, watch: 2 } as const;
function Intelligence(){
 const [venture,setVenture]=useState<VentureId>("carbon");
 const [actions,setActions]=useState<ManagementAction[]>([]);
 const alerts=useMemo(()=>generateAlerts(PHASE4_INVENTORY,PHASE4_DEMAND,venture).sort((a,b)=>severityRank[a.severity]-severityRank[b.severity]),[venture]);
 const approved=actions.filter(x=>x.status==="approved").reduce((n,x)=>n+x.impactInr,0);
 function propose(){setActions(prev=>[...prev.filter(a=>a.venture!==venture),...proposeActions(alerts)]);}
 function decide(id:string,status:ManagementAction["status"]){setActions(prev=>prev.map(a=>a.id===id?{...a,status}:a));}
 const visibleActions=actions.filter(a=>a.venture===venture);
 return <div className="space-y-6"><header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Phase 4 · scale, automation & intelligence</p><h1 className="mt-1 font-display text-4xl">Management Intelligence</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Turn operational signals into controlled management actions: detect shortages, quantify the consequence, propose the next move, and keep approval with management.</p></header>
 <Panel title="Venture intelligence boundary" kicker="Signals and actions remain venture-owned"><div className="flex flex-wrap gap-2">{(["carbon","aluminium"] as VentureId[]).map(v=><button key={v} type="button" onClick={()=>setVenture(v)} className={`rounded-lg border px-4 py-2 text-sm font-semibold ${venture===v?"border-accent bg-accent/10 text-accent":"border-border text-muted"}`}>{labels[v]}</button>)}</div></Panel>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Signals" value={String(alerts.length)} hint="Detected conditions"/><Kpi label="Critical" value={String(alerts.filter(a=>a.severity==="critical").length)} hint="Immediate attention"/><Kpi label="Proposed actions" value={String(visibleActions.filter(a=>a.status==="proposed").length)} hint="Awaiting approval"/><Kpi label="Approved impact" value={inr(approved)} hint="Action impact envelope"/></div>
 <Panel title="Signal engine" kicker="Detection → consequence → recommendation"><div className="space-y-3">{alerts.length===0?<p className="text-sm text-muted">No exception signals for this venture.</p>:alerts.map(a=><div key={a.id} className="rounded-xl border border-border p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><span className="text-[10px] uppercase tracking-[0.16em] text-accent">{a.severity}</span><h2 className="mt-1 text-sm font-semibold">{a.title}</h2><p className="mt-1 text-sm leading-6 text-muted">{a.detail}</p></div><span className="text-sm tabular-nums">Impact {inr(a.impactInr)}</span></div><p className="mt-3 text-xs font-semibold uppercase tracking-wider text-subtle">Recommended control: {a.action}</p></div>)}</div><button type="button" onClick={propose} disabled={!alerts.length} className="mt-4 rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg disabled:opacity-50">Generate management actions</button></Panel>
 <Panel title="Management action queue" kicker="Human approval remains the control point">{visibleActions.length===0?<p className="text-sm text-muted">No proposed actions yet. Generate actions from the signal engine.</p>:<div className="space-y-2">{visibleActions.map(a=><div key={a.id} className="grid gap-3 rounded-lg border border-border p-3 md:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-semibold">{a.label}</p><p className="mt-1 text-xs text-muted">{a.action as ActionType} · impact {inr(a.impactInr)}</p></div><span className="self-center text-xs uppercase tracking-wider text-subtle">{a.status}</span><div className="flex gap-2"><button type="button" onClick={()=>decide(a.id,"approved")} className="rounded border border-accent px-3 py-1.5 text-xs font-semibold text-accent">Approve</button><button type="button" onClick={()=>decide(a.id,"rejected")} className="rounded border border-border px-3 py-1.5 text-xs text-muted">Reject</button></div></div>)}</div>}</Panel>
 <Panel title="Phase 4 control loop" kicker="Management OS pattern"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["01","Observe","Inventory + demand signals"],["02","Detect","Exception / threshold"],["03","Quantify","Cash + margin consequence"],["04","Propose","Controlled action"],["05","Approve","Management decision"]].map(([n,t,d])=><div key={n} className="rounded-xl border border-border bg-bg-elevated/40 p-4"><span className="text-[10px] font-bold tracking-[0.16em] text-accent">{n}</span><p className="mt-2 text-sm font-semibold">{t}</p><p className="mt-1 text-xs leading-5 text-muted">{d}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-muted">Phase 4 recommendations are decision support, not autonomous purchasing or accounting entries. Approval is explicit; transactional execution remains downstream of the Phase 3 operational system of record.</p></Panel></div>;
}
