import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { inr } from "@/lib/format";
import { generateAlerts, proposeActions, PHASE4_DEMAND, PHASE4_INVENTORY, type ActionType, type ManagementAction, type VentureId } from "@/lib/operations/phase4";
import { approvedDecisionImpact, getForecast, governanceScore, PHASE5_DECISIONS, PHASE5_GOVERNANCE, type Decision, type ManagementRole } from "@/lib/operations/phase5";

export const Route = createFileRoute("/command/intelligence")({ component: Intelligence });
const labels: Record<VentureId,string> = { carbon: "Vyndi · Carbon Venture", aluminium: "Aluminium Bicycle Venture" };
const severityRank = { critical: 0, warning: 1, watch: 2 } as const;
const roles: ManagementRole[] = ["founder", "finance", "operations", "investor"];
const scenarios = ["base", "upside", "downside"] as const;
function Intelligence(){
 const [venture,setVenture]=useState<VentureId>("carbon");
 const [actions,setActions]=useState<ManagementAction[]>([]);
 const [managementVenture,setManagementVenture]=useState<"consolidated"|"carbon"|"aluminium">("consolidated");
 const [scenario,setScenario]=useState<(typeof scenarios)[number]>("base");
 const [role,setRole]=useState<ManagementRole>("founder");
 const [decisions,setDecisions]=useState<Decision[]>(PHASE5_DECISIONS);
 const alerts=useMemo(()=>generateAlerts(PHASE4_INVENTORY,PHASE4_DEMAND,venture).sort((a,b)=>severityRank[a.severity]-severityRank[b.severity]),[venture]);
 const approved=actions.filter(x=>x.status==="approved").reduce((n,x)=>n+x.impactInr,0);
 const forecast=useMemo(()=>getForecast(managementVenture,scenario),[managementVenture,scenario]);
 const canDecide=role!=="investor";
 function propose(){setActions(prev=>[...prev.filter(a=>a.venture!==venture),...proposeActions(alerts)]);}
 function decide(id:string,status:ManagementAction["status"]){setActions(prev=>prev.map(a=>a.id===id?{...a,status}:a));}
 function decideBoard(id:string,status:Decision["status"]){setDecisions(prev=>prev.map(a=>a.id===id?{...a,status}:a));}
 const visibleActions=actions.filter(a=>a.venture===venture);
 return <div className="space-y-6"><header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Phase 5 · management OS & investor control</p><h1 className="mt-1 font-display text-4xl">Management Intelligence</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">One controlled management layer over ventures, operations and finance: detect exceptions, forecast the business, govern decisions and prepare investor-grade management reporting.</p></header>
 <Panel title="Venture intelligence boundary" kicker="Signals and actions remain venture-owned"><div className="flex flex-wrap gap-2">{(["carbon","aluminium"] as VentureId[]).map(v=><button key={v} type="button" onClick={()=>setVenture(v)} className={`rounded-lg border px-4 py-2 text-sm font-semibold ${venture===v?"border-accent bg-accent/10 text-accent":"border-border text-muted"}`}>{labels[v]}</button>)}</div></Panel>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Signals" value={String(alerts.length)} hint="Detected conditions"/><Kpi label="Critical" value={String(alerts.filter(a=>a.severity==="critical").length)} hint="Immediate attention"/><Kpi label="Proposed actions" value={String(visibleActions.filter(a=>a.status==="proposed").length)} hint="Awaiting approval"/><Kpi label="Approved impact" value={inr(approved)} hint="Action impact envelope"/></div>
 <Panel title="Signal engine" kicker="Detection → consequence → recommendation"><div className="space-y-3">{alerts.length===0?<p className="text-sm text-muted">No exception signals for this venture.</p>:alerts.map(a=><div key={a.id} className="rounded-xl border border-border p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><span className="text-[10px] uppercase tracking-[0.16em] text-accent">{a.severity}</span><h2 className="mt-1 text-sm font-semibold">{a.title}</h2><p className="mt-1 text-sm leading-6 text-muted">{a.detail}</p></div><span className="text-sm tabular-nums">Impact {inr(a.impactInr)}</span></div><p className="mt-3 text-xs font-semibold uppercase tracking-wider text-subtle">Recommended control: {a.action}</p></div>)}</div><button type="button" onClick={propose} disabled={!alerts.length} className="mt-4 rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg disabled:opacity-50">Generate management actions</button></Panel>
 <Panel title="Management action queue" kicker="Human approval remains the control point">{visibleActions.length===0?<p className="text-sm text-muted">No proposed actions yet. Generate actions from the signal engine.</p>:<div className="space-y-2">{visibleActions.map(a=><div key={a.id} className="grid gap-3 rounded-lg border border-border p-3 md:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-semibold">{a.label}</p><p className="mt-1 text-xs text-muted">{a.action as ActionType} · impact {inr(a.impactInr)}</p></div><span className="self-center text-xs uppercase tracking-wider text-subtle">{a.status}</span><div className="flex gap-2"><button type="button" onClick={()=>decide(a.id,"approved")} className="rounded border border-accent px-3 py-1.5 text-xs font-semibold text-accent">Approve</button><button type="button" onClick={()=>decide(a.id,"rejected")} className="rounded border border-border px-3 py-1.5 text-xs text-muted">Reject</button></div></div>)}</div>}</Panel>
 <Panel title="Phase 5 · Vayu Shastr Management OS" kicker="Scope · scenario · role · governance"><div className="grid gap-3 md:grid-cols-3"><label className="text-xs text-muted">Management scope<select value={managementVenture} onChange={e=>setManagementVenture(e.target.value as typeof managementVenture)} className="mt-1 w-full rounded-md border border-border bg-bg px-3 py-2 text-sm text-fg"><option value="consolidated">Vayu Shastr · Consolidated</option><option value="carbon">Vyndi · Carbon Venture</option><option value="aluminium">Aluminium Bicycle Venture</option></select></label><label className="text-xs text-muted">Planning scenario<select value={scenario} onChange={e=>setScenario(e.target.value as typeof scenario)} className="mt-1 w-full rounded-md border border-border bg-bg px-3 py-2 text-sm text-fg">{scenarios.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs text-muted">Operating role<select value={role} onChange={e=>setRole(e.target.value as ManagementRole)} className="mt-1 w-full rounded-md border border-border bg-bg px-3 py-2 text-sm text-fg">{roles.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Revenue outlook" value={inr(forecast.revenueInr)} hint={`${scenario} scenario`}/><Kpi label="Gross margin" value={inr(forecast.grossMarginInr)} hint="Planning envelope"/><Kpi label="Cash" value={inr(forecast.cashInr)} hint="Current envelope"/><Kpi label="Runway" value={`${forecast.runwayMonths} mo`} hint="Planning indicator"/><Kpi label="Governance" value={`${governanceScore()}%`} hint="Control readiness"/></div></Panel>
 <div className="grid gap-6 lg:grid-cols-2"><Panel title="Investor / board snapshot" kicker="Management view, not statutory reporting"><div className="space-y-2">{[["Business","Multi-venture operating platform"],["Growth engine","Vyndi · Carbon Venture"],["Capital discipline","Cash + working capital monitored"],["Reporting boundary",managementVenture === "consolidated" ? "Consolidated + venture drill-down" : managementVenture === "carbon" ? labels.carbon : labels.aluminium],["Scenario",scenario]].map(([a,b])=><div key={a} className="flex justify-between gap-4 border-b border-border py-2 text-sm"><span className="text-muted">{a}</span><span className="text-right font-medium">{b}</span></div>)}</div></Panel><Panel title="Governance & controls" kicker="Production hardening register"><div className="space-y-2">{PHASE5_GOVERNANCE.map(g=><div key={g.id} className="flex items-center justify-between gap-3 rounded-lg border border-border p-3"><div><p className="text-sm font-semibold">{g.area}</p><p className="text-xs text-muted">{g.owner} · {g.due}</p></div><span className="text-[10px] uppercase tracking-wider text-accent">{g.status}</span></div>)}</div></Panel></div>
 <Panel title="Controlled decision queue" kicker="Approval hierarchy remains explicit"><div className="space-y-2">{decisions.map(d=><div key={d.id} className="grid gap-3 rounded-lg border border-border p-3 md:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-semibold">{d.title}</p><p className="mt-1 text-xs text-muted">{d.id} · owner {d.owner} · impact {inr(d.impactInr)}</p></div><span className="self-center text-xs uppercase tracking-wider text-subtle">{d.status}</span><div className="flex gap-2"><button disabled={!canDecide || d.status!=="proposed"} onClick={()=>decideBoard(d.id,"approved")} className="rounded border border-accent px-3 py-1.5 text-xs font-semibold text-accent disabled:opacity-40">Approve</button><button disabled={!canDecide || d.status!=="proposed"} onClick={()=>decideBoard(d.id,"rejected")} className="rounded border border-border px-3 py-1.5 text-xs text-muted disabled:opacity-40">Reject</button></div></div>)}<p className="pt-2 text-xs text-muted">Approved decision impact: {inr(approvedDecisionImpact(decisions))}. Investor role is read-only. Authenticated approval, immutable audit history and server-side persistence remain backend controls.</p></div></Panel>
 <Panel title="Management OS control loop" kicker="Phase 5 architecture"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["01","Observe","ERP + finance + venture data"],["02","Forecast","Base / upside / downside"],["03","Govern","Roles + approvals + controls"],["04","Report","Board + investor management view"]].map(([n,t,d])=><div key={n} className="rounded-xl border border-border bg-bg-elevated/40 p-4"><span className="text-[10px] font-bold tracking-[0.16em] text-accent">{n}</span><p className="mt-2 text-sm font-semibold">{t}</p><p className="mt-1 text-xs leading-5 text-muted">{d}</p></div>)}</div></Panel>
 <p className="text-xs leading-5 text-muted">Phase 5 is management control and decision support. It does not create statutory accounting entries or replace the authenticated system of record.</p></div>;
}
