import { createFileRoute, Link } from "@tanstack/react-router";
import { z } from "zod";
import { Panel, Kpi } from "@/components/kpi";
import { inr } from "@/lib/format";
import { useVeloxis } from "@/lib/store";
import { DEFAULT_EQUIPMENT_LEDGER, EQUIPMENT_LEDGER_META, type EquipmentLedgerId } from "@/lib/finance/equipment-ledger";
import { getAuthoritativeInventory, getAuthoritativeInventoryMovements, getInventoryControlSummary, getInventoryFifoTrace, getInventoryMslWarnings } from "@/lib/inventory-authority";

const LEDGERS=[
 {id:"stock",label:"Stock ledger",note:"Authoritative SKU balances and value"},
 {id:"components",label:"Component control",note:"BOM → approved inventory mapping"},
 {id:"msl",label:"MSL ledger",note:"Minimum stock and replenishment signals"},
 {id:"fifo",label:"FIFO ledger",note:"Receipt layers consumed oldest-first"},
 {id:"movements",label:"Movement ledger",note:"Append-only posted stock events"},
 {id:"equipment",label:"Equipment ledgers",note:"Five finance-linked parent ledgers"},
] as const;
type LedgerId=typeof LEDGERS[number]["id"];

export const Route=createFileRoute("/command/inventory-ledgers")({
 validateSearch:z.object({ledger:z.string().optional()}),
 loader:async()=>{const [summary,balances,movements,msl,fifo]=await Promise.all([getInventoryControlSummary(),getAuthoritativeInventory(),getAuthoritativeInventoryMovements(),getInventoryMslWarnings(),getInventoryFifoTrace()]);return {summary,balances,movements,msl,fifo};},
 component:InventoryLedgers,
});

function InventoryLedgers(){
 const search=Route.useSearch();const active=(LEDGERS.some(x=>x.id===search.ledger)?search.ledger:"stock") as LedgerId;const d=Route.useLoaderData();const equipment=useVeloxis(s=>s.finance.equipmentLedger)??DEFAULT_EQUIPMENT_LEDGER;const meta=LEDGERS.find(x=>x.id===active)!;
 return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] uppercase tracking-[0.22em] text-green">Inventory · controlled ledger register</p><h1 className="mt-2 text-4xl font-bold text-accent">Inventory ledgers</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">Select one ledger at a time. No duplicate balances or parallel inventory calculations are introduced.</p></div><Link to="/command/inventory" className="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold text-muted">Back to Inventory →</Link></header>
 <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{LEDGERS.map(x=><Link key={x.id} to="/command/inventory-ledgers" search={{ledger:x.id}} className={`rounded-xl border p-4 ${active===x.id?"border-accent bg-accent/10":"border-border bg-bg-elevated/30 hover:border-accent"}`}><p className="text-sm font-semibold text-fg">{x.label}</p><p className="mt-1 text-xs leading-5 text-muted">{x.note}</p></Link>)}</div>
 <div className="grid gap-3 sm:grid-cols-3"><Kpi label="Authoritative SKUs" value={String(d.summary.skuCount)}/><Kpi label="Units" value={String(d.summary.totalUnits)}/><Kpi label="Inventory value" value={inr(d.summary.inventoryValueInr)}/></div>
 {active==="stock"&&<Stock rows={d.balances}/>} {active==="components"&&<Components/>} {active==="msl"&&<MSL rows={d.msl}/>} {active==="fifo"&&<FIFO rows={d.fifo}/>} {active==="movements"&&<Movements rows={d.movements}/>} {active==="equipment"&&<Equipment rows={equipment}/>} 
 <Panel title={meta.label} kicker="Selected ledger"><p className="text-xs leading-5 text-muted">Return to Inventory from this view; all operational ledger links remain under one controlled inventory navigation.</p></Panel></main>;
}
function Stock({rows}:{rows:any[]}){return <Panel title="Authoritative stock ledger" kicker="Quantity + weighted average cost"><Table headers={["Venture","SKU","Unit","Balance","WAC","Value"]}>{rows.map(x=><tr key={`${x.venture}-${x.sku}-${x.unit}`} className="border-t border-border/70"><td>{x.venture}</td><td className="font-mono text-xs">{x.sku}</td><td>{x.unit}</td><td className="text-right">{Number(x.quantity_balance)}</td><td className="text-right">{inr(Number(x.weighted_average_cost_inr))}</td><td className="text-right">{inr(Number(x.inventory_value_inr))}</td></tr>)}</Table></Panel>}
function Components(){return <Panel title="Component control" kicker="BOM → approved inventory mapping"><p className="text-sm leading-6 text-muted">A BOM component is not treated as stock until it is explicitly mapped to an approved inventory SKU, preserving identity control and preventing fuzzy joins.</p><div className="mt-4 flex flex-wrap gap-2"><Link to="/command/bom-inventory-mapping" className="rounded-lg border border-accent px-3 py-2 text-xs font-semibold text-accent">Open mapping control →</Link><Link to="/command/inventory-truth" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold">Inventory truth</Link></div></Panel>}
function MSL({rows}:{rows:any[]}){return <Panel title="MSL ledger" kicker="Balance vs minimum stock"><Table headers={["Status","SKU","On hand","MSL","Shortfall","Reorder","Lead time","Action"]}>{rows.map(x=><tr key={`${x.venture}-${x.sku}-${x.unit}`} className="border-t border-border/70"><td className="uppercase text-xs font-semibold">{x.status}</td><td className="font-mono text-xs">{x.sku}</td><td className="text-right">{Number(x.quantity_balance)}</td><td className="text-right">{Number(x.minimum_stock_level)}</td><td className="text-right">{Number(x.shortage_quantity)}</td><td className="text-right">{Number(x.reorder_quantity)}</td><td className="text-right">{Number(x.lead_time_days)} d</td><td><Link to="/command/procurement" className="text-accent font-semibold">Procure →</Link></td></tr>)}</Table></Panel>}
function FIFO({rows}:{rows:any[]}){return <Panel title="FIFO ledger" kicker="Oldest receipt layer first"><Table headers={["Received","SKU","Received","Remaining","Unit cost","Allocations"]}>{rows.map(x=><tr key={x.layer_id} className="border-t border-border/70"><td>{new Date(x.received_at).toLocaleDateString()}</td><td className="font-mono text-xs">{x.sku}</td><td className="text-right">{Number(x.quantity_received)}</td><td className="text-right font-semibold">{Number(x.quantity_remaining)}</td><td className="text-right">{inr(Number(x.unit_cost_inr))}</td><td className="text-right">{Number(x.allocation_count)}</td></tr>)}</Table></Panel>}
function Movements({rows}:{rows:any[]}){return <Panel title="Movement ledger" kicker="Append-only posted inventory events"><Table headers={["Date","Type","SKU","Delta","Unit","Unit cost","Reference"]}>{rows.map(x=><tr key={x.id} className="border-t border-border/70"><td>{new Date(x.created_at).toLocaleString()}</td><td className="uppercase text-xs">{x.movement_type}</td><td className="font-mono text-xs">{x.sku}</td><td className="text-right">{Number(x.quantity_delta)}</td><td>{x.unit}</td><td className="text-right">{inr(Number(x.unit_cost_inr))}</td><td className="text-xs">{x.reference||x.traveller_id||"—"}</td></tr>)}</Table></Panel>}
function Equipment({rows}:{rows:any[]}){return <Panel title="Equipment & cost ledgers" kicker="Five parent ledgers · finance-linked"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{(Object.entries(EQUIPMENT_LEDGER_META) as [EquipmentLedgerId,{label:string;treatment:string}][]).map(([id,m])=><div key={id} className="rounded-xl border border-border bg-bg-elevated/30 p-4"><p className="text-sm font-semibold text-fg">{m.label}</p><p className="mt-1 text-xs text-muted">{m.treatment}</p><p className="mt-4 text-2xl">{rows.filter(x=>x.ledger===id).length}</p><p className="text-[10px] uppercase tracking-wider text-subtle">registered items</p></div>)}</div></Panel>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr>{headers.map(h=><th key={h} className="px-3 py-3 text-left">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
