import { createFileRoute, Link } from "@tanstack/react-router";
import { Panel, Kpi } from "@/components/kpi";
import { inr } from "@/lib/format";
import { getAuthoritativeInventory, getInventoryControlSummary, getInventoryMslWarnings, getInventoryFifoTrace } from "@/lib/inventory-authority";

export const Route=createFileRoute("/command/inventory")({
 loader:async()=>{const [summary,balances,msl,fifo]=await Promise.all([getInventoryControlSummary(),getAuthoritativeInventory(),getInventoryMslWarnings(),getInventoryFifoTrace()]);return {summary,balances,msl,fifo};},
 component:Inventory,
});
const LEDGERS=[
 ["stock","Stock ledger","Authoritative SKU balance, WAC and value"],
 ["components","Component control","BOM → approved SKU mapping"],
 ["msl","MSL ledger","Minimum stock, shortage and replenishment"],
 ["fifo","FIFO ledger","Receipt layers and issue allocations"],
 ["movements","Movement ledger","Append-only inventory transactions"],
 ["equipment","Equipment ledgers","Finance-linked asset and cost registers"],
] as const;
function Inventory(){const {summary,balances,msl,fifo}=Route.useLoaderData();const critical=msl.filter((x:any)=>x.status==="critical").length;return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 space-y-6">
<header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] uppercase tracking-[0.22em] text-green">Operations · inventory control</p><h1 className="mt-2 text-4xl font-bold text-accent">Inventory</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">Lean inventory control: one authoritative stock chain, explicit ledgers, no duplicate planning balances. Planning remains planning; posted inventory remains operational truth.</p></div><div className="flex gap-2"><Link to="/command/procurement" className="rounded-lg border border-accent px-4 py-2.5 text-sm font-semibold text-accent">Procurement</Link><Link to="/command/planning" className="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold text-muted">Planning</Link></div></header>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Authoritative SKUs" value={String(summary.skuCount)}/><Kpi label="Units" value={String(summary.totalUnits)}/><Kpi label="Inventory value" value={inr(summary.inventoryValueInr)}/><Kpi label="Open FIFO layers" value={String(summary.fifoLayerCount)}/><Kpi label="MSL alerts" value={String(msl.length)} hint={`${critical} critical`} tone={critical?"danger":msl.length?"warn":"ok"}/></div>
<Panel title="Select an inventory ledger" kicker="One entry point · explicit context"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{LEDGERS.map(([id,label,note])=><Link key={id} to="/command/inventory-ledgers" search={{ledger:id}} className="rounded-xl border border-border bg-bg-elevated/30 p-4 hover:border-accent"><p className="text-sm font-semibold text-fg">{label}</p><p className="mt-1 text-xs leading-5 text-muted">{note}</p><span className="mt-4 inline-block text-[10px] font-bold uppercase tracking-[0.14em] text-accent">Open ledger →</span></Link>)}</div></Panel>
<div className="grid gap-4 lg:grid-cols-3"><Panel title="Stock truth" kicker="Authoritative"><p className="text-3xl font-bold tabular-nums">{balances.length}</p><p className="mt-1 text-xs text-muted">SKU / venture / unit balances currently posted.</p><Link to="/command/inventory-ledgers" search={{ledger:"stock"}} className="mt-4 inline-block text-xs font-semibold text-accent">Open stock ledger →</Link></Panel><Panel title="MSL control" kicker="Replenishment"><p className="text-3xl font-bold tabular-nums">{msl.length}</p><p className="mt-1 text-xs text-muted">Minimum-stock exceptions linked directly to Procurement.</p><Link to="/command/inventory-ledgers" search={{ledger:"msl"}} className="mt-4 inline-block text-xs font-semibold text-accent">Review MSL →</Link></Panel><Panel title="FIFO control" kicker="Valuation / traceability"><p className="text-3xl font-bold tabular-nums">{fifo.length}</p><p className="mt-1 text-xs text-muted">Open receipt layers. Issues consume the oldest available layer first.</p><Link to="/command/inventory-ledgers" search={{ledger:"fifo"}} className="mt-4 inline-block text-xs font-semibold text-accent">Review FIFO →</Link></Panel></div>
<Panel title="Inventory workflow" kicker="Do not duplicate the source of truth"><div className="grid gap-3 md:grid-cols-5">{[["01","Master","Approved SKU identity"],["02","Mapping","BOM → SKU control"],["03","Receipt","Post stock + FIFO layer"],["04","Issue","Consume FIFO + trace"],["05","MSL","Signal → procurement"]].map(([n,t,d])=><div key={n} className="rounded-xl border border-border bg-bg-elevated/30 p-4"><span className="text-[10px] font-bold tracking-[0.16em] text-accent">{n}</span><p className="mt-2 text-sm font-semibold">{t}</p><p className="mt-1 text-xs leading-5 text-muted">{d}</p></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><Link to="/command/inventory-control-audit" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:border-accent">Open MSL / FIFO audit →</Link><Link to="/command/inventory-truth" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:border-accent">Inventory truth →</Link></div></Panel>
</main>}
