import { createFileRoute, Link } from "@tanstack/react-router";
import { Panel, Kpi } from "@/components/kpi";
import { getInventoryControlAudit } from "@/lib/inventory-control-audit";

export const Route=createFileRoute("/command/inventory-control-audit")({loader:()=>getInventoryControlAudit(),component:InventoryControlAudit});
function InventoryControlAudit(){const d=Route.useLoaderData();const msl=d.msl as any,fifo=d.fifo as any,alloc=d.alloc as any;const fifoMismatch=Number(fifo.mismatches??0),allocMismatch=Number(alloc.allocation_mismatches??0),leadMissing=Number(msl.missing_lead_time??0);return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 space-y-6"><header className="flex items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.22em] text-green">Inventory · control audit</p><h1 className="mt-2 text-4xl font-bold text-accent">MSL & FIFO audit</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">A compact control report that tests the inventory procedures against the authoritative ledger instead of duplicating stock calculations.</p></div><Link to="/command/inventory-ledgers" search={{ledger:"msl"}} className="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold text-muted">Back to ledgers →</Link></header>
<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="MSL controls" value={String(msl.controls??0)}/><Kpi label="MSL lead-time gaps" value={String(leadMissing)} tone={leadMissing?"warn":"ok"}/><Kpi label="FIFO balance mismatches" value={String(fifoMismatch)} tone={fifoMismatch?"danger":"ok"}/><Kpi label="FIFO allocation mismatches" value={String(allocMismatch)} tone={allocMismatch?"danger":"ok"}/></div>
<Panel title="MSL procedure" kicker="Operational minimum-stock control"><div className="grid gap-3 md:grid-cols-4">{[["1","Authoritative balance","Read posted ledger balance"],["2","Minimum stock","Compare against active MSL"],["3","Shortfall","max(MSL − balance, 0)"],["4","Replenishment","Send signal to Procurement; do not create a second stock ledger"]].map(([n,t,d])=><div key={n} className="rounded-xl border border-border p-4"><span className="text-[10px] font-bold tracking-wider text-accent">{n}</span><p className="mt-2 text-sm font-semibold">{t}</p><p className="mt-1 text-xs leading-5 text-muted">{d}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-muted">Audit rule: MSL is a replenishment control, not an inventory balance. Lead time must be populated before a planning signal is treated as actionable.</p></Panel>
<Panel title="FIFO procedure" kicker="Receipt layer → issue allocation"><div className="grid gap-3 md:grid-cols-4">{[["1","Receipt","Positive ledger movement creates one FIFO layer"],["2","Issue","Negative movement allocates oldest remaining layers first"],["3","Trace","Every allocation references the issue and source layer"],["4","Reconcile","FIFO remaining must equal authoritative quantity by SKU/unit"]].map(([n,t,d])=><div key={n} className="rounded-xl border border-border p-4"><span className="text-[10px] font-bold tracking-wider text-accent">{n}</span><p className="mt-2 text-sm font-semibold">{t}</p><p className="mt-1 text-xs leading-5 text-muted">{d}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-muted">The implementation follows a FIFO layer/allocation model; IAS 2 permits FIFO or weighted-average for ordinarily interchangeable inventories, with consistency for inventories of similar nature and use. citeturn0search0turn0search20</p></Panel>
<Panel title="Audit disposition" kicker="What production / procurement should act on"><div className="grid gap-3 md:grid-cols-3"><div className={`rounded-xl border p-4 ${leadMissing?"border-border":"border-accent/40"}`}><p className="text-sm font-semibold">MSL lead time</p><p className="mt-1 text-xs text-muted">{leadMissing?`${leadMissing} active control(s) have no supplier lead time.`:"All active MSL controls have a lead time."}</p></div><div className={`rounded-xl border p-4 ${fifoMismatch?"border-border":"border-accent/40"}`}><p className="text-sm font-semibold">FIFO vs stock</p><p className="mt-1 text-xs text-muted">{fifoMismatch?`${fifoMismatch} SKU/unit group(s) do not reconcile.`:"All SKU/unit groups reconcile."}</p></div><div className={`rounded-xl border p-4 ${allocMismatch?"border-border":"border-accent/40"}`}><p className="text-sm font-semibold">Issue allocations</p><p className="mt-1 text-xs text-muted">{allocMismatch?`${allocMismatch} issue(s) have allocation differences.`:"All posted issue quantities reconcile to FIFO allocations."}</p></div></div></Panel></main>}
