import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { Kpi, Panel } from "@/components/kpi";
import { INVESTOR_BOARD_STATUS, INVESTOR_MILESTONES, INVESTOR_PROOF_POINTS, USE_OF_PROCEEDS } from "@/lib/data/investor-board";
import { buildModel, totals, GM, ASP_L, COGS_L } from "@/lib/finance/model";

export const Route = createFileRoute("/command/investor-pitch")({ component: InvestorPitch });
const fmt = (n: number) => `₹${n.toFixed(1)}L`;

const OPERATING_GATES = [
  ["M0–M6", "Engineering", "CAD/FEA, prototypes, IP and validation evidence"],
  ["M6–M12", "Pilot", "Tooling, ISO path, factory qualification and pilot production"],
  ["M12–M18", "Launch", "D2C launch, first customers and service feedback"],
  ["M18–M24", "Repeatability", "Yield, warranty, service and working-capital discipline"],
  ["M24–M36", "Scale", "Capacity expansion only after evidence-backed unit economics"],
] as const;

function InvestorPitch() {
  const rows = buildModel("base", false); const t = totals(rows); const m36 = rows[35]; const m29 = rows[28]; const m24 = rows[23];
  return <div className="space-y-7">
    <header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Investor relations · Dedicated pitch page</p><h1 className="mt-1 font-display text-4xl">VéLOXIS Investor Pitch</h1><p className="mt-2 max-w-3xl text-sm text-muted">An investor-facing narrative generated from the controlled command registers. Financial figures are management-model assumptions until CA reconciliation; engineering and market claims remain subject to their evidence gates.</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><Link to="/command/investor-board" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">Investor / Board Control</Link><Link to="/command/ca-audit" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">CA Verification</Link><Link to="/command/finance-control" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">36-Month Finance</Link><Link to="/command/market-survey" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">Founder Market Survey</Link><Link to="/command/design-philosophy" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">Design Philosophy</Link></div></header>
    <section className="rounded-xl border border-border bg-surface p-6 sm:p-8"><p className="text-xs uppercase tracking-[0.18em] text-accent">Investment thesis</p><h2 className="mt-3 max-w-4xl font-display text-3xl leading-tight">An India-focused, IP-led carbon road-bike platform built around controlled engineering, rider fit, configurable specification and disciplined staged capital.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-muted">Vāyú Shastr is building VéLOXIS as an asset-light product company: retain product definition, brand, customer relationship and relevant IP while using qualified manufacturing partners for carbon production. The customer proposition is not prestige-brand imitation; it is engineered performance, fit and configuration at a materially more accessible price point.</p></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Current tranche" value="₹15L" hint="Foundation stage" /><Kpi label="Funding ladder" value="₹2Cr" hint="Staged, not immediate" /><Kpi label="Scale breakeven" value={`M${m29.m}`} hint="Planning marker" /><Kpi label="24-mo cash" value={fmt(m24.closing)} hint="Operating visibility" /></div>
    <Panel title="Market position" kicker="Use market data as context, not as an unsupported TAM claim"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Macro market</p><p className="mt-2 text-sm leading-5">Multiple research sources indicate a substantial Indian bicycle market, but reported totals vary by scope and methodology.</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Target niche</p><p className="mt-2 text-sm leading-5">VéLOXIS targets the higher-value performance road segment, especially carbon road bikes and riders seeking better fit/specification.</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Commercial thesis</p><p className="mt-2 text-sm leading-5">Compete on engineering, fit, configuration and value—not on imported-brand heritage.</p></div></div><p className="mt-4 text-xs text-muted">The Founder Market Survey is maintained as market intelligence. Investment-grade TAM/SAM/SOM should be rebuilt from primary trade data, dealer research and validated customer demand.</p></Panel>
    <Panel title="Unit economics" kicker="Current management assumptions · not historical performance"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Blended ASP</p><p className="mt-1 text-xl">{fmt(ASP_L)}</p><p className="mt-1 text-xs text-muted">25% Core · 60% Pro · 15% Apex mix</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Blended COGS</p><p className="mt-1 text-xl">{fmt(COGS_L)}</p><p className="mt-1 text-xs text-muted">Before working-capital effects</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Gross margin</p><p className="mt-1 text-xl">{GM.toFixed(1)}%</p><p className="mt-1 text-xs text-muted">Planning assumption</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Validation required</p><p className="mt-1 text-xl">COGS</p><p className="mt-1 text-xs text-muted">Supplier quotes, yield, warranty, logistics</p></div></div><p className="mt-4 text-xs text-muted">The model now uses the current ₹1.31L Core, ₹1.75L Pro and ₹3.25L Apex architecture as its blended planning basis. Replace the assumptions with supplier-quoted BOM and production data before fundraising.</p></Panel>
    <Panel title="24-month operating gates" kicker="Investor-facing execution horizon"><div className="grid gap-3 md:grid-cols-5">{OPERATING_GATES.map(([period,title,note]) => <div key={period} className="rounded-md border border-border p-4"><p className="text-xs font-semibold text-accent">{period}</p><p className="mt-2 text-sm font-medium">{title}</p><p className="mt-2 text-xs leading-5 text-muted">{note}</p></div>)}</div><p className="mt-4 text-xs text-muted">The 36-month model remains the strategic planning horizon; the Board cash graph uses the first 24 months for operating visibility.</p></Panel>
    <Panel title="Why this company" kicker="Controlled proof points"><div className="grid gap-3 md:grid-cols-2">{INVESTOR_PROOF_POINTS.map((p, i) => <div key={p} className="rounded-md border border-border p-4 text-sm"><span className="mr-2 text-accent">0{i + 1}</span>{p}</div>)}</div></Panel>
    <Panel title="Capital request" kicker="Evidence-led funding ladder"><div className="space-y-3">{INVESTOR_MILESTONES.map((m) => <div key={m.id} className="grid gap-2 rounded-md border border-border p-4 md:grid-cols-[8rem_7rem_1fr_10rem] md:items-center"><div><p className="text-xs text-subtle">{m.id}</p><p className="text-sm font-medium">{m.tranche}</p></div><div className="text-sm font-medium">₹{m.quantumLakh}L</div><div><p className="text-sm">{m.purpose}</p><p className="mt-1 text-xs text-muted">Evidence: {m.requiredEvidence}</p></div><div className="text-xs text-muted">{m.timing}<br />Gate: {m.decisionGate}</div></div>)}</div><p className="mt-4 text-xs text-muted">Strategy: {INVESTOR_BOARD_STATUS.strategy}</p></Panel>
    <Panel title="Use of proceeds" kicker="At each tranche"><div className="grid gap-3 md:grid-cols-5">{USE_OF_PROCEEDS.map((p) => <div key={p.tranche} className="rounded-md border border-border p-4"><p className="text-xs font-semibold text-accent">{p.tranche}</p><p className="mt-2 text-sm font-medium">{p.allocation}</p><p className="mt-2 text-xs text-muted">{p.note}</p></div>)}</div></Panel>
    <Panel title="36-month base-case snapshot" kicker="Strategic planning model · ₹ lakh"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Cumulative revenue</p><p className="mt-1 text-xl">{fmt(t.revenue)}</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Cumulative units</p><p className="mt-1 text-xl">{t.units}</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Cumulative funding</p><p className="mt-1 text-xl">{fmt(t.funding)}</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Cumulative EBITDA</p><p className="mt-1 text-xl">{fmt(t.ebitda)}</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">M36 closing cash</p><p className="mt-1 text-xl">{fmt(m36.closing)}</p></div></div><p className="mt-4 text-xs text-muted">These are management-model outputs, not forecasts or audited results. CA reconciliation and supplier-backed COGS validation are required before formal fundraising use.</p></Panel>
    <section className="rounded-xl border border-border p-6"><h2 className="text-sm font-semibold">Investor diligence rule</h2><p className="mt-3 text-sm leading-6 text-muted">Do not state that grants are awarded, engineering is validated, products are certified, manufacturing capacity is contracted, or statutory accounts are audited unless the corresponding evidence exists. The pitch page is a controlled presentation layer over the command registers, not a substitute for the evidence room.</p></section>
  </div>;
}
