import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { Panel, Kpi } from "@/components/kpi";
import { inr } from "@/lib/format";
import { approveInventoryOpeningBalance, createInventoryOpeningBalance, getAuthoritativeInventoryControl, listEprMappings, postInventoryOpeningBalance } from "@/lib/epr/final-control";

type Venture = "carbon" | "aluminium";
type Status = "all" | "draft" | "approved" | "posted";
type Opening = { id:string; venture:Venture; sku:string; unit:string; quantity:number|string; unit_cost_inr:number|string; reference:string; notes:string; status:"draft"|"approved"|"posted"|"rejected"; created_by:string; created_at:string; approved_by?:string|null; approved_at?:string|null; posted_by?:string|null; posted_at?:string|null };
type Mapping = { venture:Venture; sku:string; unit:string; status:string; effective_from?:string; effective_to?:string|null };

export const Route = createFileRoute("/command/inventory-openings")({
  loader: async () => { const [control,mappings] = await Promise.all([getAuthoritativeInventoryControl(), listEprMappings()]); return { ...control, mappings: mappings as Mapping[] }; },
  component: InventoryOpenings,
});

function InventoryOpenings() {
  const router = useRouter();
  const { openings, balances, mappings } = Route.useLoaderData() as { openings:Opening[]; balances:Array<{venture:Venture;sku:string;unit:string;quantity_balance:number|string}>; mappings:Mapping[] };
  const [ventureFilter,setVentureFilter]=useState<"all"|Venture>("all");
  const [statusFilter,setStatusFilter]=useState<Status>("all");
  const [form,setForm]=useState({venture:"aluminium" as Venture,sku:"",unit:"kg",quantity:"",unitCostInr:"",reference:"",notes:""});
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const filtered=useMemo(()=>openings.filter(x=>(ventureFilter==="all"||x.venture===ventureFilter)&&(statusFilter==="all"||x.status===statusFilter)),[openings,ventureFilter,statusFilter]);
  const drafts=openings.filter(x=>x.status==="draft").length; const approved=openings.filter(x=>x.status==="approved").length; const posted=openings.filter(x=>x.status==="posted").length; const postedQuantity=openings.filter(x=>x.status==="posted").reduce((sum,x)=>sum+Number(x.quantity),0);
  const skuOptions=useMemo(()=>Array.from(new Set(mappings.filter(x=>x.venture===form.venture&&x.status==="active").map(x=>x.sku))).sort(),[mappings,form.venture]);
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();setMessage(success);await router.invalidate()}catch(e){setError(e instanceof Error?e.message:"Operation failed.")}finally{setBusy(false)}}
  async function submit(e:FormEvent){e.preventDefault();const quantity=Number(form.quantity);const unitCostInr=Number(form.unitCostInr);if(!form.sku.trim()||!form.unit.trim()||!form.reference.trim()||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(unitCostInr)||unitCostInr<0){setError("Select an approved mapped SKU and enter unit, positive quantity, non-negative unit cost and a reference.");return}await run(()=>createInventoryOpeningBalance({data:{venture:form.venture,sku:form.sku.trim(),unit:form.unit.trim(),quantity,unitCostInr,reference:form.reference.trim(),notes:form.notes.trim()}}),"Opening balance created as DRAFT. Approve it before posting.")}
  return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.22em] text-green">Operate · controlled mutation</p><h1 className="mt-2 text-4xl font-bold text-accent">Opening Balances</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">Create, approve and post opening stock through the authoritative inventory and cost ledgers. Legacy seed inventory is excluded.</p></div><Link to="/command/inventory" className="rounded-lg border border-border px-4 py-2 text-sm">Back to Inventory Hub →</Link></div>
    <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Drafts" value={String(drafts)} /><Kpi label="Approved · pending posting" value={String(approved)} /><Kpi label="Posted" value={String(posted)} /><Kpi label="Total posted quantity" value={postedQuantity.toLocaleString(undefined,{maximumFractionDigits:4})} /></div>
    <Panel title="Create controlled opening balance" className="mt-6"><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <Field label="Venture"><select className="input" value={form.venture} onChange={e=>setForm({...form,venture:e.target.value as Venture,sku:""})}><option value="carbon">Carbon</option><option value="aluminium">Aluminium</option></select></Field>
      <Field label="Approved mapped SKU"><select className="input" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}><option value="">Select SKU</option>{skuOptions.map(s=><option key={s} value={s}>{s}</option>)}</select></Field>
      <Field label="Unit"><input className="input" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} /></Field>
      <Field label="Quantity"><input className="input" type="number" min="0" step="0.0001" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} /></Field>
      <Field label="Unit Cost (INR)"><input className="input" type="number" min="0" step="0.01" value={form.unitCostInr} onChange={e=>setForm({...form,unitCostInr:e.target.value})} /></Field>
      <Field label="Reference"><input className="input" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Count sheet / opening ref" /></Field>
      <Field label="Notes"><input className="input" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} /></Field>
      <div className="flex items-end"><button disabled={busy||skuOptions.length===0} className="w-full rounded-lg border border-green/40 bg-green/10 px-4 py-2.5 text-sm font-semibold text-fg disabled:opacity-50">{busy?"Saving…":"Create Draft"}</button></div>
    </form>{skuOptions.length===0&&<p className="mt-4 rounded-lg border border-yellow-400/30 p-3 text-sm text-yellow-200">No active BOM→SKU mapping is available for this venture. Create/approve the mapping first.</p>}{(message||error)&&<p className={`mt-4 rounded-lg border p-3 text-sm ${error?"border-red-400/40 text-red-300":"border-green/30 text-green"}`}>{error||message}</p>}</Panel>
    <Panel title="Opening balance register" className="mt-6"><div className="mb-4 flex flex-wrap gap-3"><select className="input max-w-[180px]" value={ventureFilter} onChange={e=>setVentureFilter(e.target.value as "all"|Venture)}><option value="all">All ventures</option><option value="carbon">Carbon</option><option value="aluminium">Aluminium</option></select><select className="input max-w-[180px]" value={statusFilter} onChange={e=>setStatusFilter(e.target.value as Status)}><option value="all">All statuses</option><option value="draft">Draft</option><option value="approved">Approved</option><option value="posted">Posted</option></select></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1500px] text-left text-sm"><thead className="text-[10px] uppercase tracking-[0.14em] text-green"><tr><th className="px-3 py-3">Venture</th><th className="px-3 py-3">SKU</th><th className="px-3 py-3">Unit</th><th className="px-3 py-3">Quantity</th><th className="px-3 py-3">Unit Cost</th><th className="px-3 py-3">Reference</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Created By</th><th className="px-3 py-3">Approved By</th><th className="px-3 py-3">Posted By</th><th className="px-3 py-3">Created At</th><th className="px-3 py-3">Approved At</th><th className="px-3 py-3">Posted At</th><th className="px-3 py-3">Actions</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} className="border-t border-border/70"><td className="px-3 py-3 uppercase">{x.venture}</td><td className="px-3 py-3 font-mono text-xs">{x.sku}</td><td className="px-3 py-3">{x.unit}</td><td className="px-3 py-3 tabular-nums">{Number(x.quantity)}</td><td className="px-3 py-3 tabular-nums">{inr(Number(x.unit_cost_inr))}</td><td className="px-3 py-3 text-xs">{x.reference}</td><td className="px-3 py-3 uppercase text-xs font-semibold">{x.status}</td><td className="px-3 py-3 text-xs">{x.created_by||"—"}</td><td className="px-3 py-3 text-xs">{x.approved_by||"—"}</td><td className="px-3 py-3 text-xs">{x.posted_by||"—"}</td><td className="px-3 py-3 text-xs text-muted">{fmt(x.created_at)}</td><td className="px-3 py-3 text-xs text-muted">{fmt(x.approved_at)}</td><td className="px-3 py-3 text-xs text-muted">{fmt(x.posted_at)}</td><td className="px-3 py-3">{x.status==="draft"&&<button disabled={busy} onClick={()=>run(()=>approveInventoryOpeningBalance({data:{openingId:x.id}}),"Opening balance approved. It is now ready to post.")} className="rounded-md border border-border px-3 py-1.5 text-xs">Approve</button>}{x.status==="approved"&&<button disabled={busy} onClick={()=>run(()=>postInventoryOpeningBalance({data:{openingId:x.id}}),"Opening balance posted to the authoritative quantity and cost ledgers.")} className="rounded-md border border-green/40 bg-green/10 px-3 py-1.5 text-xs font-semibold">Post</button>}{x.status==="posted"&&<span className="text-xs text-green">Read-only · Posted</span>}{x.status==="rejected"&&<span className="text-xs text-muted">Read-only</span>}</td></tr>)}</tbody></table></div>{filtered.length===0&&<div className="rounded-xl border border-dashed border-border p-6 text-sm text-muted">No opening balances match the selected filters.</div>}</Panel>
    <p className="mt-5 text-xs leading-5 text-subtle">Control rule: Draft → Approve → Post. Posting is performed only by the existing database-controlled function and establishes authoritative quantity and cost basis. This page never writes the inventory ledger directly.</p>
  </main>;
}
function fmt(value?:string|null){return value?new Date(value).toLocaleString():"—";}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-[10px] uppercase tracking-[0.14em] text-subtle">{label}</span>{children}</label>;}
