import { createFileRoute, Link } from "@tanstack/react-router";
import { Kpi, Panel } from "@/components/kpi";
import { INVESTOR_BOARD_STATUS, INVESTOR_MILESTONES, INVESTOR_PROOF_POINTS, USE_OF_PROCEEDS } from "@/lib/data/investor-board";
import { TIERS } from "@/lib/data/company";
import { buildModel, totals, GM, ASP_L, COGS_L } from "@/lib/finance/model";
export const Route = createFileRoute("/command/investor-pitch")({ component: InvestorPitch });
const fmt=(n:number)=>`₹${n.toFixed(1)}L`;
const OPERATING_GATES=[["M0–M6","Engineering","CAD/FEA, prototypes, IP and validation evidence"],["M6–M12","Pilot","Tooling, ISO path, factory qualification and pilot production"],["M12–M18","Launch","D2C launch, first customers and service feedback"],["M18–M24","Repeatability","Yield, warranty, service and working-capital discipline"],["M24–M30","Scale readiness","Demand, capacity, contribution margin and cash conversion evidence"],["M30–M36","Controlled scale","Capacity expansion only after evidence-backed unit economics"]] as const;
const SHOWCASE_CARDS=[
  ["Investor Presentation","Capital thesis, unit economics, funding ladder and 36-month gates.","/command/investor-pitch"],
  ["Board / Management","Executive control view for decisions, risks, milestones and governance.","/command/investor-board"],
  ["Product Walkthrough","VINDY product, engineering, design philosophy and technical proof layer.","/command/product"],
  ["Financial Cockpit","Cash, inventory, production, sales, funding and break-even in one executive view.","/command/financial-cockpit"],
  ["Manufacturing Demo","Pilot production, engineering control, quality and execution workflow.","/command/phase-6"],
  ["EPR / Compliance Demo","EPR workflow, execution and live transaction visibility.","/command/epr-live"],
] as const;
function InvestorPitch(){const rows=buildModel("base",false);const t=totals(rows);const m36=rows[35];const committedFunding=200;const maximumFunding=225;return <div className="space-y-7"><header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">VINDY · Showcase Mode</p><h1 className="mt-1 font-display text-4xl">Investor & Platform Showcase</h1><p className="mt-2 max-w-3xl text-sm text-muted">A controlled presentation layer for investors, board members, partners and demonstrations. It presents approved command views without changing the underlying operating routes or data model.</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full border border-border bg-surface px-3 py-1.5 text-xs text-muted">Showcase</span><span className="rounded-full border border-border bg-surface px-3 py-1.5 text-xs text-muted">Evidence-led</span><span className="rounded-full border border-border bg-surface px-3 py-1.5 text-xs text-muted">36-month horizon</span></div></header>
<Panel title="Showcase navigator" kicker="Choose the story you want to demonstrate"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{SHOWCASE_CARDS.map(([title,description,to])=><Link key={title} to={to as never} className="group rounded-xl border border-border bg-surface p-5 transition-colors hover:bg-bg"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{title}</p><p className="mt-2 text-xs leading-5 text-muted">{description}</p></div><span className="text-lg text-accent transition-transform group-hover:translate-x-1">→</span></div></Link>)}</div></Panel>
<section className="rounded-xl border border-border bg-surface p-6 sm:p-8"><p className="text-xs uppercase tracking-[0.18em] text-accent">Presentation thesis</p><h2 className="mt-3 max-w-4xl font-display text-3xl leading-tight">VINDY turns the operating model into a demonstrable business system: product, engineering, finance, manufacturing, EPR and governance connected through one command layer.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-muted">Use this view for investor meetings, board reviews, partner demonstrations and controlled product walkthroughs. Detailed operating controls remain behind role-aware access policies.</p></section>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Current tranche" value="₹15L" hint="Foundation stage"/><Kpi label="Committed ladder" value="₹2Cr" hint="Excludes standby"/><Kpi label="Maximum ladder" value="₹2.25Cr" hint="Includes ₹25L standby"/><Kpi label="36-mo cash" value={fmt(m36.closing)} hint="Strategic horizon"/></div>
<header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Investor relations · Dedicated pitch page</p><h2 className="mt-1 font-display text-2xl">Investment Case</h2><p className="mt-2 max-w-3xl text-sm text-muted">Investor-facing narrative generated from the controlled command registers. Financial figures are management-model assumptions until CA reconciliation; engineering and market claims remain subject to their evidence gates.</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><Link to="/command/investor-board" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">Investor / Board Control</Link><Link to="/command/ca-audit" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">CA Verification</Link><Link to="/command/finance-control" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">36-Month Finance</Link><Link to="/command/market-survey" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">Founder Market Survey</Link><Link to="/command/design-philosophy" className="rounded-md border border-border px-3 py-2 text-muted hover:bg-surface hover:text-fg">Design Philosophy</Link></div></header>
<section className="rounded-xl border border-border bg-surface p-6 sm:p-8"><p className="text-xs uppercase tracking-[0.18em] text-accent">Investment thesis</p><h2 className="mt-3 max-w-4xl font-display text-3xl leading-tight">An India-focused, IP-led carbon road-bike platform built around controlled engineering, rider fit, configurable specification and disciplined staged capital.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-muted">Vāyú Shastr is building VINDY as an asset-light product company: retain product definition, brand, customer relationship and relevant IP while using qualified manufacturing partners for carbon production. The customer proposition is engineered performance, fit and configuration at a materially more accessible price point.</p></section>
<Panel title="Market position" kicker="Segment the opportunity; do not present one headline TAM as fact"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Macro market</p><p className="mt-2 text-sm leading-5">Independent research points to a substantial Indian bicycle market, but published totals differ because definitions, channels and product scope differ.</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Addressable niche</p><p className="mt-2 text-sm leading-5">VINDY targets the higher-value performance road segment, with particular focus on carbon road bikes and riders seeking better fit and specification.</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Competitive thesis</p><p className="mt-2 text-sm leading-5">Compete on engineering, fit, configuration and value—not on imported-brand heritage or prestige signalling.</p></div></div><p className="mt-4 text-xs text-muted">The Founder Market Survey is founder-generated market intelligence, not audited market data. Investment-grade TAM/SAM/SOM should be rebuilt using primary trade data, dealer research and customer evidence.</p></Panel>
<Panel title="Tier unit economics" kicker="Management planning assumptions · supplier and production validation required"><div className="grid gap-3 md:grid-cols-3">{TIERS.map(tier=>{const margin=((tier.asp-tier.cogs)/tier.asp)*100;return <div key={tier.id} className="rounded-md border border-border p-4"><div className="flex items-baseline justify-between gap-3"><p className="text-sm font-medium">{tier.name}</p><p className="text-xs text-subtle">{tier.epithet}</p></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><p className="text-[10px] uppercase text-subtle">ASP</p><p className="mt-1 text-lg">{fmt(tier.asp/10000)}</p></div><div><p className="text-[10px] uppercase text-subtle">COGS</p><p className="mt-1 text-lg">{fmt(tier.cogs/10000)}</p></div><div><p className="text-[10px] uppercase text-subtle">GM</p><p className="mt-1 text-lg">{margin.toFixed(1)}%</p></div></div><p className="mt-3 text-xs leading-5 text-muted">Planning gross profit: {fmt((tier.asp-tier.cogs)/10000)} per bike. Validate BOM, yield, paint, assembly, logistics and warranty before treating this as realised margin.</p></div>})}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Blended ASP</p><p className="mt-1 text-xl">{fmt(ASP_L)}</p><p className="mt-1 text-xs text-muted">25% Core · 60% Pro · 15% Apex</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Blended COGS</p><p className="mt-1 text-xl">{fmt(COGS_L)}</p><p className="mt-1 text-xs text-muted">Management planning basis</p></div><div className="rounded-md border border-border p-4"><p className="text-xs text-subtle">Blended gross margin</p><p className="mt-1 text-xl">{GM.toFixed(1)}%</p><p className="mt-1 text-xs text-muted">Not historical performance</p></div></div></Panel>
<Panel title="36-month operating gates" kicker="Investor-facing execution horizon"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">{OPERATING_GATES.map(([period,title,note])=><div key={period} className="rounded-md border border-border p-4"><p className="text-xs font-semibold text-accent">{period}</p><p className="mt-2 text-sm font-medium">{title}</p><p className="mt-2 text-xs leading-5 text-muted">{note}</p></div>)}</div><p className="mt-4 text-xs text-muted">The command financial model runs through M36. Investor presentation may summarise shorter windows, but the controlled planning horizon is 36 months.</p></Panel>
<Panel title="Why this company" kicker="Controlled proof points"><div className="grid gap-3 md:grid-cols-2">{INVESTOR_PROOF_POINTS.map((p,i)=><div key={p} className="rounded-md border border-border p-4 text-sm"><span className="mr-2 text-accent">0{i+1}</span>{p}</div>)}</div></Panel>
<Panel title="Capital request" kicker="Evidence-led funding ladder"><div className="space-y-3">{INVESTOR_MILESTONES.map(m=><div key={m.id} className="grid gap-2 rounded-md border border-border p-4 md:grid-cols-[8rem_7rem_1fr_10rem] md:items-center"><div><p className="text-xs text-subtle">{m.id}</p><p className="text-sm font-medium">{m.tranche}</p></div><div className="text-sm font-medium">₹{m.quantumLakh}L</div><div><p className="text-sm">{m.purpose}</p><p className="mt-1 text-xs text-muted">Evidence: {m.requiredEvidence}</p></div><div className="text-xs text-muted">{m.timing}<br/>Gate: {m.decisionGate}</div></div>)}</div><p className="mt-4 text-xs text-muted">Committed ladder: ₹{committedFunding/100}Cr. Maximum planned capital including the conditional ₹25L standby facility: ₹{maximumFunding/100}Cr. Strategy: {INVESTOR_BOARD_STATUS.strategy}</p></Panel>
<Panel title="Use of proceeds" kicker="At each tranche"><div className="grid gap-3 md:grid-cols-5">{USE_OF_PROCEEDS.map(p=><div key={p.tranche} className="rounded-md border border-border p-4"><p className="text-xs font-semibold text-accent">{p.tranche}</p><p className="mt-2 text-sm font-medium">{p.allocation}</p><p className="mt-2 text-xs text-muted">{p.note}</p></div>)}</div></Panel>
<Panel title="36-month base-case snapshot" kicker="Strategic planning model · ₹ lakh"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Cumulative revenue",fmt(t.revenue)],["Cumulative units",String(t.units)],["Cumulative funding",fmt(t.funding)],["Cumulative EBITDA",fmt(t.ebitda)],["M36 closing cash",fmt(m36.closing)]].map(([label,value])=><div key={label} className="rounded-md border border-border p-4"><p className="text-xs text-subtle">{label}</p><p className="mt-1 text-xl">{value}</p></div>)}</div><p className="mt-4 text-xs text-muted">Management-model outputs, not forecasts or audited results. CA reconciliation and supplier-backed COGS validation are required before formal fundraising use.</p></Panel>
<section className="rounded-xl border border-border p-6"><h2 className="text-sm font-semibold">Investor diligence rule</h2><p className="mt-3 text-sm leading-6 text-muted">Do not state that grants are awarded, engineering is validated, products are certified, manufacturing capacity is contracted, or statutory accounts are audited unless the corresponding evidence exists. This showcase is a controlled presentation layer over the command registers.</p></section></div>}
