import { createFileRoute, Link } from "@tanstack/react-router";
import { Panel } from "@/components/kpi";

export const Route = createFileRoute("/command/market-survey")({ component: MarketSurvey });

const sources = [
  ["Fortune Business Insights", "2026", "$1.45B", "₹13,877 cr", "4.8% global proxy"],
  ["Ken Research", "2026", "$2.6B", "₹24,882 cr", "Not stated"],
  ["6Wresearch", "2025", "$2.7B", "₹25,839 cr", "6.2% (2025–31)"],
  ["TechSci Research", "2024", "$2.9B", "₹27,753 cr", "5.9% (2024–30)"],
  ["Grand View Research", "2025", "$3.70B", "₹35,411 cr", "15.0% (2026–33)"],
  ["Deep Market Insights", "2025", "$3.87B", "₹37,019 cr", "6.55% (2026–34)"],
];
const outlook = [["Fortune Business Insights", "₹17,542 cr"], ["6Wresearch", "₹36,366 cr"], ["TechSci Research", "₹41,448 cr"], ["Deep Market Insights", "₹54,176 cr"], ["Grand View Research", "₹81,906 cr"]];

function MarketSurvey() {
 return <div className="space-y-7">
  <header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Command · Founder research</p><h1 className="mt-1 font-display text-4xl text-accent">India Bicycle Market Survey</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Founder-compiled market survey, as on 22 August 2026. This page preserves the supplied research deck as an internal strategy reference; it is not presented as an audited market census.</p><div className="mt-4 flex flex-wrap gap-2"><Link to="/command" className="rounded-md border border-border px-3 py-2 text-xs text-muted hover:border-accent hover:text-accent">Command</Link><Link to="/command/investor-pitch" className="rounded-md border border-border px-3 py-2 text-xs text-muted hover:border-accent hover:text-accent">Investor Pitch</Link></div></header>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Present-day range" value="₹13,900–₹37,000 cr" note="Six private estimates"/><Metric label="Working midpoint" value="~₹27,000 cr" note="≈ US$2.8B"/><Metric label="2031 range" value="₹17,500–₹82,000 cr" note="Source CAGRs compounded"/><Metric label="Blended midpoint" value="~₹46,000 cr" note="Implied ~9–10% CAGR"/></div>
  <Panel title="01 · Market size today" kicker="Wide, honest range"><p className="text-sm leading-6 text-muted">The supplied survey deliberately avoids a false single market number. Six research houses estimate the Indian bicycle market differently because scope, base year and included categories differ. The working midpoint used in the deck is approximately ₹27,000 crore.</p></Panel>
  <Panel title="02 · Source comparison" kicker="Same market, six different yardsticks"><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-[10px] uppercase tracking-[0.14em] text-subtle"><tr><th className="px-3 py-3">Source</th><th>Base</th><th>US$</th><th>₹ crore</th><th>CAGR</th></tr></thead><tbody>{sources.map(r=><tr key={r[0]} className="border-t border-border"><td className="px-3 py-3 font-medium">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td className="text-muted">{r[4]}</td></tr>)}</tbody></table></div><div className="mt-5 grid gap-3 md:grid-cols-3"><Note title="Scope differs">Some estimates include e-cycles, parts/accessories and unorganised-sector volume; others focus on complete conventional bicycles.</Note><Note title="Base year differs">2024, 2025 and 2026 baselines are not directly comparable without adjustment.</Note><Note title="No census anchor">The deck notes no government or industry-body census equivalent to the auto sector.</Note></div></Panel>
  <Panel title="03 · Five-year outlook" kicker="Projected to 2031 using each source's own CAGR"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{outlook.map(([name,value])=><div key={name} className="rounded-lg border border-border p-4"><p className="text-xs text-subtle">{name}</p><p className="mt-2 font-display text-xl text-accent">{value}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-muted">This is a comparability exercise using the source forecasts, not a new independent forecast.</p></Panel>
  <Panel title="04–05 · Material mix & domestic/imported structure" kicker="Strategic reading for a carbon manufacturer"><div className="grid gap-4 md:grid-cols-3"><Material title="Steel" value="Largest by unit volume" note="Utility, cargo and rural bicycles; overwhelmingly domestic and low value per unit."/><Material title="Aluminium" value="Largest by value today" note="Mixed domestic assembly and imported tubing/components; entry to mid-premium."/><Material title="Carbon" value="Smallest volume · fastest-growing value" note="The survey describes frame supply as near-100% import-dependent, mainly Taiwan/China OEM factories."/></div><div className="mt-5 rounded-lg border border-border bg-bg/40 p-4 text-sm leading-6 text-muted">Global-proxy frame mix shown in the deck: <strong className="text-fg">Aluminium 38% · Carbon fibre 25% · Steel 27% · Titanium & other 10%</strong>. The deck explicitly flags this as a global proxy, not an India-measured split.</div></Panel>
  <Panel title="06 · Import trade snapshot" kicker="China supplies volume; Taiwan supplies value"><div className="grid gap-3 md:grid-cols-3"><Material title="China" value="$1.9M" note="Low-cost, high-volume complete bikes; ~90,000 units at the deck's cited $21 average."/><Material title="Taiwan" value="$1.4M" note="Premium components & complete bikes; ~2,450 units at the cited $571 average."/><Material title="Sri Lanka" value="$637k" note="Regional trade-agreement flows."/></div><p className="mt-4 text-xs leading-5 text-muted">The deck says these three represent ~77% of import value in the cited Indexbox slice, while warning that it is one HS-code slice/TTM view rather than the whole bicycle-and-parts trade.</p></Panel>
  <Panel title="Strategic implications for VéLOXIS" kicker="Founder synthesis"><div className="grid gap-3 md:grid-cols-2"><Note title="MFN origin dominance">The survey identifies China as 76.6% of overall import volume and places high-end carbon framesets from Taiwan, the US and Western Europe within the stated ~45–49% MFN tax stack.</Note><Note title="Supply-chain rerouting risk">Vietnam and Thailand can alter duty economics through ASEAN trade routes, so domestic advantage must be paired with lean manufacturing and shorter logistics.</Note><Note title="Domestic carbon opportunity">The deck frames carbon as a small but fast-growing, premium, import-dependent segment with limited domestic frame competition.</Note><Note title="Road-bike relevance">The survey's synthesis identifies road bikes as the revenue-leading product type in multiple cited 2025 estimates and the category where carbon frames concentrate.</Note></div></Panel>
  <section className="rounded-xl border border-border p-5"><p className="text-[11px] uppercase tracking-[0.18em] text-green">Method & caveats</p><h2 className="mt-1 font-display text-2xl text-accent">Use this as strategic evidence, not audited fact</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-muted"><li>• All market values are private research estimates except the cited DGCI&S principal trade data.</li><li>• USD→INR in the source deck uses ₹95.7 per US$ on 22 August 2026.</li><li>• Material mix percentages are global proxies where India-specific splits were unavailable.</li><li>• The deck recommends a primary DGCI&S pull and bottom-up dealer survey for investment-grade numbers.</li><li>• Compiled 22 August 2026 for internal planning use, not investment advice.</li></ul></section>
 </div>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="rounded-xl border border-border bg-bg-elevated/30 p-4"><p className="text-[10px] uppercase tracking-[0.13em] text-subtle">{label}</p><p className="mt-2 font-display text-xl text-accent">{value}</p><p className="mt-1 text-xs text-muted">{note}</p></div>}
function Note({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-lg border border-border p-4"><p className="font-medium text-fg">{title}</p><p className="mt-2 text-xs leading-5 text-muted">{children}</p></div>}
function Material({title,value,note}:{title:string;value:string;note:string}){return <div className="rounded-lg border border-border p-4"><p className="text-xs uppercase tracking-[0.12em] text-subtle">{title}</p><p className="mt-2 font-display text-lg text-accent">{value}</p><p className="mt-2 text-xs leading-5 text-muted">{note}</p></div>}
