import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { buildModelWithInputs, type ScenarioId } from "@/lib/finance/model";
import { buildAccountingModel } from "@/lib/finance/accounting";
import { buildComponentRequirements, buildOperationsMonths, totalBomRequirementInr } from "@/lib/finance/operations-engine";
import { inr, lakh } from "@/lib/format";
import { useVeloxis } from "@/lib/store";

export const Route = createFileRoute("/command/operations")({ component: Operations });

function Operations() {
  const scenario = useVeloxis((s) => s.scenario) as ScenarioId;
  const drawStandby = useVeloxis((s) => s.drawStandby);
  const finance = useVeloxis((s) => s.finance);
  const accounting = useVeloxis((s) => s.accounting);
  const rows = useMemo(() => buildModelWithInputs(scenario, drawStandby, finance), [scenario, drawStandby, finance]);
  const accountingRows = useMemo(() => buildAccountingModel(rows, accounting), [rows, accounting]);
  const months = useMemo(() => buildOperationsMonths(rows, finance), [rows, finance]);
  const components = useMemo(() => buildComponentRequirements(rows, finance), [rows, finance]);
  const bomRequirement = totalBomRequirementInr(rows, finance);
  const trough = accountingRows.reduce((min, r) => r.closingCash < min.closingCash ? r : min, accountingRows[0]);
  const workingCapital = accountingRows.at(-1) ? accountingRows.at(-1)!.receivables + accountingRows.at(-1)!.inventory - accountingRows.at(-1)!.payables : 0;

  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Phase 3 · operations control</p><h1 className="font-display text-4xl">Operations & Procurement</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Production now connects to BOM requirements, procurement exposure and accounting cash. This is the bridge from an engineering plan to the money required to build it.</p></div><Link to="/command/production" className="text-sm font-semibold text-accent">Production planning →</Link></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="36-mo units" value={String(rows.reduce((s,r)=>s+r.units,0))} hint={scenario}/><Kpi label="BOM requirement" value={inr(Math.round(bomRequirement))} hint="Quantity × landed cost"/><Kpi label="Accounting purchases" value={lakh(accountingRows.reduce((s,r)=>s+r.purchases,0))} hint="Inventory movement"/><Kpi label="Working capital" value={lakh(workingCapital)} hint="AR + inventory − AP at M36"/><Kpi label="Cash trough" value={lakh(trough.closingCash)} hint={`M${trough.m}`} tone={trough.closingCash<0?"danger":trough.closingCash<15?"warn":"ok"}/></div>
    <Panel title="Monthly production → material requirement" kicker="36 months · live BOM"><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-[0.14em] text-subtle"><tr><th className="px-3 py-3 text-left">Month</th><th className="px-3 py-3 text-right">Units</th><th className="px-3 py-3 text-right">Aluminium</th><th className="px-3 py-3 text-right">Carbon</th><th className="px-3 py-3 text-right">Premium</th><th className="px-3 py-3 text-right">BOM req.</th><th className="px-3 py-3 text-right">Inventory buy</th><th className="px-3 py-3 text-right">Accounting cash</th></tr></thead><tbody>{months.filter(r=>r.units>0||r.bomRequirementInr>0).map(r=><tr key={r.m} className="border-t border-border/70"><td className="px-3 py-3 font-semibold text-fg">M{r.m}</td><td className="px-3 py-3 text-right tabular-nums">{r.units}</td><td className="px-3 py-3 text-right tabular-nums text-muted">{r.aluminiumUnits}</td><td className="px-3 py-3 text-right tabular-nums text-muted">{r.carbonUnits}</td><td className="px-3 py-3 text-right tabular-nums text-muted">{r.premiumCarbonUnits}</td><td className="px-3 py-3 text-right tabular-nums text-accent">{inr(Math.round(r.bomRequirementInr))}</td><td className="px-3 py-3 text-right tabular-nums">{lakh(r.inventoryBuy)}</td><td className="px-3 py-3 text-right tabular-nums">{lakh(accountingRows[r.m-1]?.closingCash??0)}</td></tr>)}</tbody></table></div></Panel>
    <Panel title="Component procurement exposure" kicker="36-mo requirement from BOM"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-[0.14em] text-subtle"><tr><th className="px-3 py-3 text-left">Component</th><th className="px-3 py-3 text-right">Required qty</th><th className="px-3 py-3 text-right">Estimated landed spend</th></tr></thead><tbody>{components.slice(0,18).map(r=><tr key={r.item} className="border-t border-border/70"><td className="px-3 py-3 font-medium text-fg">{r.item}</td><td className="px-3 py-3 text-right tabular-nums">{r.quantity.toFixed(r.quantity%1?2:0)}</td><td className="px-3 py-3 text-right tabular-nums">{inr(Math.round(r.estimatedCostInr))}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs leading-5 text-muted">This is a BOM-driven requirement, not yet a purchase order or stock deduction. Phase 3 keeps the engineering requirement separate until each BOM component is mapped to an operational SKU and supplier lead time.</p></Panel>
    <div className="grid gap-4 lg:grid-cols-3"><Panel title="Working capital" kicker="Accounting layer"><p className="text-sm text-muted">M36 AR</p><p className="text-xl tabular-nums text-fg">{lakh(accountingRows.at(-1)?.receivables??0)}</p><p className="mt-3 text-sm text-muted">M36 inventory</p><p className="text-xl tabular-nums text-fg">{lakh(accountingRows.at(-1)?.inventory??0)}</p><p className="mt-3 text-sm text-muted">M36 AP</p><p className="text-xl tabular-nums text-fg">{lakh(accountingRows.at(-1)?.payables??0)}</p></Panel><Panel title="Procurement rules" kicker="Control before cash"><ul className="space-y-2 text-sm text-muted"><li>• Validate supplier quote before replacing BOM estimates.</li><li>• Separate recoverable GST from product COGS with the CA.</li><li>• Confirm lead time and MOQ before committing the purchase month.</li><li>• Do not treat listed catalogue prices as accounting inventory cost.</li></ul></Panel><Panel title="Next operational link" kicker="Phase 3 → execution"><p className="text-sm leading-6 text-muted">Map BOM components to operational inventory SKUs, then add supplier lead time, MOQ and purchase timing. Until that mapping exists, the system reports requirement and exposure without pretending that stock is consumed.</p><Link to="/command/inventory" className="mt-4 inline-block text-sm font-semibold text-accent">Open inventory control →</Link></Panel></div>
  </div>;
}
