import { createFileRoute, Link } from "@tanstack/react-router";
import { Panel } from "@/components/kpi";

export const Route = createFileRoute("/command/phase-5")({ component: Phase5 });

const GATES = [
  ["P5-01", "Engineering master", "VEDM-301 Rev 5.3.8 is the controlled authority. Reconcile geometry, interfaces, drawings, revision status and configuration before tooling release."],
  ["P5-02", "ECR / configuration control", "Geometry, material, layup, tooling, process and supplier changes require controlled ECR review and impact assessment before release."],
  ["P5-03", "CAD + geometry closure", "Lock the complete XS–XL geometry master and interfaces only after reconciliation; historical values remain superseded."],
  ["P5-04", "Fork / tyre clearance", "Reconcile front/rear inflated tyre envelope. 35 mm is the controlled baseline/target; 700×40 remains a development verification target."],
  ["P5-05", "Structural / FEA", "Confirm laminate adequacy and structural viability through engineering evidence before design freeze; do not convert working targets into facts."],
  ["P5-06", "Supplier qualification", "NDA, controlled RFQ/MOQ, capability review, quality-system review, subcontracting controls and qualification decision precede pilot PO."],
  ["P5-07", "Tooling control", "Buyer-owned tooling, custody, maintenance, retrieval/non-use rights and acceptance against controlled tooling drawings."],
  ["P5-08", "Material + process control", "Prepreg/material certificates, lot traceability, layup schedule, cure cycle, machining and assembly process controls must be defined."],
  ["P5-09", "Quality system", "Incoming, in-process and final inspection; NDT; cosmetic inspection; serial genealogy; NCR/CAPA; warranty/failure-analysis feedback."],
  ["P5-10", "Capability gate", "Critical dimensions require objective capability evidence; Cp/Cpk target ≥1.33 where applicable and agreed with the manufacturing quality plan."],
  ["P5-11", "ISO 4210 path", "Maintain applicable lab/test planning and evidence. Validation/certification is not claimed until the corresponding objective evidence exists."],
  ["P5-12", "Phase 6 entry", "Engineering, supplier, tooling, process and quality prerequisites must be ready before controlled pilot production starts."],
];

function Phase5() {
  return <div className="space-y-6">
    <header className="rounded-2xl border border-border bg-bg-elevated/70 p-5"><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Execution stage 05</p><h1 className="mt-1 font-display text-4xl text-accent">Phase 5 · Engineering, Tooling & Quality Gate</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-muted">The hard gate between commercial readiness and pilot production. Phase 5 controls engineering authority, ECRs, supplier qualification, tooling, process traceability, quality and the ISO 4210 evidence path.</p></header>
    <Panel title="Phase 5 prerequisite register" kicker="No skipped gates"><div className="overflow-hidden rounded-xl border border-border">{GATES.map(([id,title,detail])=><div key={id} className="grid gap-2 border-b border-border p-4 last:border-b-0 md:grid-cols-[90px_220px_1fr]"><span className="text-xs font-semibold text-accent">{id}</span><span className="text-sm font-medium text-fg">{title}</span><span className="text-sm leading-6 text-muted">{detail}</span></div>)}</div></Panel>
    <div className="grid gap-4 md:grid-cols-3"><Panel title="Engineering Control" kicker="ECR → BOM → finance"><p className="text-sm leading-6 text-muted">Revision control includes BOM/COGS, weight, production and inventory impact. Approval precedes release.</p><Link to="/command/engineering" className="mt-3 inline-block text-sm text-accent">Open engineering →</Link></Panel><Panel title="Manufacturing Controls" kicker="Supplier → tooling → pilot"><p className="text-sm leading-6 text-muted">Supplier qualification, tooling ownership, pilot build, traceability and release gates are controlled here.</p><Link to="/command/manufacturing" className="mt-3 inline-block text-sm text-accent">Open manufacturing →</Link></Panel><Panel title="Quality Control" kicker="IQC → IPQC → FQC → CAPA"><p className="text-sm leading-6 text-muted">Inspection, NCR/CAPA, warranty and failure analysis remain evidence-controlled.</p><Link to="/command/quality" className="mt-3 inline-block text-sm text-accent">Open quality →</Link></Panel></div>
    <Panel title="Locked correction register" kicker="Current working baseline"><div className="grid gap-3 md:grid-cols-2">{[["Authority","VEDM-301 Rev 5.3.8","Controlled engineering master; older geometry is historical/superseded."],["Fork","~380 mm A-C development direction","~378 mm is an indicated clearance correction, not a production lock; offset/trail unvalidated."],["Tyre","35 mm baseline / 700×40 target","700×40 requires CAD and physical verification."],["BB","T47i · 85.5 mm","Corrected configuration; historical 68 mm must not return."],["Carbon","T700/T800 mixed","Planned material system; final laminate schedule remains controlled IP."],["Frame","850–950 g painted Medium","Target only until prototype weighing/structural evidence."],["Tube architecture","VAEA / VEDM-503","DT 3.5:1 KVF/Kammtail; TT 3.2:1 flattened aero ellipse/VTS™ intent; ST 3.0:1 KVF."],["Company / product","Vāyú Shastr Pvt Ltd / VéLOXIS","Company and consumer/product identities remain distinct."]].map(([a,b,c])=><div key={a} className="rounded-xl border border-border p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-subtle">{a}</p><p className="mt-1 text-sm font-semibold text-fg">{b}</p><p className="mt-1 text-xs leading-5 text-muted">{c}</p></div>)}</div></Panel>
    <div className="flex flex-wrap gap-2"><Link to="/command/phase-4" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold">← Phase 4</Link><Link to="/command/phase-6" className="rounded-lg border border-accent px-3 py-2 text-xs font-semibold text-accent">Phase 6 →</Link><Link to="/command/phase-6a" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold">Phase 6A EPR →</Link></div>
  </div>;
}
