import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { getProcurementPlanningReport, setProcurementSkuAction, type ReconciledRequirementRow } from "@/lib/procurement-authority";

export const Route=createFileRoute("/command/procurement-planning")({loader:()=>getProcurementPlanningReport(),component:ProcurementPlanning});
const lakh=(n:number)=>`₹${Number(n).toFixed(1)}L`;

function ProcurementPlanning(){
  const data=Route.useLoaderData();const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState("");
  const net=data.requirements.reduce((s,r)=>s+r.netRequirement,0);const committed=data.requirements.reduce((s,r)=>s+r.committedRequirement,0);const exceptions=data.unprojectedCommitments.length+data.planningMappingIssues.length;
  async function action(row:ReconciledRequirementRow,actionType:"rfq"|"approval"|"po"){const key=`${row.requirementMonth}-${row.sku}-${actionType}`;setBusy(key);setMessage("");try{await setProcurementSkuAction({data:{requirementMonth:row.requirementMonth,sku:row.sku,unit:row.unit,actionType,quantity:row.netRequirement,status:"in_progress",demandBasis:row.demandBasis,note:`Raised from reconciled ${row.demandBasis} requirement for M${row.requirementMonth}.`}});setMessage(`${row.sku} M${row.requirementMonth}: ${actionType.toUpperCase()} in progress for ${row.netRequirement.toFixed(2)} ${row.unit}.`);}catch(e){setMessage(e instanceof Error?e.message:"Unable to update procurement action.");}finally{setBusy(null);}}
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-10 sm:px-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] uppercase tracking-[0.22em] text-green">Plan + commitments · reconciled supply signal</p><h1 className="mt-2 text-4xl font-bold text-accent">Procurement Planning</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-muted">One requirement view reconciles the 36-month family plan with exact confirmed-order demand, physical FIFO stock, reservations, MSL and authorised open POs. Plan and commitments remain separately visible; the governing demand signal is not double-counted.</p></div><div className="flex flex-wrap gap-2"><Link to="/command/purchase-execution" className="rounded-lg bg-accent px-4 py-2.5 text-sm font-semibold text-bg">Execute purchase</Link><Link to="/command/inventory" className="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold text-muted hover:text-accent">Master Inventory</Link><Link to="/command/sales" className="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold text-muted hover:text-accent">Commercial</Link></div></header>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="Plan procurement" value={lakh(data.summary.totalProcurementLakh)} hint="36M finance baseline"/><Kpi label="Committed demand" value={`${committed.toFixed(0)} units`} hint="Exact released job cards"/><Kpi label="Net SKU requirement" value={`${net.toFixed(0)} units`} hint="After stock + PO + MSL"/><Kpi label="Control exceptions" value={String(exceptions)} hint="Mapping / projection blockers" tone={exceptions?"danger":"ok"}/><Kpi label="Planning horizon" value="36 mo" hint="M1 → M36"/></div>
    {message?<div className="rounded-lg border border-border bg-surface px-4 py-3 text-sm text-muted">{message}</div>:null}
    {exceptions?<Panel title="Needs attention" kicker="Resolve before treating the material promise as reliable"><div className="space-y-3">{data.planningMappingIssues.map((issue)=><div key={issue} className="rounded-lg border border-warn/30 bg-warn/5 p-3 text-sm text-warn">{issue}</div>)}{data.unprojectedCommitments.map((o)=><div key={o.id} className="rounded-lg border border-warn/30 bg-warn/5 p-3"><p className="text-sm font-semibold text-fg">{o.id} · {o.variant_name??o.variant_id??"Variant missing"}</p><p className="mt-1 text-xs text-muted">Confirmed M{Number(o.plan_month)} · {Number(o.units)} units. Production projection is missing, stale or unreleased. Synchronize the current Commercial revision.</p></div>)}</div></Panel>:null}
    <Panel title="Reconciled SKU requirements" kicker="Plan vs committed → stock → reservations → MSL → open PO → net buy"><div className="overflow-x-auto"><table className="w-full min-w-[1450px] text-left text-xs"><thead className="border-b border-border text-[10px] uppercase tracking-[0.13em] text-subtle"><tr><th className="px-2 py-3">Month</th><th className="px-2 py-3">SKU</th><th className="px-2 py-3 text-right">Plan</th><th className="px-2 py-3 text-right">Committed</th><th className="px-2 py-3 text-right">Governing</th><th className="px-2 py-3 text-right">Physical</th><th className="px-2 py-3 text-right">Reserved</th><th className="px-2 py-3 text-right">ATP</th><th className="px-2 py-3 text-right">MSL</th><th className="px-2 py-3 text-right">Open PO</th><th className="px-2 py-3 text-right">Projected close</th><th className="px-2 py-3 text-right">Net buy</th><th className="px-2 py-3">Basis</th><th className="px-2 py-3">Action</th></tr></thead><tbody>{data.requirements.map((r)=><tr key={`${r.requirementMonth}-${r.sku}-${r.unit}`} className="border-t border-border/70"><td className="px-2 py-3 font-semibold">M{r.requirementMonth}</td><td className="px-2 py-3"><span className="font-mono font-semibold text-fg">{r.sku}</span> <span className="text-subtle">{r.unit}</span></td><td className="px-2 py-3 text-right">{r.plannedRequirement.toFixed(2)}</td><td className="px-2 py-3 text-right">{r.committedRequirement.toFixed(2)}</td><td className="px-2 py-3 text-right font-semibold">{r.grossRequirement.toFixed(2)}</td><td className="px-2 py-3 text-right">{r.physicalQuantity.toFixed(2)}</td><td className="px-2 py-3 text-right">{r.reservedQuantity.toFixed(2)}</td><td className="px-2 py-3 text-right">{r.availableToPromise.toFixed(2)}</td><td className="px-2 py-3 text-right">{r.minimumStockLevel.toFixed(2)}</td><td className="px-2 py-3 text-right">{r.openPoQuantity.toFixed(2)}</td><td className="px-2 py-3 text-right">{r.projectedEndingStock.toFixed(2)}</td><td className={`px-2 py-3 text-right font-bold ${r.netRequirement>0?"text-warn":"text-green"}`}>{r.netRequirement.toFixed(2)}</td><td className="px-2 py-3 uppercase text-subtle">{r.demandBasis}</td><td className="px-2 py-3">{r.netRequirement>0?<div className="flex gap-2">{(["rfq","approval","po"] as const).map((a)=><button key={a} disabled={busy===`${r.requirementMonth}-${r.sku}-${a}`} onClick={()=>void action(r,a)} className="text-xs font-semibold text-accent disabled:opacity-40">{a.toUpperCase()}</button>)}</div>:<span className="text-green">Covered</span>}</td></tr>)}</tbody></table>{data.requirements.length===0?<p className="py-8 text-center text-sm text-muted">No mapped material requirement is generated. Check approved planning-standard BOM mappings.</p>:null}</div></Panel>
    <details className="rounded-xl border border-border bg-surface/30 p-4"><summary className="cursor-pointer text-sm font-semibold text-fg">36-month finance context</summary><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-xs"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr><th className="px-2 py-2 text-left">Requirement</th><th className="px-2 py-2 text-left">Plan action</th><th className="px-2 py-2 text-left">Units</th><th className="px-2 py-2 text-left">Longitude / Latitude / Altitude</th><th className="px-2 py-2 text-right">Finance procurement</th><th className="px-2 py-2 text-left">Tranche</th></tr></thead><tbody>{data.forecast.map((r)=><tr key={r.month} className="border-t border-border"><td className="px-2 py-2">M{r.requirementMonth}</td><td className="px-2 py-2 text-accent">M{r.planningMonth}</td><td className="px-2 py-2">{r.units}</td><td className="px-2 py-2">{r.coreUnits} / {r.proUnits} / {r.apexUnits}</td><td className="px-2 py-2 text-right">{r.procurementLakh?lakh(r.procurementLakh):"—"}</td><td className="px-2 py-2">{r.tranche}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-muted">This is modeled intent, not a PO register. Execution actions above preserve provenance and distinguish forecast from commitment.</p></details>
  </main>;
}
