import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { buildModelWithInputs, type ProductLineId, type ScenarioId } from "@/lib/finance/model";
import { buildAccountingModel } from "@/lib/finance/accounting";
import { buildSalesMonths, productAsp, salesTotals, type SalesChannel, type SalesOrder, type SalesOrderStatus } from "@/lib/finance/sales-engine";
import { lakh } from "@/lib/format";
import { useVeloxis } from "@/lib/store";

export const Route = createFileRoute("/command/sales")({ component: SalesPlanning });
const ORDERS_KEY="veloxis-sales-orders-v1", ACTUALS_KEY="veloxis-actuals-v1";
const statusOptions:SalesOrderStatus[]=["lead","confirmed","delivered","cancelled"];
const channelOptions:SalesChannel[]=["direct","dealer","online"];
function SalesPlanning(){
 const scenario=useVeloxis(s=>s.scenario) as ScenarioId,drawStandby=useVeloxis(s=>s.drawStandby),finance=useVeloxis(s=>s.finance),accounting=useVeloxis(s=>s.accounting);const rows=useMemo(()=>buildModelWithInputs(scenario,drawStandby,finance),[scenario,drawStandby,finance]);const accountingRows=useMemo(()=>buildAccountingModel(rows,accounting),[rows,accounting]);
 const [orders,setOrders]=useState<SalesOrder[]>([]);const [actuals,setActuals]=useState<Record<number,{units?:number|null;revenue?:number|null}>>({});const [draft,setDraft]=useState({month:1,product:"carbon" as ProductLineId,units:1,channel:"direct" as SalesChannel,status:"confirmed" as SalesOrderStatus});
 useEffect(()=>{try{const o=localStorage.getItem(ORDERS_KEY);if(o)setOrders(JSON.parse(o));const a=localStorage.getItem(ACTUALS_KEY);if(a){const parsed=JSON.parse(a);const compact:Record<number,{units?:number|null;revenue?:number|null}>={};Object.entries(parsed).forEach(([m,v]:any)=>{compact[Number(m)]={units:v?.units,revenue:v?.revenue}});setActuals(compact)}}catch{}},[]);
 const sales=useMemo(()=>buildSalesMonths(rows,finance,orders,actuals,accounting),[rows,finance,orders,actuals,accounting]);const totals=salesTotals(sales);const latest=sales.filter(r=>r.ordersUnits>0||r.actualUnits>0).at(-1)?.m??0;const trough=accountingRows.reduce((a,b)=>b.closingCash<a.closingCash?b:a,accountingRows[0]);
 function saveOrders(next:SalesOrder[]){setOrders(next);try{localStorage.setItem(ORDERS_KEY,JSON.stringify(next))}catch{}} function addOrder(){const asp=productAsp(finance,draft.product);if(draft.month<1||draft.month>36||draft.units<=0||asp<=0)return;saveOrders([...orders,{id:`SO-${Date.now()}`,month:draft.month,product:draft.product,units:draft.units,aspLakh:asp,channel:draft.channel,status:draft.status}])}function updateOrder(id:string,key:"month"|"units"|"status",value:number|string){saveOrders(orders.map(o=>o.id===id?{...o,[key]:key==="status"?value:Number(value)}:o))}
 return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Commercial · Phase 4</p><h1 className="mt-1 font-display text-4xl">Sales & Revenue Engine</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Sales now connects product economics, production capacity, orders, revenue, collections and receivables. Actuals remain separate and the rolling view uses verified actuals where entered.</p></div><div className="flex gap-2"><Link to="/command/finance-assumptions" className="rounded-lg border border-accent px-4 py-2.5 text-sm font-semibold text-accent">Pricing assumptions</Link><Link to="/command/financial-cockpit" className="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold text-muted">Cash cockpit</Link></div></div>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Plan units" value={String(totals.plannedUnits)} hint="36 months"/><Kpi label="Plan revenue" value={lakh(totals.plannedRevenue)} hint="ASP × planned units"/><Kpi label="Order units" value={String(totals.ordersUnits)} hint="Non-cancelled orders"/><Kpi label="Order value" value={lakh(totals.ordersRevenue)} hint="Current order book"/><Kpi label="Collections" value={lakh(totals.collections)} hint={`Collection timing ${accounting.collectionDays??accounting.collectionMonths*30}d`}/><Kpi label="Cash trough" value={lakh(trough.closingCash)} hint={`M${trough.m}`} tone={trough.closingCash<0?"danger":trough.closingCash<15?"warn":"ok"}/></div>
 <Panel title="Plan → Orders → Revenue → Collections" kicker="One commercial chain"><div className="grid gap-3 md:grid-cols-5">{[["01","Plan","Units × ASP"],["02","Order","Committed demand"],["03","Revenue","Delivery / sale event"],["04","Receivable","Uncollected revenue"],["05","Collection","Collection days → cash"]].map(([n,t,d])=><div key={n} className="rounded-xl border border-border bg-bg-elevated/40 p-4"><span className="text-[10px] font-bold tracking-[0.16em] text-accent">{n}</span><p className="mt-2 text-sm font-semibold text-fg">{t}</p><p className="mt-1 text-xs leading-5 text-muted">{d}</p></div>)}</div></Panel>
 <Panel title="Order book" kicker="Management capture · not an ERP sales ledger"><div className="grid gap-3 rounded-xl border border-border bg-surface p-4 md:grid-cols-6"><label className="text-xs text-muted">Month<input type="number" min="1" max="36" value={draft.month} onChange={e=>setDraft({...draft,month:Number(e.target.value)})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm text-fg"/></label><label className="text-xs text-muted">Product<select value={draft.product} onChange={e=>setDraft({...draft,product:e.target.value as ProductLineId})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm text-fg">{finance.productLines.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label className="text-xs text-muted">Units<input type="number" min="1" value={draft.units} onChange={e=>setDraft({...draft,units:Number(e.target.value)})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm text-fg"/></label><label className="text-xs text-muted">Channel<select value={draft.channel} onChange={e=>setDraft({...draft,channel:e.target.value as SalesChannel})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm text-fg">{channelOptions.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs text-muted">Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as SalesOrderStatus})} className="mt-1 w-full rounded-md border border-border bg-bg px-2 py-2 text-sm text-fg">{statusOptions.map(x=><option key={x}>{x}</option>)}</select></label><button type="button" onClick={addOrder} className="self-end rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg">Add order</button></div>
 {orders.length===0?<p className="mt-4 text-sm text-muted">No order-book entries yet. Add confirmed demand here; this does not overwrite the financial Plan.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr><th className="px-3 py-3 text-left">Order</th><th className="px-3 py-3">Month</th><th className="px-3 py-3 text-left">Product</th><th className="px-3 py-3 text-right">Units</th><th className="px-3 py-3 text-right">Value</th><th className="px-3 py-3">Channel</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-t border-border"><td className="px-3 py-3 text-xs text-muted">{o.id}</td><td className="px-3 py-3"><input type="number" min="1" max="36" value={o.month} onChange={e=>updateOrder(o.id,"month",Number(e.target.value))} className="w-16 rounded border border-border bg-bg px-2 py-1 text-fg"/></td><td className="px-3 py-3 text-fg">{finance.productLines.find(p=>p.id===o.product)?.label??o.product}</td><td className="px-3 py-3 text-right"><input type="number" min="1" value={o.units} onChange={e=>updateOrder(o.id,"units",Number(e.target.value))} className="w-16 rounded border border-border bg-bg px-2 py-1 text-right text-fg"/></td><td className="px-3 py-3 text-right tabular-nums">{lakh(o.units*o.aspLakh)}</td><td className="px-3 py-3 text-center text-xs text-muted">{o.channel}</td><td className="px-3 py-3"><select value={o.status} onChange={e=>updateOrder(o.id,"status",e.target.value)} className="rounded border border-border bg-bg px-2 py-1 text-xs text-fg">{statusOptions.map(x=><option key={x}>{x}</option>)}</select></td></tr>)}</tbody></table></div>}</Panel>
 <Panel title="36-month revenue & collection view" kicker={`Actual through M${latest||"—"}; future months remain plan-driven`}><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-xs"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr><th className="px-3 py-3 text-left">Month</th><th className="px-3 py-3 text-right">Plan units</th><th className="px-3 py-3 text-right">Orders</th><th className="px-3 py-3 text-right">Actual units</th><th className="px-3 py-3 text-right">Plan revenue</th><th className="px-3 py-3 text-right">Orders value</th><th className="px-3 py-3 text-right">Actual revenue</th><th className="px-3 py-3 text-right">Variance</th><th className="px-3 py-3 text-right">Collections</th><th className="px-3 py-3 text-right">AR</th></tr></thead><tbody>{sales.map(r=><tr key={r.m} className="border-t border-border"><td className="px-3 py-2 font-medium text-fg">M{r.m}</td><td className="px-3 py-2 text-right tabular-nums">{r.plannedUnits}</td><td className="px-3 py-2 text-right tabular-nums">{r.ordersUnits||"—"}</td><td className="px-3 py-2 text-right tabular-nums">{actuals[r.m]?.units??"—"}</td><td className="px-3 py-2 text-right tabular-nums">{lakh(r.plannedRevenue)}</td><td className="px-3 py-2 text-right tabular-nums">{lakh(r.ordersRevenue)}</td><td className="px-3 py-2 text-right tabular-nums">{actuals[r.m]?.revenue==null?"—":lakh(actuals[r.m]?.revenue??0)}</td><td className={`px-3 py-2 text-right tabular-nums ${r.varianceRevenue<0?"text-danger":"text-ok"}`}>{(actuals[r.m]?.revenue!=null||r.ordersRevenue>0)?lakh(r.varianceRevenue):"—"}</td><td className="px-3 py-2 text-right tabular-nums text-accent">{lakh(r.collections)}</td><td className="px-3 py-2 text-right tabular-nums">{lakh(r.openReceivables)}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-5 text-muted">Collections use the accounting collection-days assumption. This is a management revenue/order layer; statutory revenue recognition, tax invoices, returns and channel-specific terms still require CA/ERP treatment.</p></Panel>
 <Panel title="Connected controls" kicker="No duplicate assumptions"><div className="flex flex-wrap gap-2"><Link to="/command/finance-assumptions" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:border-accent">Pricing / mix / launch</Link><Link to="/command/product" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:border-accent">Product economics</Link><Link to="/command/production" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:border-accent">Production capacity</Link><Link to="/command/actuals" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:border-accent">Enter actuals</Link><Link to="/command/financial-cockpit" className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:border-accent">Financial cockpit</Link></div></Panel></div>;
}
