import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { buildModelWithInputs, minCash, SCENARIOS, totals, type ScenarioId } from "@/lib/finance/model";
import { useVeloxis } from "@/lib/store";
import { lakh } from "@/lib/format";
import { ExplainableValue } from "@/components/explainable-value";

export const Route = createFileRoute("/command/scenarios")({ component: Scenarios });
const money=(n:number)=>`₹${n.toFixed(1)}L`;

type ScenarioCase = { id: ScenarioId; meta: (typeof SCENARIOS)[ScenarioId]; t: ReturnType<typeof totals>; trough: ReturnType<typeof minCash>; gp: number; be: number | null; last: ReturnType<typeof buildModelWithInputs>[number] };

function Scenarios(){
  const drawStandby=useVeloxis(s=>s.drawStandby); const finance=useVeloxis(s=>s.finance); const active=useVeloxis(s=>s.scenario); const setScenario=useVeloxis(s=>s.setScenario);
  const cases=useMemo<ScenarioCase[]>(()=> (Object.entries(SCENARIOS) as [ScenarioId,(typeof SCENARIOS)[ScenarioId]][]).map(([id,meta])=>{const rows=buildModelWithInputs(id,drawStandby,finance); const t=totals(rows); const trough=minCash(rows); const gp=rows.reduce((s,r)=>s+r.gp,0); const be=rows.find(r=>r.ebitda>=0)?.m??null; return {id,meta,t,trough,gp,be,last:rows.at(-1)!};}),[drawStandby,finance]);
  const measures: Array<[string,(c:ScenarioCase)=>string|number]> = [["36M units",c=>c.t.units],["36M revenue",c=>lakh(c.t.revenue,1)],["36M gross profit",c=>money(c.gp)],["Funding required",c=>money(c.t.funding)],["Cash trough",c=>money(c.trough.cash)],["Trough month",c=>`M${c.trough.m}`],["Break-even",c=>c.be?`M${c.be}`:"Not reached"],["Ending inventory",c=>money(c.last.inventory)]];
  return <div className="space-y-6"><div><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Decision analysis</p><h1 className="font-display text-4xl">Scenarios</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Three cases only: Base, Delayed and Stress. The point is not to predict perfectly; it is to see how timing, volume and cost changes alter cash and funding.</p></div>
    <div className="grid gap-4 lg:grid-cols-3">{cases.map(c=><button key={c.id} type="button" onClick={()=>setScenario(c.id)} className={`group rounded-xl border p-5 text-left ${active===c.id?"border-accent bg-accent/10":"border-border bg-surface hover:border-accent/50"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold text-fg">{c.meta.label}</p><p className="mt-1 text-xs font-medium text-accent">{c.meta.probability} confidence</p></div><span className="rounded-full border border-border px-2 py-1 text-[10px] uppercase tracking-wider text-subtle">{active===c.id?"Active":"Select"}</span></div><p className="mt-3 text-xs leading-5 text-muted">{c.meta.note}</p><div className="mt-4 grid grid-cols-2 gap-3"><ExplainableValue label="Funding" value={money(c.t.funding)} confidence={c.meta.probability} reasoning={["Funding timing follows the selected scenario schedule.","The shared finance model applies current volume, cost and cash assumptions."]} source="Finance · Planning" /><ExplainableValue label="Cash trough" value={money(c.trough.cash)} confidence={c.meta.probability} reasoning={[`Liquidity reaches its minimum in M${c.trough.m} under this scenario.`,"Cash is recalculated from the same operating and funding model used by Finance."]} source="Finance · Cash model" /></div></button>)}</div>
    <Panel title="Side-by-side decision table" kicker="Same assumptions · different scenario logic"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-border text-left text-xs text-subtle"><th className="px-3 py-3">Measure</th>{cases.map(c=><th key={c.id} className="px-3 py-3">{c.meta.label}</th>)}</tr></thead><tbody>{measures.map(([label,fn])=><tr key={label} className="border-b border-border/70"><td className="px-3 py-3 text-muted">{label}</td>{cases.map(c=><td key={c.id} className="px-3 py-3 tabular-nums text-fg">{fn(c)}</td>)}</tr>)}</tbody></table></div></Panel>
    <div className="grid gap-4 md:grid-cols-3">{cases.map(c=><Kpi key={c.id} label={`${c.meta.label} · funding`} value={money(c.t.funding)} hint={`Trough ${money(c.trough.cash)} at M${c.trough.m}`} tone={c.trough.cash<8?"danger":c.trough.cash<15?"warn":"ok"}/>)}</div>
    <div className="flex items-center justify-between rounded-xl border border-border bg-surface p-4"><div><p className="text-sm font-medium text-fg">Need to change the model?</p><p className="mt-1 text-xs text-muted">Go to assumptions rather than editing outputs. The model remains connected.</p></div><Link to="/command/finance-assumptions" className="text-sm text-accent hover:text-fg">Open assumptions →</Link></div>
  </div>
}
