import { useEffect, useState } from "react";
import { Kpi, Panel } from "@/components/kpi";
import { inr } from "@/lib/format";
import {
  createInventoryMovement,
  createProductionOrder,
  createPurchaseOrder,
  createSalesOrder,
  getPhase6AContext,
  listPhase6AOrders,
  listInventoryPosition,
  transitionProductionOrder,
  transitionPurchaseOrder,
  transitionSalesOrder,
} from "@/lib/operations/phase6a";
import type { VentureId, Phase6ARole } from "@/lib/operations/phase6a";

const ventures: VentureId[] = ["carbon", "aluminium", "consolidated"];
const labels: Record<VentureId, string> = { carbon: "Vyndi · Carbon Venture", aluminium: "Aluminium Bicycle Venture", consolidated: "Consolidated" };
const can = (role: Phase6ARole, permission: string) => role === "founder" || (role === "operations" && ["sales:create", "sales:transition", "purchase:create", "purchase:transition", "production:create", "production:transition", "inventory:create"].includes(permission)) || (role === "finance" && ["sales:transition", "purchase:transition"].includes(permission));

export function AuthoritativeErp() {
  const [role, setRole] = useState<Phase6ARole | null>(null);
  const [venture, setVenture] = useState<VentureId>("carbon");
  const [data, setData] = useState<any>({ sales: [], purchases: [], production: [], inventory: [], decisions: [] });
  const [positions, setPositions] = useState<any[]>([]);
  const [message, setMessage] = useState("");
  const [salesDraft, setSalesDraft] = useState({ customer: "", product: "", units: 1, valueInr: 0, month: 1 });
  const [poDraft, setPoDraft] = useState({ supplier: "", sku: "", item: "", qty: 1, unitCostInr: 0, expectedMonth: 1 });
  const [invDraft, setInvDraft] = useState({ sku: "", type: "receipt" as "receipt" | "reserve" | "consume" | "release" | "adjustment", qty: 1, unitCostInr: 0, refType: "manual", refId: "MANUAL" });

  async function refresh() {
    try {
      const [ctx, orders, stock] = await Promise.all([getPhase6AContext(), listPhase6AOrders(), listInventoryPosition({ data: { ventureId: venture } })]);
      setRole(ctx.role); setData(orders); setPositions(stock as any[]); setMessage("");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load authoritative operating data"); }
  }
  useEffect(() => { void refresh(); }, [venture]);
  const sales = data.sales.filter((x: any) => x.venture_id === venture && !["cancelled", "completed"].includes(x.status));
  const purchases = data.purchases.filter((x: any) => x.venture_id === venture && !["cancelled", "received"].includes(x.status));
  const production = data.production.filter((x: any) => x.venture_id === venture && x.status !== "cancelled");
  const orderValue = sales.reduce((n: number, x: any) => n + Number(x.value_inr), 0);
  const poValue = purchases.reduce((n: number, x: any) => n + Number(x.qty) * Number(x.unit_cost_inr), 0);

  async function run(action: () => Promise<unknown>) { try { await action(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Operation failed"); } }
  const readOnly = role === "investor" || role === "auditor";

  return <div className="space-y-6">
    <header><p className="text-[11px] uppercase tracking-[0.2em] text-subtle">Phase 6A · authoritative operating core</p><h1 className="mt-1 font-display text-4xl">ERP Execution Control</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Server-backed transactions with authenticated identity, venture scope and append-only audit events. Phase 5 remains the management view; this layer is the durable operational authority.</p></header>
    {message && <div className="rounded-lg border border-border bg-surface p-3 text-sm text-muted">{message}</div>}
    <Panel title="Operating boundary" kicker="Every durable transaction carries venture scope"><div className="flex flex-wrap gap-2">{ventures.map(v => <button key={v} type="button" onClick={() => setVenture(v)} className={`rounded-lg border px-4 py-2 text-sm font-semibold ${venture === v ? "border-accent bg-accent/10 text-accent" : "border-border text-muted"}`}>{labels[v]}</button>)}</div><p className="mt-3 text-xs text-muted">Identity: {role ?? "resolving"} · mutations are server-authorized</p></Panel>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Open sales units" value={String(sales.reduce((n: number, x: any) => n + Number(x.units), 0))} hint={labels[venture]}/><Kpi label="Order value" value={inr(orderValue)} hint="Durable sales orders"/><Kpi label="Open POs" value={String(purchases.length)} hint="Durable purchase orders"/><Kpi label="PO commitment" value={inr(poValue)} hint="Qty × unit cost"/><Kpi label="Production WIP" value={String(production.reduce((n: number, x: any) => n + Number(x.units), 0))} hint="Durable manufacturing orders"/></div>
    {!readOnly && can(role ?? "auditor", "sales:create") && <Panel title="Create sales order" kicker="Server mutation + audit event"><div className="grid gap-3 md:grid-cols-6"><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" placeholder="Customer" value={salesDraft.customer} onChange={e => setSalesDraft({...salesDraft, customer:e.target.value})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" placeholder="Product" value={salesDraft.product} onChange={e => setSalesDraft({...salesDraft, product:e.target.value})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" type="number" min="1" value={salesDraft.units} onChange={e => setSalesDraft({...salesDraft, units:Number(e.target.value)})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" type="number" min="1" placeholder="Value INR" value={salesDraft.valueInr} onChange={e => setSalesDraft({...salesDraft, valueInr:Number(e.target.value)})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" type="number" min="1" max="36" value={salesDraft.month} onChange={e => setSalesDraft({...salesDraft, month:Number(e.target.value)})}/><button className="rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg" onClick={() => void run(() => createSalesOrder({data:{ventureId:venture,...salesDraft}}))}>Create SO</button></div></Panel>}
    <Panel title="Authoritative sales orders" kicker="Persisted on the server"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-subtle"><tr><th className="p-3 text-left">SO</th><th className="p-3 text-left">Customer</th><th className="p-3 text-left">Product</th><th className="p-3 text-right">Units</th><th className="p-3 text-right">Value</th><th className="p-3">Status</th></tr></thead><tbody>{sales.map((x:any)=><tr key={x.id} className="border-t border-border"><td className="p-3 text-xs text-muted">{x.id}</td><td className="p-3">{x.customer}</td><td className="p-3">{x.product}</td><td className="p-3 text-right">{x.units}</td><td className="p-3 text-right">{inr(Number(x.value_inr))}</td><td className="p-3">{can(role ?? "auditor", "sales:transition") ? <select value={x.status} onChange={e=>void run(()=>transitionSalesOrder({data:{id:x.id,status:e.target.value as any}}))} className="rounded border border-border bg-bg px-2 py-1 text-xs"><option>draft</option><option>confirmed</option><option>completed</option><option>cancelled</option></select> : x.status}</td></tr>)}</tbody></table></div></Panel>
    {!readOnly && can(role ?? "auditor", "purchase:create") && <Panel title="Create purchase order" kicker="Server mutation + audit event"><div className="grid gap-3 md:grid-cols-7"><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" placeholder="Supplier" value={poDraft.supplier} onChange={e=>setPoDraft({...poDraft,supplier:e.target.value})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" placeholder="SKU" value={poDraft.sku} onChange={e=>setPoDraft({...poDraft,sku:e.target.value})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" placeholder="Item" value={poDraft.item} onChange={e=>setPoDraft({...poDraft,item:e.target.value})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" type="number" min="1" value={poDraft.qty} onChange={e=>setPoDraft({...poDraft,qty:Number(e.target.value)})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" type="number" min="0" placeholder="Unit cost" value={poDraft.unitCostInr} onChange={e=>setPoDraft({...poDraft,unitCostInr:Number(e.target.value)})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" type="number" min="1" max="36" value={poDraft.expectedMonth} onChange={e=>setPoDraft({...poDraft,expectedMonth:Number(e.target.value)})}/><button className="rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg" onClick={()=>void run(()=>createPurchaseOrder({data:{ventureId:venture,...poDraft}}))}>Create PO</button></div></Panel>}
    <Panel title="Authoritative purchase orders" kicker="Persisted on the server"><div className="space-y-2">{purchases.map((x:any)=><div key={x.id} className="grid gap-2 rounded-lg border border-border p-3 md:grid-cols-[auto_1fr_auto_auto]"><span className="text-xs text-muted">{x.id}</span><span><b>{x.item}</b><span className="block text-xs text-muted">{x.sku} · {x.supplier} · {x.qty} units</span></span><span>{inr(Number(x.qty)*Number(x.unit_cost_inr))}</span>{can(role ?? "auditor", "purchase:transition")?<select value={x.status} onChange={e=>void run(()=>transitionPurchaseOrder({data:{id:x.id,status:e.target.value as any}}))} className="rounded border border-border bg-bg px-2 py-1 text-xs"><option>draft</option><option>ordered</option><option>received</option><option>cancelled</option></select>:<span>{x.status}</span>}</div>)}</div></Panel>
    <Panel title="Inventory position" kicker="Derived only from immutable movement events"><div className="grid gap-2 md:grid-cols-3">{positions.map((x:any)=><div key={`${x.venture_id}-${x.sku}`} className="rounded-lg border border-border p-3"><span className="text-xs text-muted">{x.sku}</span><p className="mt-1 text-lg font-semibold tabular-nums">{Number(x.net_qty)}</p><p className="text-xs text-muted">net units</p></div>)}{positions.length===0&&<p className="text-sm text-muted">No inventory movements recorded for this venture.</p>}</div></Panel>
    {!readOnly && can(role ?? "auditor", "inventory:create") && <Panel title="Record inventory movement" kicker="Append-only · never edit or delete"><div className="grid gap-3 md:grid-cols-7"><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" placeholder="SKU" value={invDraft.sku} onChange={e=>setInvDraft({...invDraft,sku:e.target.value})}/><select className="rounded-md border border-border bg-bg px-2 py-2 text-sm" value={invDraft.type} onChange={e=>setInvDraft({...invDraft,type:e.target.value as any})}><option>receipt</option><option>reserve</option><option>consume</option><option>release</option><option>adjustment</option></select><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" type="number" value={invDraft.qty} onChange={e=>setInvDraft({...invDraft,qty:Number(e.target.value)})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" type="number" min="0" value={invDraft.unitCostInr} onChange={e=>setInvDraft({...invDraft,unitCostInr:Number(e.target.value)})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" placeholder="Ref type" value={invDraft.refType} onChange={e=>setInvDraft({...invDraft,refType:e.target.value})}/><input className="rounded-md border border-border bg-bg px-2 py-2 text-sm" placeholder="Ref ID" value={invDraft.refId} onChange={e=>setInvDraft({...invDraft,refId:e.target.value})}/><button className="rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg" onClick={()=>void run(()=>createInventoryMovement({data:{ventureId:venture,...invDraft}}))}>Record</button></div></Panel>}
    <Panel title="Production orders" kicker="Created against a durable sales order"><div className="mb-3">{!readOnly && can(role ?? "auditor", "production:create") && sales[0] && <button className="rounded-md bg-accent px-4 py-2 text-sm font-semibold text-bg" onClick={()=>void run(()=>createProductionOrder({data:{ventureId:venture,salesOrderId:sales[0].id,product:sales[0].product,units:Number(sales[0].units)}}))}>Create production order from latest SO</button>}</div><div className="space-y-2">{production.map((x:any)=><div key={x.id} className="grid gap-2 rounded-lg border border-border p-3 md:grid-cols-[auto_1fr_auto]"><span className="text-xs text-muted">{x.id}</span><span><b>{x.product} · {x.units} units</b><span className="block text-xs text-muted">SO {x.sales_order_id} · QC {x.qc_passed?"passed":"pending"}</span></span>{can(role ?? "auditor", "production:transition")?<select value={x.status} onChange={e=>void run(()=>transitionProductionOrder({data:{id:x.id,status:e.target.value as any}}))} className="rounded border border-border bg-bg px-2 py-1 text-xs"><option>planned</option><option>in-production</option><option>qc</option><option>finished</option><option>released</option><option>cancelled</option></select>:<span>{x.status}</span>}</div>)}</div><p className="mt-3 text-xs text-muted">Production creation is exposed as a server capability for the 6A control spine; approval prerequisites are intentionally completed in Phase 6B.</p></Panel>
  </div>;
}
