import { Link, Outlet, useLocation, useNavigate } from "@tanstack/react-router";
import { Activity, AlertTriangle, Bike, BookOpen, BrainCircuit, CheckSquare, ChevronDown, ClipboardCheck, Factory, Landmark, Lightbulb, Presentation, Rocket, Scale, UserRound, Wallet, Wrench, FileSpreadsheet, BadgeCheck, Ruler, LineChart, Boxes, Layers3, SlidersHorizontal, GitCompare, Cog, Shield, LogOut, FlaskConical, DraftingCompass, Radar, Workflow, Database } from "lucide-react";
import { useEffect, useState } from "react";
import { SiteHeader } from "@/components/site-header";
import { cn } from "@/lib/utils";
import { getCommandRole, lockCommand } from "@/lib/command-access";
type NavItem={to:string;label:string;icon:typeof Activity;exact?:boolean}; type NavGroup={label:string;icon:typeof Activity;items:NavItem[];defaultOpen?:boolean};
const GROUPS:NavGroup[]=[
  {label:"Overview",icon:Activity,defaultOpen:true,items:[{to:"/command",label:"Board",icon:Activity,exact:true},{to:"/command/control-tower",label:"Control Tower",icon:Radar},{to:"/command/management-intelligence",label:"Management Intelligence",icon:Lightbulb},{to:"/command/epr-workflow",label:"EPR Workflow",icon:Workflow},{to:"/command/epr-execution",label:"EPR Execution",icon:ClipboardCheck},{to:"/command/epr-live",label:"LIVE EPR · Transactions",icon:Database},{to:"/command/financial-cockpit",label:"Financial Cockpit",icon:Wallet}]},
  {label:"Execution Stages",icon:Rocket,defaultOpen:true,items:[{to:"/command/phase-4",label:"Phase 4 · Sales & Revenue",icon:LineChart},{to:"/command/phase-5",label:"Phase 5 · Engineering + QC",icon:DraftingCompass},{to:"/command/phase-6",label:"Phase 6 · Pilot Production",icon:Factory},{to:"/command/phase-6a",label:"Phase 6A · EPR Execution",icon:ClipboardCheck},{to:"/command/deployment-readiness",label:"Deployment Readiness",icon:Rocket}]},
  {label:"Finance",icon:Wallet,defaultOpen:true,items:[{to:"/command/finance-assumptions",label:"Plan & Assumptions",icon:SlidersHorizontal},{to:"/command/scenarios",label:"Scenarios",icon:GitCompare},{to:"/command/master-finance",label:"Master Finance",icon:Layers3},{to:"/command/aluminium-finance",label:"Aluminium Vertical",icon:Factory},{to:"/command/finance",label:"Finance",icon:Wallet},{to:"/command/finance-control",label:"Finance Control",icon:Wallet},{to:"/command/balance-sheet",label:"Balance Sheet",icon:FileSpreadsheet},{to:"/command/ca-audit",label:"CA Verification / Audit",icon:BadgeCheck},{to:"/command/funding",label:"Funding Intelligence",icon:Landmark},{to:"/command/cash",label:"Cash & Working Capital",icon:Wallet}]},
  {label:"Production",icon:Factory,defaultOpen:true,items:[{to:"/command/production",label:"Production Planning",icon:Cog},{to:"/command/operations",label:"Operations & Procurement",icon:Boxes},{to:"/command/manufacturing",label:"Manufacturing Controls",icon:Factory},{to:"/command/inventory",label:"Inventory Planning",icon:Boxes},{to:"/inventory",label:"Component Control",icon:Boxes},{to:"/command/ops",label:"Ops",icon:Landmark}]},
  {label:"Product & Technical",icon:Wrench,defaultOpen:true,items:[{to:"/command/product",label:"Product",icon:Bike},{to:"/command/bom",label:"BOM & Cost Engine",icon:Boxes},{to:"/command/engineering",label:"Engineering Control",icon:DraftingCompass},{to:"/command/quality",label:"Quality Control",icon:FlaskConical},{to:"/command/technical",label:"Technical",icon:Wrench},{to:"/command/design-philosophy",label:"Design Philosophy",icon:Ruler}]},
  {label:"Sales & Market",icon:LineChart,items:[{to:"/command/sales",label:"Sales Planning",icon:LineChart},{to:"/command/market-survey",label:"Market Survey",icon:LineChart},{to:"/command/gtm",label:"GTM",icon:Shield}]},
  {label:"Legal & Risk",icon:Scale,items:[{to:"/command/legal",label:"Legal",icon:Scale},{to:"/command/legal-control",label:"Legal Control",icon:Scale},{to:"/command/risk",label:"Risk",icon:AlertTriangle}]},
  {label:"Leadership & Investors",icon:Presentation,items:[{to:"/command/founder-command",label:"Founder Command",icon:UserRound},{to:"/command/investor-pitch",label:"Investor Pitch",icon:Presentation},{to:"/command/investor-board",label:"Investor / Board",icon:Presentation}]},
  {label:"Knowledge & Delivery",icon:BookOpen,items:[{to:"/command/ai-knowledge",label:"AI / Knowledge",icon:BrainCircuit},{to:"/command/qa-verification",label:"QA / Verification",icon:ClipboardCheck},{to:"/command/actions",label:"Action Log",icon:CheckSquare},{to:"/command/knowledge",label:"45-Point Knowledge Register",icon:BookOpen}]},
];
function Group({group}:{group:NavGroup}){const location=useLocation();const active=group.items.some(item=>location.pathname===item.to||(!item.exact&&location.pathname.startsWith(`${item.to}/`)));return <details open={active||group.defaultOpen} className="group/section"><summary className="flex cursor-pointer list-none items-center gap-2 rounded-md px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-subtle hover:bg-surface hover:text-fg [&::-webkit-details-marker]:hidden"><group.icon className="size-3.5 shrink-0"/><span className="flex-1">{group.label}</span><ChevronDown className="size-3 transition-transform group-open/section:rotate-180"/></summary><div className="ml-2 mt-1 space-y-0.5 border-l border-border pl-2">{group.items.map(item=><Link key={item.to} to={item.to as never} activeOptions={item.exact?{exact:true}:undefined} className="flex items-center gap-2 rounded-md px-3 py-2 text-sm text-muted transition-colors duration-150 hover:bg-surface hover:text-fg" activeProps={{className:"bg-surface text-fg"}}><item.icon className="size-4 shrink-0"/>{item.label}</Link>)}</div></details>}
export function CommandShell(){const navigate=useNavigate();const[role,setRole]=useState<"admin"|"viewer"|null>(null);const[loggingOut,setLoggingOut]=useState(false);useEffect(()=>{getCommandRole().then(setRole).catch(()=>setRole(null))},[]);const viewer=role==="viewer";async function logout(){if(loggingOut)return;setLoggingOut(true);try{await lockCommand();setRole(null);await navigate({to:"/command-login"})}finally{setLoggingOut(false)}}return <div className="min-h-dvh bg-bg"><SiteHeader/><div className="mx-auto flex max-w-7xl"><aside className="sticky top-14 hidden h-[calc(100dvh-3.5rem)] w-64 shrink-0 flex-col border-r border-border py-6 lg:flex"><p className="px-5 pb-3 text-[10px] uppercase tracking-[0.2em] text-subtle">VINDY · Command</p><nav className="min-h-0 flex-1 space-y-2 overflow-y-auto px-2 pb-4 pr-1 [scrollbar-width:thin]">{GROUPS.map(group=><Group key={group.label} group={group}/>)}</nav><div className="px-3 pt-3"><button type="button" onClick={logout} disabled={loggingOut} className="flex w-full items-center gap-2 rounded-md border border-border px-3 py-2 text-sm text-muted hover:bg-surface hover:text-fg disabled:opacity-50"><LogOut className="size-4"/>{loggingOut?"Logging out…":`Log out${viewer?" · User":role==="admin"?" · Admin":""}`}</button></div></aside><div className="min-w-0 flex-1"><div className="flex gap-1 overflow-x-auto border-b border-border px-3 py-2 lg:hidden [scrollbar-width:thin]">{GROUPS.flatMap(g=>g.items).map(item=><Link key={item.to} to={item.to as never} activeOptions={item.exact?{exact:true}:undefined} className={cn("shrink-0 rounded-md px-3 py-2 text-xs text-muted")} activeProps={{className:"bg-surface text-fg"}}>{item.label}</Link>)}<button type="button" onClick={logout} disabled={loggingOut} className="shrink-0 rounded-md border border-border px-3 py-2 text-xs text-muted disabled:opacity-50">{loggingOut?"Logging out…":"Log out"}</button></div><div className="px-4 py-6 sm:px-6 lg:px-8"><div className={cn(viewer&&"pointer-events-none select-none opacity-95")}><fieldset disabled={viewer} className="min-w-0 border-0 p-0 m-0"><Outlet/></fieldset></div></div></div></div></div>}
