/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandRouteRouteImport } from './routes/command/route'
import { Route as RangeRouteImport } from './routes/range'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as CommandIndexRouteImport } from './routes/command/index'
import { Route as CommandActionsRouteImport } from './routes/command/actions'
import { Route as CommandAiKnowledgeRouteImport } from './routes/command/ai-knowledge'
import { Route as CommandDeploymentReadinessRouteImport } from './routes/command/deployment-readiness'
import { Route as CommandErpExecutionRouteImport } from './routes/command/erp-execution'
import { Route as CommandFinanceRouteImport } from './routes/command/finance'
import { Route as CommandFinanceControlRouteImport } from './routes/command/finance-control'
import { Route as CommandFounderCommandRouteImport } from './routes/command/founder-command'
import { Route as CommandFundingRouteImport } from './routes/command/funding'
import { Route as CommandGtmRouteImport } from './routes/command/gtm'
import { Route as CommandIntelligenceRouteImport } from './routes/command/intelligence'
import { Route as CommandInvestorBoardRouteImport } from './routes/command/investor-board'
import { Route as CommandKnowledgeRouteImport } from './routes/command/knowledge'
import { Route as CommandLegalRouteImport } from './routes/command/legal'
import { Route as CommandLegalControlRouteImport } from './routes/command/legal-control'
import { Route as CommandManufacturingRouteImport } from './routes/command/manufacturing'
import { Route as CommandOpsRouteImport } from './routes/command/ops'
import { Route as CommandProductRouteImport } from './routes/command/product'
import { Route as CommandQaVerificationRouteImport } from './routes/command/qa-verification'
import { Route as CommandRiskRouteImport } from './routes/command/risk'
import { Route as CommandTechnicalRouteImport } from './routes/command/technical'
import { Route as RangeTierRouteImport } from './routes/range.$tier'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const CommandRouteRoute = CommandRouteRouteImport.update({ id: '/command', path: '/command', getParentRoute: () => rootRouteImport } as any)
const RangeRoute = RangeRouteImport.update({ id: '/range', path: '/range', getParentRoute: () => rootRouteImport } as any)
const ApiHealthRoute = ApiHealthRouteImport.update({ id: '/api/health', path: '/api/health', getParentRoute: () => rootRouteImport } as any)

const CommandIndexRoute = CommandIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => CommandRouteRoute } as any)
const CommandActionsRoute = CommandActionsRouteImport.update({ id: '/actions', path: '/actions', getParentRoute: () => CommandRouteRoute } as any)
const CommandAiKnowledgeRoute = CommandAiKnowledgeRouteImport.update({ id: '/ai-knowledge', path: '/ai-knowledge', getParentRoute: () => CommandRouteRoute } as any)
const CommandDeploymentReadinessRoute = CommandDeploymentReadinessRouteImport.update({ id: '/deployment-readiness', path: '/deployment-readiness', getParentRoute: () => CommandRouteRoute } as any)
const CommandErpExecutionRoute = CommandErpExecutionRouteImport.update({ id: '/erp-execution', path: '/erp-execution', getParentRoute: () => CommandRouteRoute } as any)
const CommandFinanceRoute = CommandFinanceRouteImport.update({ id: '/finance', path: '/finance', getParentRoute: () => CommandRouteRoute } as any)
const CommandFinanceControlRoute = CommandFinanceControlRouteImport.update({ id: '/finance-control', path: '/finance-control', getParentRoute: () => CommandRouteRoute } as any)
const CommandFounderCommandRoute = CommandFounderCommandRouteImport.update({ id: '/founder-command', path: '/founder-command', getParentRoute: () => CommandRouteRoute } as any)
const CommandFundingRoute = CommandFundingRouteImport.update({ id: '/funding', path: '/funding', getParentRoute: () => CommandRouteRoute } as any)
const CommandGtmRoute = CommandGtmRouteImport.update({ id: '/gtm', path: '/gtm', getParentRoute: () => CommandRouteRoute } as any)
const CommandIntelligenceRoute = CommandIntelligenceRouteImport.update({ id: '/intelligence', path: '/intelligence', getParentRoute: () => CommandRouteRoute } as any)
const CommandInvestorBoardRoute = CommandInvestorBoardRouteImport.update({ id: '/investor-board', path: '/investor-board', getParentRoute: () => CommandRouteRoute } as any)
const CommandKnowledgeRoute = CommandKnowledgeRouteImport.update({ id: '/knowledge', path: '/knowledge', getParentRoute: () => CommandRouteRoute } as any)
const CommandLegalRoute = CommandLegalRouteImport.update({ id: '/legal', path: '/legal', getParentRoute: () => CommandRouteRoute } as any)
const CommandLegalControlRoute = CommandLegalControlRouteImport.update({ id: '/legal-control', path: '/legal-control', getParentRoute: () => CommandRouteRoute } as any)
const CommandManufacturingRoute = CommandManufacturingRouteImport.update({ id: '/manufacturing', path: '/manufacturing', getParentRoute: () => CommandRouteRoute } as any)
const CommandOpsRoute = CommandOpsRouteImport.update({ id: '/ops', path: '/ops', getParentRoute: () => CommandRouteRoute } as any)
const CommandProductRoute = CommandProductRouteImport.update({ id: '/product', path: '/product', getParentRoute: () => CommandRouteRoute } as any)
const CommandQaVerificationRoute = CommandQaVerificationRouteImport.update({ id: '/qa-verification', path: '/qa-verification', getParentRoute: () => CommandRouteRoute } as any)
const CommandRiskRoute = CommandRiskRouteImport.update({ id: '/risk', path: '/risk', getParentRoute: () => CommandRouteRoute } as any)
const CommandTechnicalRoute = CommandTechnicalRouteImport.update({ id: '/technical', path: '/technical', getParentRoute: () => CommandRouteRoute } as any)
const RangeTierRoute = RangeTierRouteImport.update({ id: '/$tier', path: '/$tier', getParentRoute: () => RangeRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/command': typeof CommandRouteRouteWithChildren
  '/range': typeof RangeRouteWithChildren
  '/command/actions': typeof CommandActionsRoute
  '/command/ai-knowledge': typeof CommandAiKnowledgeRoute
  '/command/deployment-readiness': typeof CommandDeploymentReadinessRoute
  '/command/erp-execution': typeof CommandErpExecutionRoute
  '/command/finance': typeof CommandFinanceRoute
  '/command/finance-control': typeof CommandFinanceControlRoute
  '/command/founder-command': typeof CommandFounderCommandRoute
  '/command/funding': typeof CommandFundingRoute
  '/command/gtm': typeof CommandGtmRoute
  '/command/intelligence': typeof CommandIntelligenceRoute
  '/command/investor-board': typeof CommandInvestorBoardRoute
  '/command/knowledge': typeof CommandKnowledgeRoute
  '/command/legal': typeof CommandLegalRoute
  '/command/legal-control': typeof CommandLegalControlRoute
  '/command/manufacturing': typeof CommandManufacturingRoute
  '/command/ops': typeof CommandOpsRoute
  '/command/product': typeof CommandProductRoute
  '/command/qa-verification': typeof CommandQaVerificationRoute
  '/command/risk': typeof CommandRiskRoute
  '/command/technical': typeof CommandTechnicalRoute
  '/range/$tier': typeof RangeTierRoute
  '/command/': typeof CommandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/range': typeof RangeRouteWithChildren
  '/command/actions': typeof CommandActionsRoute
  '/command/ai-knowledge': typeof CommandAiKnowledgeRoute
  '/command/deployment-readiness': typeof CommandDeploymentReadinessRoute
  '/command/erp-execution': typeof CommandErpExecutionRoute
  '/command/finance': typeof CommandFinanceRoute
  '/command/finance-control': typeof CommandFinanceControlRoute
  '/command/founder-command': typeof CommandFounderCommandRoute
  '/command/funding': typeof CommandFundingRoute
  '/command/gtm': typeof CommandGtmRoute
  '/command/intelligence': typeof CommandIntelligenceRoute
  '/command/investor-board': typeof CommandInvestorBoardRoute
  '/command/knowledge': typeof CommandKnowledgeRoute
  '/command/legal': typeof CommandLegalRoute
  '/command/legal-control': typeof CommandLegalControlRoute
  '/command/manufacturing': typeof CommandManufacturingRoute
  '/command/ops': typeof CommandOpsRoute
  '/command/product': typeof CommandProductRoute
  '/command/qa-verification': typeof CommandQaVerificationRoute
  '/command/risk': typeof CommandRiskRoute
  '/command/technical': typeof CommandTechnicalRoute
  '/range/$tier': typeof RangeTierRoute
  '/command': typeof CommandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/command': typeof CommandRouteRouteWithChildren
  '/range': typeof RangeRouteWithChildren
  '/command/actions': typeof CommandActionsRoute
  '/command/ai-knowledge': typeof CommandAiKnowledgeRoute
  '/command/deployment-readiness': typeof CommandDeploymentReadinessRoute
  '/command/erp-execution': typeof CommandErpExecutionRoute
  '/command/finance': typeof CommandFinanceRoute
  '/command/finance-control': typeof CommandFinanceControlRoute
  '/command/founder-command': typeof CommandFounderCommandRoute
  '/command/funding': typeof CommandFundingRoute
  '/command/gtm': typeof CommandGtmRoute
  '/command/intelligence': typeof CommandIntelligenceRoute
  '/command/investor-board': typeof CommandInvestorBoardRoute
  '/command/knowledge': typeof CommandKnowledgeRoute
  '/command/legal': typeof CommandLegalRoute
  '/command/legal-control': typeof CommandLegalControlRoute
  '/command/manufacturing': typeof CommandManufacturingRoute
  '/command/ops': typeof CommandOpsRoute
  '/command/product': typeof CommandProductRoute
  '/command/qa-verification': typeof CommandQaVerificationRoute
  '/command/risk': typeof CommandRiskRoute
  '/command/technical': typeof CommandTechnicalRoute
  '/range/$tier': typeof RangeTierRoute
  '/command/': typeof CommandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CommandRouteRoute: typeof CommandRouteRouteWithChildren
  RangeRoute: typeof RangeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/api/health': { id: '/api/health'; path: '/api/health'; fullPath: '/api/health'; preLoaderRoute: typeof ApiHealthRouteImport; parentRoute: typeof rootRouteImport }
    '/command': { id: '/command'; path: '/command'; fullPath: '/command'; preLoaderRoute: typeof CommandRouteRouteImport; parentRoute: typeof rootRouteImport }
    '/range': { id: '/range'; path: '/range'; fullPath: '/range'; preLoaderRoute: typeof RangeRouteImport; parentRoute: typeof rootRouteImport }
    '/command/': { id: '/command/'; path: '/'; fullPath: '/command/'; preLoaderRoute: typeof CommandIndexRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/actions': { id: '/command/actions'; path: '/actions'; fullPath: '/command/actions'; preLoaderRoute: typeof CommandActionsRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/ai-knowledge': { id: '/command/ai-knowledge'; path: '/ai-knowledge'; fullPath: '/command/ai-knowledge'; preLoaderRoute: typeof CommandAiKnowledgeRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/deployment-readiness': { id: '/command/deployment-readiness'; path: '/deployment-readiness'; fullPath: '/command/deployment-readiness'; preLoaderRoute: typeof CommandDeploymentReadinessRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/erp-execution': { id: '/command/erp-execution'; path: '/erp-execution'; fullPath: '/command/erp-execution'; preLoaderRoute: typeof CommandErpExecutionRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/finance': { id: '/command/finance'; path: '/finance'; fullPath: '/command/finance'; preLoaderRoute: typeof CommandFinanceRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/finance-control': { id: '/command/finance-control'; path: '/finance-control'; fullPath: '/command/finance-control'; preLoaderRoute: typeof CommandFinanceControlRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/founder-command': { id: '/command/founder-command'; path: '/founder-command'; fullPath: '/command/founder-command'; preLoaderRoute: typeof CommandFounderCommandRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/funding': { id: '/command/funding'; path: '/funding'; fullPath: '/command/funding'; preLoaderRoute: typeof CommandFundingRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/gtm': { id: '/command/gtm'; path: '/gtm'; fullPath: '/command/gtm'; preLoaderRoute: typeof CommandGtmRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/intelligence': { id: '/command/intelligence'; path: '/intelligence'; fullPath: '/command/intelligence'; preLoaderRoute: typeof CommandIntelligenceRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/investor-board': { id: '/command/investor-board'; path: '/investor-board'; fullPath: '/command/investor-board'; preLoaderRoute: typeof CommandInvestorBoardRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/knowledge': { id: '/command/knowledge'; path: '/knowledge'; fullPath: '/command/knowledge'; preLoaderRoute: typeof CommandKnowledgeRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/legal': { id: '/command/legal'; path: '/legal'; fullPath: '/command/legal'; preLoaderRoute: typeof CommandLegalRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/legal-control': { id: '/command/legal-control'; path: '/legal-control'; fullPath: '/command/legal-control'; preLoaderRoute: typeof CommandLegalControlRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/manufacturing': { id: '/command/manufacturing'; path: '/manufacturing'; fullPath: '/command/manufacturing'; preLoaderRoute: typeof CommandManufacturingRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/ops': { id: '/command/ops'; path: '/ops'; fullPath: '/command/ops'; preLoaderRoute: typeof CommandOpsRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/product': { id: '/command/product'; path: '/product'; fullPath: '/command/product'; preLoaderRoute: typeof CommandProductRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/qa-verification': { id: '/command/qa-verification'; path: '/qa-verification'; fullPath: '/command/qa-verification'; preLoaderRoute: typeof CommandQaVerificationRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/risk': { id: '/command/risk'; path: '/risk'; fullPath: '/command/risk'; preLoaderRoute: typeof CommandRiskRouteImport; parentRoute: typeof CommandRouteRoute }
    '/command/technical': { id: '/command/technical'; path: '/technical'; fullPath: '/command/technical'; preLoaderRoute: typeof CommandTechnicalRouteImport; parentRoute: typeof CommandRouteRoute }
    '/range/$tier': { id: '/range/$tier'; path: '/$tier'; fullPath: '/range/$tier'; preLoaderRoute: typeof RangeTierRouteImport; parentRoute: typeof RangeRoute }
  }
}

interface CommandRouteRouteChildren {
  CommandActionsRoute: typeof CommandActionsRoute
  CommandAiKnowledgeRoute: typeof CommandAiKnowledgeRoute
  CommandDeploymentReadinessRoute: typeof CommandDeploymentReadinessRoute
  CommandErpExecutionRoute: typeof CommandErpExecutionRoute
  CommandFinanceRoute: typeof CommandFinanceRoute
  CommandFinanceControlRoute: typeof CommandFinanceControlRoute
  CommandFounderCommandRoute: typeof CommandFounderCommandRoute
  CommandFundingRoute: typeof CommandFundingRoute
  CommandGtmRoute: typeof CommandGtmRoute
  CommandIntelligenceRoute: typeof CommandIntelligenceRoute
  CommandInvestorBoardRoute: typeof CommandInvestorBoardRoute
  CommandKnowledgeRoute: typeof CommandKnowledgeRoute
  CommandLegalRoute: typeof CommandLegalRoute
  CommandLegalControlRoute: typeof CommandLegalControlRoute
  CommandManufacturingRoute: typeof CommandManufacturingRoute
  CommandOpsRoute: typeof CommandOpsRoute
  CommandProductRoute: typeof CommandProductRoute
  CommandQaVerificationRoute: typeof CommandQaVerificationRoute
  CommandRiskRoute: typeof CommandRiskRoute
  CommandTechnicalRoute: typeof CommandTechnicalRoute
  CommandIndexRoute: typeof CommandIndexRoute
}
const CommandRouteRouteChildren: CommandRouteRouteChildren = {
  CommandActionsRoute,
  CommandAiKnowledgeRoute,
  CommandDeploymentReadinessRoute,
  CommandErpExecutionRoute,
  CommandFinanceRoute,
  CommandFinanceControlRoute,
  CommandFounderCommandRoute,
  CommandFundingRoute,
  CommandGtmRoute,
  CommandIntelligenceRoute,
  CommandInvestorBoardRoute,
  CommandKnowledgeRoute,
  CommandLegalRoute,
  CommandLegalControlRoute,
  CommandManufacturingRoute,
  CommandOpsRoute,
  CommandProductRoute,
  CommandQaVerificationRoute,
  CommandRiskRoute,
  CommandTechnicalRoute,
  CommandIndexRoute,
}
const CommandRouteRouteWithChildren = CommandRouteRoute._addFileChildren(CommandRouteRouteChildren)

interface RangeRouteChildren { RangeTierRoute: typeof RangeTierRoute }
const RangeRouteChildren: RangeRouteChildren = { RangeTierRoute }
const RangeRouteWithChildren = RangeRoute._addFileChildren(RangeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  ApiHealthRoute,
  CommandRouteRoute: CommandRouteRouteWithChildren,
  RangeRoute: RangeRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
