/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandRouteRouteImport } from './routes/command/route'
import { Route as RangeRouteImport } from './routes/range'
import { Route as CommandIndexRouteImport } from './routes/command/index'
import { Route as CommandActionsRouteImport } from './routes/command/actions'
import { Route as CommandFinanceRouteImport } from './routes/command/finance'
import { Route as CommandGtmRouteImport } from './routes/command/gtm'
import { Route as CommandLegalRouteImport } from './routes/command/legal'
import { Route as CommandOpsRouteImport } from './routes/command/ops'
import { Route as CommandProductRouteImport } from './routes/command/product'
import { Route as CommandRiskRouteImport } from './routes/command/risk'
import { Route as RangeTierRouteImport } from './routes/range.$tier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRouteRoute = CommandRouteRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const RangeRoute = RangeRouteImport.update({
  id: '/range',
  path: '/range',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIndexRoute = CommandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommandRouteRoute,
} as any)
const CommandActionsRoute = CommandActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => CommandRouteRoute,
} as any)
const CommandFinanceRoute = CommandFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => CommandRouteRoute,
} as any)
const CommandGtmRoute = CommandGtmRouteImport.update({
  id: '/gtm',
  path: '/gtm',
  getParentRoute: () => CommandRouteRoute,
} as any)
const CommandLegalRoute = CommandLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => CommandRouteRoute,
} as any)
const CommandOpsRoute = CommandOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => CommandRouteRoute,
} as any)
const CommandProductRoute = CommandProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => CommandRouteRoute,
} as any)
const CommandRiskRoute = CommandRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => CommandRouteRoute,
} as any)
const RangeTierRoute = RangeTierRouteImport.update({
  id: '/$tier',
  path: '/$tier',
  getParentRoute: () => RangeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRouteRouteWithChildren
  '/range': typeof RangeRouteWithChildren
  '/command/actions': typeof CommandActionsRoute
  '/command/finance': typeof CommandFinanceRoute
  '/command/gtm': typeof CommandGtmRoute
  '/command/legal': typeof CommandLegalRoute
  '/command/ops': typeof CommandOpsRoute
  '/command/product': typeof CommandProductRoute
  '/command/risk': typeof CommandRiskRoute
  '/range/$tier': typeof RangeTierRoute
  '/command/': typeof CommandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/range': typeof RangeRouteWithChildren
  '/command/actions': typeof CommandActionsRoute
  '/command/finance': typeof CommandFinanceRoute
  '/command/gtm': typeof CommandGtmRoute
  '/command/legal': typeof CommandLegalRoute
  '/command/ops': typeof CommandOpsRoute
  '/command/product': typeof CommandProductRoute
  '/command/risk': typeof CommandRiskRoute
  '/range/$tier': typeof RangeTierRoute
  '/command': typeof CommandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRouteRouteWithChildren
  '/range': typeof RangeRouteWithChildren
  '/command/actions': typeof CommandActionsRoute
  '/command/finance': typeof CommandFinanceRoute
  '/command/gtm': typeof CommandGtmRoute
  '/command/legal': typeof CommandLegalRoute
  '/command/ops': typeof CommandOpsRoute
  '/command/product': typeof CommandProductRoute
  '/command/risk': typeof CommandRiskRoute
  '/range/$tier': typeof RangeTierRoute
  '/command/': typeof CommandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/range'
    | '/command/actions'
    | '/command/finance'
    | '/command/gtm'
    | '/command/legal'
    | '/command/ops'
    | '/command/product'
    | '/command/risk'
    | '/range/$tier'
    | '/command/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/range'
    | '/command/actions'
    | '/command/finance'
    | '/command/gtm'
    | '/command/legal'
    | '/command/ops'
    | '/command/product'
    | '/command/risk'
    | '/range/$tier'
    | '/command'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/range'
    | '/command/actions'
    | '/command/finance'
    | '/command/gtm'
    | '/command/legal'
    | '/command/ops'
    | '/command/product'
    | '/command/risk'
    | '/range/$tier'
    | '/command/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRouteRoute: typeof CommandRouteRouteWithChildren
  RangeRoute: typeof RangeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/range': {
      id: '/range'
      path: '/range'
      fullPath: '/range'
      preLoaderRoute: typeof RangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/': {
      id: '/command/'
      path: '/'
      fullPath: '/command/'
      preLoaderRoute: typeof CommandIndexRouteImport
      parentRoute: typeof CommandRouteRoute
    }
    '/command/actions': {
      id: '/command/actions'
      path: '/actions'
      fullPath: '/command/actions'
      preLoaderRoute: typeof CommandActionsRouteImport
      parentRoute: typeof CommandRouteRoute
    }
    '/command/finance': {
      id: '/command/finance'
      path: '/finance'
      fullPath: '/command/finance'
      preLoaderRoute: typeof CommandFinanceRouteImport
      parentRoute: typeof CommandRouteRoute
    }
    '/command/gtm': {
      id: '/command/gtm'
      path: '/gtm'
      fullPath: '/command/gtm'
      preLoaderRoute: typeof CommandGtmRouteImport
      parentRoute: typeof CommandRouteRoute
    }
    '/command/legal': {
      id: '/command/legal'
      path: '/legal'
      fullPath: '/command/legal'
      preLoaderRoute: typeof CommandLegalRouteImport
      parentRoute: typeof CommandRouteRoute
    }
    '/command/ops': {
      id: '/command/ops'
      path: '/ops'
      fullPath: '/command/ops'
      preLoaderRoute: typeof CommandOpsRouteImport
      parentRoute: typeof CommandRouteRoute
    }
    '/command/product': {
      id: '/command/product'
      path: '/product'
      fullPath: '/command/product'
      preLoaderRoute: typeof CommandProductRouteImport
      parentRoute: typeof CommandRouteRoute
    }
    '/command/risk': {
      id: '/command/risk'
      path: '/risk'
      fullPath: '/command/risk'
      preLoaderRoute: typeof CommandRiskRouteImport
      parentRoute: typeof CommandRouteRoute
    }
    '/range/$tier': {
      id: '/range/$tier'
      path: '/$tier'
      fullPath: '/range/$tier'
      preLoaderRoute: typeof RangeTierRouteImport
      parentRoute: typeof RangeRoute
    }
  }
}

interface CommandRouteRouteChildren {
  CommandActionsRoute: typeof CommandActionsRoute
  CommandFinanceRoute: typeof CommandFinanceRoute
  CommandGtmRoute: typeof CommandGtmRoute
  CommandLegalRoute: typeof CommandLegalRoute
  CommandOpsRoute: typeof CommandOpsRoute
  CommandProductRoute: typeof CommandProductRoute
  CommandRiskRoute: typeof CommandRiskRoute
  CommandIndexRoute: typeof CommandIndexRoute
}

const CommandRouteRouteChildren: CommandRouteRouteChildren = {
  CommandActionsRoute: CommandActionsRoute,
  CommandFinanceRoute: CommandFinanceRoute,
  CommandGtmRoute: CommandGtmRoute,
  CommandLegalRoute: CommandLegalRoute,
  CommandOpsRoute: CommandOpsRoute,
  CommandProductRoute: CommandProductRoute,
  CommandRiskRoute: CommandRiskRoute,
  CommandIndexRoute: CommandIndexRoute,
}

const CommandRouteRouteWithChildren = CommandRouteRoute._addFileChildren(
  CommandRouteRouteChildren,
)

interface RangeRouteChildren {
  RangeTierRoute: typeof RangeTierRoute
}

const RangeRouteChildren: RangeRouteChildren = {
  RangeTierRoute: RangeTierRoute,
}

const RangeRouteWithChildren = RangeRoute._addFileChildren(RangeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRouteRoute: CommandRouteRouteWithChildren,
  RangeRoute: RangeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
